grails-app/i18n/messages.properties
grails-app/i18n/messages_fr.properties

updated messages*.properties to include translations for new reason code

Added translations for new reason code fixed #123

---

grails-app/services/org/pih/warehouse/shipping/ShipmentService.groovy
grails-app/taglib/org/pih/warehouse/SelectTagLib.groovy

* OBPIH-733 Allow rollback of all shipment events, not just sending and receiving
* OBPIH-740 Fixed bug with Create Stock Requisition workflow where stock list dropdown was only showing the first 10 stock lists

Hotfix/release 0.7.28

---

grails-app/controllers/org/pih/warehouse/stockMovement/StockMovementController.groovy
grails-app/i18n/messages.properties
grails-app/views/dashboard/megamenu.gsp
grails-app/views/stockMovement/_create.gsp

https://tickets.pih-emr.org/browse/OBPIH-826

OBPIH-826: New template for upcoming shipment feature.

---

grails-app/views/layouts/main.gsp
grails-app/views/stockMovement/_create.gsp
package.json
src/css/main.scss
src/js/components/Layout/Breadcrumbs.jsx
src/js/components/Layout/Header.jsx
src/js/components/Layout/MainLayout.jsx
src/js/components/Layout/MainLayoutRoute.jsx
src/js/components/Layout/Menu.jsx
src/js/components/Layout/Navbar.jsx
src/js/components/StockMovement.jsx
src/js/components/app.jsx
src/js/en.js
src/js/index.jsx
src/js/tests/StockMovement.test.jsx
webpack.config.js

https://tickets.pih-emr.org/browse/OBPIH-833

Create a layout for new react pages that mimics the custom layout

---

package.json
src/css/main.scss
src/js/components/LanguageSelector.jsx
src/js/components/Layout/Header.jsx
src/js/components/Layout/Menu.jsx
src/js/en.js
src/js/fr.js
src/js/index.jsx
src/js/reducers/index.jsx

https://tickets.pih-emr.org/browse/OBPIH-853

Multiple languages support.

---

src/js/actions/index.js
src/js/actions/types.js
src/js/components/stock-movement-wizard/AddItemsPage.jsx
src/js/components/stock-movement-wizard/CreateStockMovement.jsx
src/js/reducers/index.jsx
src/js/reducers/locationsReducer.jsx
src/js/reducers/productsReducer.jsx
src/js/reducers/usersReducer.jsx

I moved some repeating api request to redux. Now we wont refetch some data that should not change frequently.
example:
Data from /api/generic/person is used on step 1 and 2, so we fetch this only once and store it in redux.

Move some API requests to redux

---

src/css/main.scss
src/js/components/receiving/ReceivingCheckScreen.jsx

Strike through quantity remaining when checkbox is checked so user can be sure it is canceled.

OBPIH-917 change quantity remaining field's look when it is canceled

---

src/groovy/org/pih/warehouse/api/StockMovement.groovy
src/js/components/stock-movement-wizard/StockMovement.jsx

To make the stock movement name easier to read, use capital or lower case letter according to how those pieces are named in the system rather than defaulting to all caps.

OBPIH-1157 Tweak stock movement name

---

src/js/components/stock-movement-wizard/AddItemsPage.jsx

This should work the same as the create stock movement from a depot page—lines are added as you tab through

OBPIH-1151 add lines automatically to stock movement from a vendor

---

src/js/components/put-away/PutAwayCheckPage.jsx
src/js/components/put-away/PutAwayPage.jsx
src/js/components/put-away/PutAwaySecondPage.jsx
src/js/components/receiving/PartialReceivingPage.jsx
src/js/components/receiving/ReceivingCheckScreen.jsx
src/js/components/stock-movement-wizard/EditPage.jsx
src/js/components/stock-movement-wizard/PickPage.jsx
src/js/components/stock-movement-wizard/SendMovementPage.jsx
src/js/components/stock-movement-wizard/modals/AdjustInventoryModal.jsx
src/js/components/stock-movement-wizard/modals/EditPickModal.jsx
src/js/components/stock-movement-wizard/modals/SubstitutionsModal.jsx

For all item quantities on new React pages, if number is over four digits, add comma(s) to make numbers easier to read.

OBPIH-1156 Format quantities with commas

---

src/js/components/receiving/PartialReceivingPage.jsx
src/js/components/receiving/ReceivingPage.jsx
src/js/components/receiving/modals/EditLineModal.jsx
src/js/components/stock-movement-wizard/EditPage.jsx
src/js/components/stock-movement-wizard/modals/AdjustInventoryModal.jsx
src/js/components/stock-movement-wizard/modals/EditPickModal.jsx
src/js/components/stock-movement-wizard/modals/PackingSplitLineModal.jsx
src/js/components/stock-movement-wizard/modals/SubstitutionsModal.jsx

1. "autofill qtys" button on receipt page should not autofill a negative qty if shipped - received <0. Calculation should be max(0, shipped - received)
2. If a user has entered a negative quantity, a validation error should occur when they click next that does not let them move to the final page without changing the amount to a positive qty.

OBPIH-1292 Add validation to prevent negative qty

---

src/js/components/stock-movement-wizard/EditPage.jsx

Enable save button on edit page and change condition in order to save revised items even if reason code is not given. item.reasonCode is not necessary in this condition because this field is always disabled if there is no quantityRevised.

OBPIH-1408 Enable save button on edit page

---

grails-app/services/org/pih/warehouse/inventory/StockMovementService.groovy

@jmiranda feature is ready (its ugly solution, but i spent most of the estimation time on debuggin/testing if everything is working), but we can merge it after release.
However I see this part https://github.com/openboxes/openboxes/blob/develop/grails-app/services/org/pih/warehouse/inventory/StockMovementService.groovy#L93 as a potential future refactor to split it in case of inbound and outbound sm.

OBPIH-1530: Fixed saving tracking nr, driver name and comments

---

grails-app/controllers/org/pih/warehouse/requisition/RequisitionTemplateController.groovy
grails-app/domain/org/pih/warehouse/requisition/Requisition.groovy
grails-app/domain/org/pih/warehouse/requisition/RequisitionItem.groovy
grails-app/i18n/messages.properties
grails-app/views/requisitionTemplate/_header.gsp
grails-app/views/requisitionTemplate/edit.gsp
src/groovy/org/pih/warehouse/api/StocklistItem.groovy

-Add column for unit cost and total cost per line on stock list details page
-Add place for total stock list value on left hand panel
-Include pricing in Excel export (unformatted version)
-Pricing is ignored for import
-Pricing is not visible on the page or on export if a user does not have financial user permissions.

OBPIH-1886 Add pricing information to stock list details page

---

grails-app/services/org/pih/warehouse/inventory/InventoryService.groovy

It doesn't seem to be necessary to hydrate the entire product object when retrieving the inventory level map. Grouping by product id works just as well and it provides a significant speed up (up to 8x in our informal testing) in the Browse inventory page.

Improve getCurrentInventory performance

---

docs/installation/docker.md

Should be merged after https://github.com/openboxes/openboxes-docker/pull/6.

Update docker-related documentation.

---

grails-app/controllers/org/pih/warehouse/core/LocationController.groovy
grails-app/domain/org/pih/warehouse/core/Organization.groovy
grails-app/services/org/pih/warehouse/core/OrganizationService.groovy

@jmiranda I found weird behavior here, hence "needs help". Could you review the code and this issue: 
When I create a location with supplier type, the proper organization is created and it has proper roles (Supplier and Manufacturer). That's good but when I create the second location with a supplier type, then the new organization is created (this is good), the proper roles are assigned (this is good) but these roles are removed from the first organization (I think this is wrong). This will happen for every new organization that is created (only the newest has assigned roles). Am I missing something here? Is it expected or I forgot about something?

OBPIH-2150: Find or create new organization on location page

---

src/js/components/tablero/Tablero.jsx

In the end the problem was just that the componentDidUpdate was always checking if the last locationId was = ' ' and was never executed. I changed it to the componentDidAmount which shouldn't be executed if the currentLocation is = ' '

OBPIH-3046 fix of the location not loading well

---

src/js/components/stock-movement-wizard/StockMovement.scss
src/js/components/stock-movement-wizard/outbound/AddItemsPage.jsx
src/js/components/stock-movement-wizard/outbound/EditPage.jsx
src/js/components/stock-movement-wizard/outbound/PackingPage.jsx
src/js/components/stock-movement-wizard/outbound/SendMovementPage.jsx
src/js/components/wizard/WizardSteps.scss

Header information should all show as text inputs, but should be tinted as read only if not editable. --> This part will be done in this ticket as it was the same part OBPIH-3260 : Stock movement design header and page fit changes

OBPIH-3259 Formatting Changes to Stock Movement Design

---

grails-app/services/org/pih/warehouse/core/UserService.groovy

Basically in that one I just control if a new graph has been added or if one has been removed checking if the size of the user config is still the same as the config in the config.groovy file.
If the size is the same we compare every keys in order to see if anything has changed.
We don't have to remove the user config because as soon as he will save a new config, his config will be updated taking as well the eventual graph added or removed.
In the end, with this fix, I don't think that we need a button to remove the user dashboardConfig. 
What do you think ? 
@awalkowiak @jmiranda

OBPIH-3251 Investigate dashboard config issues

---

build.gradle

Please review my changes, 
Bug fixed for running app in Windows machine.

OBGM-301 Exception Caused by: java.io.IOException: CreateProcess error=206, The filename or extension is too long

---

grails-app/views/purchaseOrder/_showOrderItems.gsp

Each time we use message as a string in java script we need to remamber to escape quotes.

OBPIH-3671 Fix french confirmation message on PO edit lines page

---

grails-app/services/org/pih/warehouse/core/LocationService.groovy

This method is a tad inefficient when you have many locations, since it needs to retrieve all the records from the database and hydrate them before filtering.
With the proposed changes the filtering is done on the database, which improves performance for this use case.
Anecdotal benchmark: On our instance with 150K locations it cut down the load time of the New Purchase Order page from 60+ seconds to 0.2 seconds.

Improve getLocationsSupportingActivity performance

---

grails-app/controllers/org/pih/warehouse/user/AuthController.groovy

This teeny-tiny PR prevents the user signup page from printing misleading warnings.

OBPIH-4144 Improve warning messages when user signup is disabled

---

package-lock.json

This PR updates the `fsevents` by a point release so that it compiles cleanly on recent Mac OS releases.

OBPIH-4145 Update dependencies to build on latest Mac OS

---

package-lock.json

While looking into the log4j issue, I ran a few scanners that pointed out other security vulnerabilities. This and a few others (forthcoming) were straightforward remedies. I don't think this needs to go out in the next release, so I've targeted develop. Let me know if I should aim it elsewhere. Thanks!

OBPIH-4217 Update lodash to fix a critical security vulnerability.

---

scripts/_Events.groovy
src/groovy/util/LiquibaseUtil.groovy

Oops! The previous PR removed a log that was in use, and kept one that was a no-op.
Testing: I checked that this change restores the liquibase changelog files via `jar tf`, and verified that the resultant warfile launches successfully with Tomcat 7 on my machine.

OBPIH-4218 Fix logging includes.

---

grails-app/conf/BuildConfig.groovy
grails-app/controllers/org/pih/warehouse/admin/AdminController.groovy
grails-app/controllers/org/pih/warehouse/core/ErrorsController.groovy
grails-app/migrations/install/baseline.sql
grails-app/services/org/pih/warehouse/core/MailService.groovy
grails-app/views/admin/sendMail.gsp
test/integration/org/pih/warehouse/core/MailServiceTests.groovy

I'm pretty sure the dev failures were caused by invalid email addresses in the test database. "Miss Administrator" and "Mister Manager" now have `openboxes@pih.org` as their email address.
While I was at it, I consolidated disparate implementations in MailService, removing 150-200 lines of code, fixed a broken test, and added tests for what happens if an SMTP server is down (no exception is thrown) (OBS-1053). I also updated the tools we use to send and test email.
GitHub is showing a sea of red ink which is making review difficult. I preserved fifteen(!?) existing function signatures, removing only one that took a map as input. (This one was used only in AdminController and ErrorsController and was easy to refactor.) The rest all route to a new function called `sendMailImpl()`. The …

OBPIH-4250 fix `from` email address on dev instance + OBS-1053 don't crash if smtp server is unavailable

---

grails-app/views/stocklist/_itemList.gsp

I couldn't reproduce [OBS-1089](https://pihemr.atlassian.net/browse/OBS-1089) on `develop`, but could on `master`; this one-line commit from @awalkowiak is the reason why. Any objection to a patch release to unblock a colleague on the pharmacy team?
argument in favor:
- this change has been soaking in develop since October
possible argument against:
- there may be other commits on develop that might need to come along for the ride
An alternative solution would be to target this patch to the specific template(s) affected by this bug. But I thought I'd go with the easiest fix first! :-)

OBS-1089 Fix stocklist PDF export

---

src/js/components/locations-configuration/AddBinModal.jsx
src/js/components/locations-configuration/AddZoneModal.jsx
src/js/components/locations-configuration/BinTable.jsx
src/js/components/locations-configuration/ZoneAndBinLocations.jsx
src/js/components/locations-configuration/ZoneTable.jsx
src/js/components/locations-configuration/ZoneTable.scss

Approved changes from QA which include:
- fixed error when adding for example 6th location and you have set 5 per page, the 6th location makes the react-table to create another page. I also improved/fixed it in reverse way - if you have one element on n-th page and you delete it, amount of pages is decremented and it automatically goes back to previous page.
- the scroll is disabled when Add Zone/Bin modal is opened (to avoid "flying select" problem)
- added INTERNAL for Bin Types.
- the Bin Type rows show the name of the Bin Type instead of locationTypeCode like before

OBDS-105 + 125: Zone and Bin: Bin Table + Bin Modal

---

src/js/components/stock-movement-wizard/outbound/EditPage.jsx

fixed reasonCode format on stockMovementItems fetch
stockMovementItems returned reasonCode: 'STOCK_OUT'
when expected was reasonCode: { id: 'STOCK_OUT', name: 'Stock out', value: 'STOCK_OUT'}

OBPIH-4336 - reason code issue

---

grails-app/controllers/org/pih/warehouse/order/OrderController.groovy

This column has been wrong in two different ways over time.
Before my CSV fixes, the header was "vendor code", the value was `productSupplier?.supplierCode` - header/value mismatch
When I patched CSV, the header was "vendor code", the value was `product?.vendorCode` - header/value agreed, but wasn't what was desired
Now it's "supplier code" with a value of `productSupplier?.supplierCode` - header/value agree, and the field is what's desired (I think)

OBPIH-4377 Use supplier code, not vendor code, when downloading order as CSV.

---

grails-app/i18n/messages.properties
src/css/main.scss
src/js/components/form-elements/FieldArrayComponent.jsx
src/js/components/stock-movement-wizard/request/AddItemsPage.jsx

I spent a long time trying to figure out how to make the red asterisk for header - the same asterisk which is visible for "regular" fields with required: true. It was supposedly made and was used in many components (talking about fields, which have another nestled fields inside (ArrayField)), but it did not really work with current version, so even though it was used in many places, the asterisk didn't work.
With my changes, the red asterisk for headers are now "generic", which means they can be used anywhere (and will now finally work in places, where it was previously declared (e.g. stock-movement/combined-shipments/AddItemsPage.jsx) and many others, so I hope my changes will also improve other wizards.

OBAM-335 UI updates to ward pull/adhoc request

---

grails-app/controllers/org/pih/warehouse/core/DocumentController.groovy
grails-app/controllers/org/pih/warehouse/shipping/ShipmentController.groovy
grails-app/services/org/pih/warehouse/core/DocumentTemplateService.groovy
grails-app/services/org/pih/warehouse/inventory/StockMovementService.groovy
grails-app/services/org/pih/warehouse/requisition/RequisitionService.groovy
grails-app/views/shipment/showDetails.gsp
src/groovy/org/pih/warehouse/api/DocumentGroupCode.groovy

and OBAM-358 Add variables for custom document template

OBAM-357 Allow multiple invoice templates on single shipment workflow

---

src/js/components/stock-movement-wizard/combined-shipments/SendMovementPage.jsx
src/js/components/stock-movement-wizard/inbound/SendMovementPage.jsx
src/js/components/stock-movement-wizard/outbound/SendMovementPage.jsx

The problem there was not actually a fault of mine while dealing with the task, but with the validation - as a default, the `shipmentType` as a value being sent to validation was simply a string "5".
When changing to any other option, the `shipmentType` becomes an object (which is good) with id, name etc.
Why did the validation work if you tried to send shipment without changing the shipment type?
In this line:  
```
else if (values.shipmentType.id === _.find(this.state.shipmentTypes, shipmentType => shipmentType.label === 'Default').value)
```
it was unexpectedly true, because:
1. `values.shipmentType.id` is `undefined` (because values.shipmentType is a string "5", not an object)
2. `shipmentTypes` fetched from api don't have property `.value` so it was also `undefined`, so `undefined` …

OBPIH-4404 Improvements after QA

---

grails-app/controllers/org/pih/warehouse/order/OrderController.groovy
grails-app/i18n/messages.properties
grails-app/views/order/_filters.gsp
web-app/css/openboxes.css

I was struggling with finding a way how to propely round the `order.total `and `order.totalNormalized` so it looks in the .csv as in the table of list orders - I hope that rounding it to 2 decimal places as in the table was a good approach. 
I was also thinking whether I should download all orders (obviously with applied filter, but what I mean is that if there are 4 pages, the 4 pages are downloaded at one time) or only those visible at the moment (10 rows) in the table should be downloaded, but I kept the approach of already done report which is "Download order line details" where all rows are downloaded.

OBPIH-3776 Add download orders option

---

grails-app/services/org/pih/warehouse/forecasting/ForecastingService.groovy

It seemed to be a pretty easy fix, but at first I made changes to `def monthlyDemand` like this:
```
def monthlyDemand = new BigDecimal(totalDemand / Math.floor((demandPeriod / 30))).setScale(0, RoundingMode.HALF_UP)
```
and in the return in **monthlyDemand** section I just wrote: **monthlyDemand: monthlyDemand**, but in turned out that it worked well in reports, but the stock card's "On hand months" calculation was destroyed with that version, so what made it not destroying the `"On hand months"` was to copy what is in the `def monthlyDemand` inside return directly. Don't know what the reason is, because anyway it should return the same (we just don't call the method from above, but assign the value directly).
I attach two screenshots to show the difference in `"On hand months"` that I …

OBPIH-4477 Data not in the right columns in reorder report

---

grails-app/controllers/org/pih/warehouse/api/LocationApiController.groovy
grails-app/services/org/pih/warehouse/core/LocationService.groovy
src/groovy/org/pih/warehouse/core/RoleType.groovy

There are a lot of combinations of user/location permissions both user default permissions and location-based. I tested a bunch of them and it seemed to be working fine - if a user doesn't have any default permissions and doesn't have any location-based permissions, none locations are visible and if a user doesn't have any default permissions which were pointed out in the ticket, but has that permission in any location - that location is visible.
Worth pointing out is the fact that I had to be switching between develop branch and release branch to be able to edit a user, because while trying to edit the user on release branch I was getting an ugly error: 
```
"Exception Message: No enum constant org.pih.warehouse.core.RoleType.ROLE_PRODUCT_MANAGER "
```
It is probably due to the fact, …

OBPIH-4451 Issue with user permissions in location chooser

---

grails-app/controllers/org/pih/warehouse/order/OrderController.groovy
grails-app/domain/org/pih/warehouse/order/OrderItemDetails.groovy
grails-app/domain/org/pih/warehouse/order/OrderItemSummary.groovy
grails-app/migrations/views/changelog.xml
grails-app/migrations/views/order-item-details.sql
grails-app/migrations/views/order-summary-view.sql
grails-app/services/org/pih/warehouse/order/OrderService.groovy
grails-app/views/order/_orderItemSummaryFilters.gsp
grails-app/views/order/orderItemSummaryList.gsp

I added two views. First one order_item_summary "extended" with more JOINs, based on the already existing views related to the Order derived status (inside the order-summary-view.sql). The other one order_item_details is a bit simplified. There is option to check tables with results from both views on the '(...)/openboxes/order/orderItemSummaryList' and on the '(...)/openboxes/order/orderItemDetailsList'. The key difference between those two is that we won't be able do an extensive filtering on the simplified one, where on the list from the order_item_summary view we can basically filter on every field we have there. After performance testing/comparison we can decide which option we want to be there and the other one will be removed.

OBPIH-4461 Add view for OrderItem derived status

---

grails-app/views/order/_itemDetails.gsp
grails-app/views/order/_itemStatus.gsp
grails-app/views/order/_orderSummary.gsp
grails-app/views/order/show.gsp

After many different approaches, the dynamic filtering (hiding a row) worked the best here. I managed to recreate what was done probably in Stock History section. At the moment the filtering is done by product name which Kelsey admitted on one of the previous standups. The changes may seem weird (it might look like I changed the whole file) on Git, due to indents because of one additional <div> for everything, but the part I edited was just adding the <script> section and one if at the beginning of the first div.
The "if" was added to determine whether it is a putaway order or a PO order, because I assume it was not supposed to be done for putaways and as there is one view for both cases, it would work also for putaways if I hadn't added the "if".

OBPIH-4440 Add item search to PO view page

---

grails-app/domain/org/pih/warehouse/core/User.groovy
grails-app/taglib/org/pih/warehouse/AuthTagLib.groovy
grails-app/views/taglib/_displayLogo.gsp
src/js/components/stock-movement-wizard/request/EditPage.jsx

It also reverts the "OBS-1176 GrailsTagException: Error executing tag <g:render>"

OBPIH-4584 Fix reason code for revising items on the outbound request

---

grails-app/services/org/pih/warehouse/core/FileService.groovy

To test this one you have to e.g. get the template from the Documents at obdev and upload it locally, because if you have an older db data like me, the variable `${COMMERCIAL_INVOICE}` does not exist in the template and that's why I couldn't test this one before.

OBPIH-4470 Add Columns for Manufacturer and Origin to commercial invoice

---

package-lock.json
package.json
scripts/_Events.groovy

This, very trivial, PR updates `webpack-cli` so we can set `--no-color` when running webpack on bamboo (Some of bamboo's log views do not support fancy ascii escapes, and webpack's terminal output is hard to read there).

OBPIH-4331 Avoid fancy terminal escapes when running webpack.

---

grails-app/conf/Config.groovy
grails-app/conf/UrlMappings.groovy
grails-app/controllers/org/pih/warehouse/api/DashboardApiController.groovy
grails-app/services/org/pih/warehouse/core/UserService.groovy
package.json
src/js/actions/index.js
src/js/components/dashboard/Dashboard.jsx
src/js/components/dashboard/UnarchiveIndicators.jsx

OBPIH-4277 Add option to make separate dashboard pages

---

grails-app/conf/Config.groovy
grails-app/conf/RoleFilters.groovy
grails-app/views/order/_actions.gsp

The main problem to fix was that the `Delete order` button was visible only for superusers and that I had to figure out how to prevent `<g:link>` of disabling the button after making is visible not only for superusers.
Deleting now works for role at least Assistant, so for roles: Superuser, Admin, Manager, Assistant.

OBPIH-4001 Make admin, manager, assistant be able to delete pending POs

---

grails-app/conf/Config.groovy
grails-app/conf/RoleFilters.groovy
grails-app/conf/UrlMappings.groovy
grails-app/controllers/org/pih/warehouse/inventory/StockMovementController.groovy
grails-app/taglib/LinkTagLib.groovy
grails-app/views/stockMovement/_actions.gsp
grails-app/views/stockMovement/show.gsp
src/groovy/org/pih/warehouse/api/StockMovement.groovy
src/groovy/util/ConfigHelper.groovy
test/unit/org/pih/warehouse/utils/ConfigHelperTests.groovy

What needs to be discussed and I am not sure how to do it is how to distinguish outbound sm (Create outbound movement) from stock request (Create Stock Request) on the backend side, because it uses the same `def remove` and in the rules for now I followed what was supposed to be done for regular shipments so:
```
[controller: 'stockMovement', actions: ['remove'], accessRules: [ minimumRequiredRole: RoleType.ROLE_ASSISTANT ]]
```
but the problem is that we don't want to change the behavior in requests, so it should still remain `> Admin`.
I've hidden **Delete** button on the frontend side checking if `requsition.sourceType == ELECTRONIC:`
```
stockMovement?.requisition?.sourceType == RequisitionSourceType.ELECTRONIC
```
, so if you are not `> Admin` you won't be able to see the button to …

OBPIH-3983 Manager cannot delete a pending shipment

---

grails-app/conf/Config.groovy
grails-app/conf/RoleFilters.groovy
grails-app/views/order/_orderDocuments.gsp

Making admins be able to delete documents from PO

OBPIH-4002 Admins cannot delete documents

---

build.gradle
gradle.properties
grails-app/conf/application.yml
grails-app/utils/org/pih/warehouse/PasswordCodec.groovy
grails-app/views/purchaseOrder/_showOrderItems.gsp

This PR builds on OBGM-340's warfile fix to make unit and integration tests at least not crash. The main parts of it are (a) making sure that all jars from a product family are the same version and (b) enabling `failOnVersionConflict()` which is handy for detecting when two dependencies request different versions of the same underlying library. There are a dozen or so security patches in here as well, and I added a brief comment to each dependency explaining what it was used for. Hopefully that's helpful to future versions of ourselves.
@awalkowiak Java-dependency-wise this should be a pretty good baseline for the foreseeable future for Grails 3; you can merge it into the base branch at your leisure.
`grails run-app` - works
`grails war` - works
`grails test-app` - doesn't crash
`grails …

OBGM-342 Fight our way out of dependency hell, with comments

---

grails-app/controllers/org/pih/warehouse/api/CombinedShipmentItemApiController.groovy
grails-app/services/org/pih/warehouse/order/OrderService.groovy

It wasn't specified in the ticket, but discussed with Katarzyna, that orders which are not at least `PLACED` (e.g. `PENDING`) should not be visible in dropdown (you should not be able to ship any item of such an order). That's why `createCriteria` was also changed by me.

OBPIH-4677 Fix orders and items visible in PO shipment dropdown

---

package-lock.json
package.json
webpack.config.js

On my machine, this reduces webpack build times from ~40 sec. to ~10 sec. Maybe it'll be useful to other devs as well. It adds up!
It doesn't do anything different for a clean build -- the cache is tucked away in node_modules

OBPIH-4557 Cache intermediate results to speed webpack rebuilds by ~75%.

---

grails-app/controllers/org/pih/warehouse/product/ProductAttributeValueController.groovy
grails-app/services/org/pih/warehouse/core/DocumentService.groovy

DocumentService.generateExcel() closes the response provided to it, but 3 out of 4 callers attempt to flush the response after it returns, which won’t work. For clarity, I removed the close() call from generateExcel() and added a flush() call to the 1 caller that didn't already do so. Resolves OBENBOXES-OBNAV-Q25.

OBPIH-4766 Don't implicitly close response when generating Excel files.

---

src/css/main.scss
src/js/components/Layout/HeaderStyles.scss
src/js/components/Layout/NavbarIcons.jsx
src/js/components/location/LocationChooser/LocationChooserModal/LocationButton.jsx
src/js/components/location/LocationChooser/LocationChooserModal/LocationChooserModal.jsx
src/js/components/location/LocationChooser/LocationChooserModal/LocationChooserModal.scss

- fix long location name text overlay
- fix some padding/margin styling
- added ability to close modal on click outside

OBPIH-4705 Fix Location chooser button

---

src/js/components/Layout/HeaderStyles.scss
src/js/components/dashboard/Dashboard.scss

I also realized and fixed on the fly that on resolutions below 1440 menu items inside dropdowns had wrong padding on the left and right side (it was changed from 16 to 8, but it should only change for the main buttons, so for sections: Dashboard, Inventory etc, but not items (`<a>`) inside dropdown).
As for reporting section columns it was decided between Katarzyna and me that we would keep it as it is for now, as the fix would not be that straight forward.

OBPIH-4704 Fix dashboard moving when switching sections

---

grails-app/views/common/_menuicons.gsp
grails-app/views/dashboard/megamenu.gsp

The problem was that `<div>` was opened before `<g:isUserAdmin>` but closed inside `<g:isUserAdmin>` which caused that if a user was not >= admin, the `<div>` was opened but never closed.
I also found on the fly in megamenu `</a>` which was not according to anything so I removed it.

OBPIH-4707 Fix collapsing menu on GSP for < Admin users

---

src/js/components/form-elements/DateFilter/DateFilter.jsx
src/js/components/form-elements/DateFilter/DateFilter.scss
src/js/components/form-elements/DateFilter/index.jsx

- restyle date picker popup
- restyle data picker input
- create a separate DateFilter component

OBPIH-4734 Restyle date-picker

---

grails-app/conf/Config.groovy
grails-app/controllers/org/pih/warehouse/api/StockMovementApiController.groovy
grails-app/domain/org/pih/warehouse/inventory/OutboundStockMovementListItem.groovy
grails-app/services/org/pih/warehouse/inventory/StockMovementService.groovy

- plus fix filtering by dateCreated for inbounds
- plus fix OutboundStockMovementListItem toJson mapper

OBPIH-4751 Fix deleting Stock Movements endpoint

---

grails-app/controllers/org/pih/warehouse/product/ProductController.groovy
grails-app/domain/org/pih/warehouse/product/Product.groovy
grails-app/services/org/pih/warehouse/core/DocumentService.groovy
grails-app/views/inventory/_browseProduct.gsp
grails-app/views/inventory/browse.gsp
grails-app/views/mobile/productDetails.gsp
grails-app/views/mobile/productList.gsp
grails-app/views/product/_documents.gsp
grails-app/views/product/_summary.gsp
grails-app/views/product/_summaryDialog.gsp
grails-app/views/requisition/printDraft.gsp

This PR primarily removes a deprecated grails plugin by refactoring `scaleImage()`. It also correctly renders thumbnails on HiDPI screens, reduces inefficiencies when sending images to `nailthumb`, and makes `Product.getThumbnail()` work deterministically.

OBGM-325 Remove image-builder plugin and simplify thumbnail code.

---

grails-app/domain/org/pih/warehouse/inventory/OutboundStockMovementListItem.groovy
src/js/components/stock-movement-wizard/request/AddItemsPage.jsx
web-app/css/openboxes.css

After upgrading `bootstrap` version - elements with class `.fade` additionally have `opacity: 0` applied to them.
The reason for that is that new version of bootstrap has additional styling for class `.fade` where:
```
.fade:not(.show) {
opacity: 0;
}
```
so instead of adding in every instance where we use class `.fade` additional class `.show` I just overwritten the styling for `.fade:not(.show)`

OBPIH-4872 Fix fade class opacity styling bug

---

grails-app/controllers/org/pih/warehouse/api/StockMovementApiController.groovy
grails-app/domain/org/pih/warehouse/requisition/RequisitionItem.groovy
grails-app/services/org/pih/warehouse/inventory/StockMovementService.groovy

Hi @jmiranda, I was able to reproduce OBS-1269 by moving back and forth a few times between Edit, Pick and Ship and editing the quantity field _without_ ever clicking the big red Undo button. More details are on the ticket.
The one-line summary of this change is that it basically presses the undo button for you if you don't press it yourself before editing the quantity.
In more detail, `reviseItems()`, as written, has guards around `removeShipmentAndPicklistItemsForModifiedRequisitionItem()` and `RequisitionItem::undoChanges()` which strikes me as both unnecessary and, at least in the case described in OBS-1269, incorrect. (Contrast the `revertItem()` implementation which calls them indiscriminately.)
In fact, nowhere else in this file do I see guards around either of these methods, while …

OBS-1269 Remove dangling references when calling StockMovementService.reviseItems()

---

grails-app/views/layouts/custom.gsp
web-app/css/openboxes.css

It turned out after long research that I had to add additional package of styles for datatable I found for bootstrap 4. Weird part is that anyway I have to keep old styles as well and on Mozilla it works well without any change.
As the styles provided (or rather make our custom styles working) also additional padding in one place, I had to remove this padding in styles.

OBPIH-4875 Data do not fit to columns in reports

---

grails-app/views/inventory/_inventoryAdjustment.gsp

It was just that without the newer bootstrap the "row" property didn't actually change anything, but in newer version it's flex's property which made it broken.

OBPIH-4884 Adjust stock page broken

---

grails-app/controllers/org/pih/warehouse/order/OrderController.groovy
grails-app/views/order/_actions.gsp
grails-app/views/order/_filters.gsp
grails-app/views/order/_summary.gsp
grails-app/views/order/list.gsp

- hide order list link button on show putaway show page
- fix redirect after delete pending putaway
- disable product type filter on putaway list

OBPIH-4924 fix putaway list redirects

---

src/js/components/Filter/FilterForm.jsx
src/js/components/invoice/InvoiceListFilters.jsx
src/js/components/location/LocationChooser/index.jsx
src/js/components/products/ProductsList.jsx
src/js/components/purchaseOrder/PurchaseOrderList.jsx
src/js/components/purchaseOrder/PurchaseOrderListFilters.jsx
src/js/components/stock-list/StockList.jsx
src/js/components/stock-movement/inbound/StockMovementInboundList.jsx
src/js/components/stock-movement/outbound/StockMovementOutboundList.jsx
src/js/components/stock-transfer/list/StockTransferList.jsx
src/js/reducers/sessionReducer.jsx

Fixed:
- `Clear` filter button doesn't remove default, disabled values on PO and Invoice list anymore
- Filters get cleared after changing the location, but not after refreshing the page
- fix bug on PO list when switching between location with central purchasing enabled and not enabled one
- added re-fetch on stock transfer list when changing location

OBPIH-4914 Combined fixes of issues on list pages

---

src/groovy/org/pih/warehouse/api/PartialReceiptItem.groovy

@jmiranda this line was throwing `collection [...] not processed by flush()` after doing `shipmentItem.addToReceiptItems(receiptItem)` when there was a multi-line cancel case.

OBPIH-5004 Fix saving and canceling multiple receipt items

---

grails-app/conf/Config.groovy

When fixing the GSP menu some days ago, I forgot to bring back two deprecated sections to `enabled = false` by default, which caused that on GSP pages those were seen by default. On React they were not visible, because they are taken from inside inbound/outbound section where their menuItems are `enabled = false`, but on GSP the menuItems are hardcoded, and it was only checking `if (megamenuConfig.shipping.enabled)`.
On obnavstage it was also not visible, because the menu is overwritten here, so it's just my fault here, that I haven't spotted this when pushing previous ticket even though I thought, everything was fine.

Fix menu on GSP not to show deprecated sections by default

---

grails-app/conf/Config.groovy
grails-app/views/order/_filters.gsp

I had to revert back delete of (surprisingly used though) menu sections. 'If' statements using those sections are nested deep into e.g. `if (megamenuConfig.inbound.enabled)`, that's why I haven't realized that at first sight. The result was that Inbound and Outbound menu were there, but there was nothing inside them after removing those stockMovement, putaways sections from config. Now I made sure a few times section by section that everything works propely on default settings.

OBPIH-5047 Keep orderType when clicking Cancel on putaway list

---

grails-app/services/org/pih/warehouse/inventory/InventorySnapshotService.groovy
grails-app/services/org/pih/warehouse/inventory/ProductAvailabilityService.groovy

As part of restoring test coverage, I added guards to
- ProductAvailabilityService.updateProductAvailability()
- InventorySnapshotService.updateInventorySnapshots()
to prevent them from firing on objects that had no ID.
However, the change also made it impossible for these
methods to clear Product.productCode, which is an
optional field. I'm not sure if this change is causing
the performance problems, but I believe it is a bug.

OBS-1253 Fix regression in updateProductAvailability and updateInventorySnapshots

---

grails-app/conf/Config.groovy

Confirmed with Katarzyna, that delete should be still only for >= Assistants

OBPIH-5163 Users with Browser permissions can't see the PO list page

---

src/js/components/Layout/NavbarIcons.jsx
src/js/components/Layout/menu/Menu.jsx

filter out configuration megamenu based on section id instead of label
The bug ocurred when switching languages which is logical because previously we were filtering out **configuration** section based on label by doing  `if (section.label === 'Configuration)` which would result in `false` in all of the cases where configuration has a different translation label than _Configuration_.

OBPIH-5174 Fix filtering out configuration section from megamenu on react

---

build.gradle
grails-app/controllers/org/pih/warehouse/NewRelicInterceptor.groovy
grails-app/views/layouts/bootstrap.gsp
grails-app/views/layouts/custom.gsp
grails-app/views/layouts/main.gsp
grails-app/views/layouts/mobile.gsp

This PR sends a lot of telemetry to New Relic, including
- [crash reports](https://onenr.io/0EjOgdylAj6),
- [logs](https://onenr.io/08jqn1Ny1Ql),
- [timing by url](https://onenr.io/0VjYneP0EQ0),
- [JVM CPU/memory use](https://onenr.io/0MR2G3Z9JjY),
- [database usage](https://onenr.io/0OQMnZNWvwG),
- [host process stats](https://onenr.io/0dQe6BNpowe), and
- (finally!) [disk consumption and usage](https://onenr.io/0qwyeaNpdwn).
It also supports [New Relic's thread profiler](https://onenr.io/0VRV6OzqMRa)
This is presently running on obnavtest1. Note, for all this stuff to work, I needed to wire it to a different New Relic account than what we use for obnav, obnavstage and obdev.
It should not be difficult to back-port this to Grails 1. Maybe on obnavtest2? If we like the results then we can …

OBGM-362 Configure New Relic

---

build.gradle

Hi Justin,
This change makes Openboxes war files run as standalone jars (like how `openboxes-devops/arm-template/scripts/ob-vm-setup.sh` expects). If you set `ORG_GRADLE_PROJECT_WEB_SERVER=tomcat` in the environment, we skip libraries that Tomcat provides.

OBGM-381 Make standalone war files by default; optionally target Tomcat

---

build.gradle

Oops, this should have gone in the previous PR

OBGM-381.2 Make tomcat-jdbc a compile-time dependency for standalone war files

---

.github/workflows/integration-tests.yml
.github/workflows/unit-tests.yml

This PR updates my previous OBS-1342 patch to never talk to sdkman at all, but instead download grails directly from GitHub.

OBS-1342.2 Do not call sdkman from GitHub Actions.

---

package-lock.json

This PR fixes a security vulnerability in a sub-sub-(sub-)dependency that dependabot has been whining about for a while.

OBPIH-5197 Bump loader-utils to 1.4.2.

---

grails-app/services/org/pih/warehouse/inventory/InventoryService.groovy
grails-app/services/org/pih/warehouse/product/ProductMergeService.groovy

This fixes issue, when few inventories had transactions (PRODUCT_INVENTORY or INVENTORY) with the same product, which led to moving stock between two inventories while merging products.

OBPIH-5237 Properly move stock within multiple inventories

---

grails-app/conf/InitializationFilters.groovy
grails-app/i18n/messages.properties
grails-app/taglib/org/pih/warehouse/MessageTagLib.groovy

…olving the big spike), fix menu (translations) fetching when switching locales
After a long and exhausting round of investigation I have a very interesting summary of known for the long time issue with `<g:message>` tags not being translatable by the crowdin vs `<warehouse:message>` being translatable.
After we lost this "workaround" I found for translating `<g:message>` tags when merging the changes to transition in/out to/from localization mode, we again faced an issue with `<g:message>` not being translatable by crowdin anywhere (because the “workaround” which we did not really know what it is about, we thought it’s just a random thing was lost). It was a big regression “issue”, because since we had a workaround to translate those and suddenly lost that workaround, it would mean that …

OBPIH-5161 Set locale for every request

---

src/js/components/returns/inbound/AddItemsPage.jsx
src/js/components/stock-movement-wizard/inbound/AddItemsPage.jsx
src/js/components/stock-movement-wizard/outbound/AddItemsPage.jsx

After discussing it with @drodzewicz and the reasons why it was changed to `button` in one of the latest PRs by him we couldn't reproduce the issue he had before when the type was `submit`, probably this:
```
event.stopPropagation();
```
fixed the issue Dariusz had with the enter case, so we could just simply bring back `type="submit"` here

OBPIH-5301 Fix validation for lot and exp date on inbound add items step

---

grails-app/i18n/messages.properties
src/js/components/dashboard/Dashboard.jsx
src/js/components/dashboard/GraphCard.jsx
src/js/components/dashboard/NumberCard.jsx
src/js/components/dashboard/UnarchiveIndicators.jsx

- Add missing translations for Dashboards sidebar items
- Add missing translation For labels on Archive indicators, save config etc.
- Fix truncated label causing crowding not to translate it properly
- Modify indicator filter component option label rendering to instead accept arguments in the label for more control on the order of words

OBPIH-5207 Fix crowdin translations on Dashboard

---

grails-app/controllers/org/pih/warehouse/api/LocationApiController.groovy
grails-app/services/org/pih/warehouse/data/LocationDataService.groovy
src/groovy/org/pih/warehouse/inventory/RefreshProductAvailabilityEvent.groovy

plus fixed deleting bin location with zone
plus fixed finding location type by name during import

OBPIH-5329 Improve performance after deleting location

---

grails-app/domain/org/pih/warehouse/inventory/OutboundStockMovement.groovy

The line I added is `231`. The problem was twice fixed - once by me a long time ago: [PR](https://github.com/openboxes/openboxes/pull/3537) and then half of it was cherry-picked by Dariusz for some other hotfix: [PR](https://github.com/openboxes/openboxes/pull/3630).
Why it was working on the hotfix branch and it is not working here, is that on the `release/0.8.19-hotfix2` version of the `def delete` for the `StockMovementApiController` was not the version that @awalkowiak has refactored (28 of September) and that is currently both on develop and `release/0.8.21`, but it was like that:
```
def delete = {
stockMovementService.deleteStockMovement(params.id)
render status: 204
}
```
So we were using `stockMovementService` for all cases and we were calling the `StockMovement` class for …

OBPIH-5344 Fix deleting stock requests from React side

---

grails-app/controllers/org/pih/warehouse/JsonController.groovy
grails-app/domain/org/pih/warehouse/product/Product.groovy
grails-app/views/product/_summary.gsp
grails-app/views/taglib/_globalSearch.gsp
src/js/components/GlobalSearch/GlobalSearch.jsx
src/js/utils/option-utils.jsx

Added:
- separate getter for translated product name - I think it's a better approach instead of overriding the `name` getter, so that we have better control of that, especially that we don't cover the translations for all places at once
- if a synonym for user's current locale exists, we want to display it and have a tooltip with the original name of the product. If the synonym doesn't exist, we don't need to have the tooltip
- for now implemented only for stock card header and the global search, so that I do not block other tickets. The rest of cases for stock card (all the tabs and modals) will be covered in a separate, already existing ticket
What we might consider thinking about in the future (consulted with Manon) is that what to do if someone creates a product with e.g. Spanish …

OBPIH-5315 Display product name translation on stock card header and in the global search

---

grails-app/jobs/org/pih/warehouse/jobs/AssignIdentifierJob.groovy
grails-app/jobs/org/pih/warehouse/jobs/CalculateHistoricalQuantityJob.groovy
grails-app/jobs/org/pih/warehouse/jobs/DataCleaningJob.groovy
grails-app/jobs/org/pih/warehouse/jobs/DataMigrationJob.groovy
grails-app/jobs/org/pih/warehouse/jobs/JobUtils.groovy
grails-app/jobs/org/pih/warehouse/jobs/RefreshDemandDataJob.groovy
grails-app/jobs/org/pih/warehouse/jobs/RefreshInventorySnapshotJob.groovy
grails-app/jobs/org/pih/warehouse/jobs/RefreshProductAvailabilityJob.groovy
grails-app/jobs/org/pih/warehouse/jobs/RefreshStockoutDataJob.groovy
grails-app/jobs/org/pih/warehouse/jobs/RefreshTransactionFactJob.groovy
grails-app/jobs/org/pih/warehouse/jobs/SendStockAlertsJob.groovy
grails-app/jobs/org/pih/warehouse/jobs/UpdateExchangeRatesJob.groovy

This one is from the icebox, but since I was dinking around with Quartz config last week I figured I'd bring it back to life for a tech huddle.
- some Quartz jobs have a `@DisallowConcurrentExecution` annotation;
- some declare `def concurrent = false`;
- some check whether a migration is happening before running;
- each one of the above is not done by at least one job :-( .
This PR makes all Quartz jobs perform all 3 checks and consolidates common code in a new JobsUtil class. (I also added comments to ease Grails 1/3 rebases going forward.)
I'm not sure whether the 0.8.19 deploy was actually affected by this; the migrations there took longer than they have on any other push so the window for error was wider -- but I think these bugs should be fixed even if they haven't bitten us in the …

OBS-1253 Don't run Quartz jobs during DB migrations; consistently disable concurrent job execution

---

grails-app/jobs/org/pih/warehouse/jobs/SendStockAlertsJob.groovy
grails-app/services/org/pih/warehouse/data/MigrationService.groovy
grails-app/services/org/pih/warehouse/inventory/InventoryService.groovy
grails-app/services/org/pih/warehouse/inventory/InventorySnapshotService.groovy
grails-app/services/org/pih/warehouse/inventory/ProductAvailabilityService.groovy
grails-app/services/org/pih/warehouse/jobs/GparsService.groovy

This PR, along with #3809 and #3810, splits #3785 into more focused chunks. #3809 and #3810 make changes to dependencies and config. This PR fixes some logging issues:
- Replace `GParsPool.withPool()` with `gparsService.withPool('informative name')`
- GPars workers now log their parent pool to indicate who brought them into being, and how many siblings they have
- uncaught exceptions get properly logged instead of `println`'ed, which means Sentry and New Relic can see them

OBS-1373 Improve GPars logging and exception handling.

---

grails-app/conf/BuildConfig.groovy

This PR makes sure there is one and only one implementation of `com.lowagie.*` in the class path. No guarantees it'll fix the recurring Cp1252 warnings, but it _will_ make it easier to follow the stack traces. At present it's not clear whether the issue is coming from `itext` or `openpdf`. (I suspect the former)

OBPIH-5268 Completely remove itext and core-renderer from build process.

---

grails-app/controllers/org/pih/warehouse/product/ProductController.groovy
grails-app/domain/org/pih/warehouse/core/Synonym.groovy
grails-app/i18n/messages.properties
grails-app/services/org/pih/warehouse/data/ProductSynonymDataService.groovy
grails-app/services/org/pih/warehouse/product/ProductService.groovy
grails-app/views/inventoryLevel/_form.gsp
grails-app/views/product/_productSynonyms.gsp
src/groovy/org/pih/warehouse/importer/ProductSynonymExcelImporter.groovy
test/integration/org/pih/warehouse/product/ProductIntegrationTests.groovy
test/unit/org/pih/warehouse/core/SynonymTests.groovy

I tried to make it as generic as I could, so that the methods I created, e.g. `getSynonymsOfTypeAndLocale` or `validateMultipleSynonymsOfType` are "ready" to be used in the future if we for example add some new synonym type codes that would have to be unique.
What is done:
- validation not to allow multiple synonyms of type `DISPLAY_NAME` per locale (included both - adding manually and through import)
- preventing from clearing the form values if an error occurs (so that the user can correct him/herself without having to re-write everything again)
- I also added a potential fix for another `NullPointerException` that Katarzyna has discovered today at inventory level dialog (probably the source is the same as yesterday - I found only one potential place in the dialog file which could cause …

OBPIH-5367 Add validation to prevent multiple display names per locale

---

grails-app/controllers/org/pih/warehouse/api/StockTransferApiController.groovy
grails-app/services/org/pih/warehouse/stockTransfer/StockTransferService.groovy

The problem was that this is `POST` method and we pass the params as request body, but were trying to access it through `params`. 
I know that `parseRequest` in `UrlMappings` is supposed to do the job, to parse the request body to be accessible through the `params`, but from what I've read, the `parseRequest` has not been supported since Grails 2.3.
The fix for that was to change the access from `params.locationId` to `request.JSON.locationId`, but what I'd like to bring up there is that we should be aware, that many places might face the same problem, since we used to use `parseRequest` in many endpoints, so we might want to come up with some solution not to have to change it from `params` to `request.JSON` in every place that will be found.
One of the solutions could be to create a …

OBGM-401 Unable to display items in outbound return workflow

---

grails-app/controllers/org/pih/warehouse/order/PurchaseOrderController.groovy
grails-app/domain/org/pih/warehouse/order/Order.groovy
grails-app/views/purchaseOrder/_showOrderItems.gsp

There were a few things, because fixing one of the errors, I got to another one :D 
Generally the error I was getting was different than the error in the ticket - I was getting an error that 
```
groovy.lang.MissingMethodException
No signature of method: org.pih.warehouse.order.Order.publishEvent() is applicable for argument types: 
```
and this is because in Grails 1.3.9 we have access to event publisher "globally" - that means it is injected automatically for each bean, but in Grails 3 we have to inject it ourselves with `@Autowired` annotation.
Then I was getting an error, that `addItems` method is not recognized - this was because in Grails 3 the methods in the redirects have to be as string.
And then finally the error was that `unexpected token ||` - it's weird, because we have the …

OBGM-396 Unable to create PO

---

src/js/components/product-select/ProductSelect.jsx
src/js/components/stock-movement-wizard/combined-shipments/AddItemsPage.jsx
src/js/utils/Select.jsx
src/js/utils/option-utils.jsx

I added a props `forceTooltip`, because if i just set `showValueTooltip=true` the tooltip doesn't work. When i changed the condition in `isTooltipDisabled()` then i found some places when two tooltips were displayed (because of using Tooltip inside `FIELDS`)

OBPIH-5148 Can't see full item description on add items to PO shipment page

---

grails-app/conf/Config.groovy
grails-app/controllers/org/pih/warehouse/api/ApiController.groovy
src/css/main.scss
src/js/components/Layout/notifications/notification.jsx
src/js/components/Layout/notifications/notification.md
src/js/components/Router.jsx
src/js/components/dashboard/CustomAlert.jsx
src/js/consts/notificationTypes.js
src/js/reducers/sessionReducer.jsx
src/js/utils/apiClient.jsx

I tried to make it as much configurable as I could - the usage is pretty simple and described in the `notification.md` file.
I made `notification()` as **curried** function, so it takes as an argument `type` of the notification from enum `NotificationType` and then returns a function which expects arguments: `message` (required), `details` (the description of the error, optional), `startIcon` (optional, each type of the notification has its default `startIcon`).
I also tried to cause as little regression as I could, so I also took care of already existing notifications (which are called by `Alert.success(...)` directly), and managed to make them look as close as to the new design:
Manon has said it looked good, and said, that we would have in the future some tickets to change the existing …

OBPIH-5355 Restyling components for notifications

---

grails-app/controllers/org/pih/warehouse/product/ProductController.groovy
grails-app/i18n/messages.properties
grails-app/services/org/pih/warehouse/product/ProductMergeService.groovy
grails-app/services/org/pih/warehouse/requisition/RequisitionService.groovy

and do not allow to make a merge before finishing the pending stock movements

OBPIH-5237 Validate if merged products have pending stock movements

---

src/js/components/stock-movement-wizard/outbound/AddItemsPage.jsx

Forever loading lines after clicking 'Add line' and unable to click next button when focus is on input field were caused by onClick function. There is no option to trigger onClick when focus is on another element and onBlur from the second element takes longer time.
I solved issues connected with running the same transaction twice setting variable actionInProgress (it couldn't be in state, because setting state is asynchronous operation and there is a possibility to run autosave and save from the button at the same time).

OBPIH-5323 Save line by line in outbound add items step (fixes after QA)

---

grails-app/controllers/org/pih/warehouse/picklist/PicklistController.groovy
grails-app/controllers/org/pih/warehouse/putaway/PutAwayController.groovy
grails-app/services/org/pih/warehouse/core/DocumentTemplateService.groovy
grails-app/utils/org/pih/warehouse/util/DesCodec.groovy
grails-app/utils/org/pih/warehouse/util/PDFUtil.groovy
grails-app/utils/org/pih/warehouse/util/PdfUtil.groovy
grails-app/views/error.gsp
grails-app/views/unsupported.gsp
web-app/css/custom.css
web-app/css/openboxes.css
web-app/css/print.css

XDocReport can clobber a global used by Grails' rendering plugin. Talk about spooky action at a distance. This PR checks that global after each call to XDocReport and repairs it as needed.
Steps to reproduce are in the associated ticket. Yuck.

OBPIH-5426 Reload Courier, etc. as needed after XDocReport calls

---

grails-app/services/org/pih/warehouse/inventory/ProductAvailabilityService.groovy

I figured it was easier to talk about this head-scratcher over a PR.
Current `saveProductAvailability` behavior is to log and then re-raise the exception, which can cause the GPars worker running it to crash. Since the blast radius for this issue is fairly small, for debugging purposes I made `saveProductAvailability` return a boolean if it succeeded, then call log.info() if it works, or log.error() if it doesn't. What I really want to know is what the other GPars threads are doing, but they stop logging after the deadlock exception is raised.
Not sure what the "right" behavior here is. Is `saveProductAvailability()` idempotent? If so, we could retry it (perhaps after an incremental delay) since the deadlock conditions likely pass a few seconds after the error is raised. Or we could …

OBS-1375 Do not crash ProductAvailabilityService threads if deadlock occurs

---

grails-app/services/org/pih/warehouse/inventory/StockMovementService.groovy
src/groovy/org/pih/warehouse/order/RefreshOrderSummaryEvent.groovy
src/js/components/stock-movement-wizard/combined-shipments/AddItemsPage.jsx

This improves refreshing after removing shipment item or all shipment items on combined shipments for multiple POs.

OBPIH-5388 Add list of orders as source for RefreshOrderSummaryEvent

---

grails-app/domain/org/pih/warehouse/invoice/InvoiceItem.groovy
grails-app/domain/org/pih/warehouse/invoice/InvoiceItemCandidate.groovy
grails-app/services/org/pih/warehouse/product/ProductService.groovy
src/groovy/org/pih/warehouse/api/PartialReceiptItem.groovy
src/groovy/org/pih/warehouse/product/ProductSearchDto.groovy
src/js/components/invoice/AddItemsPage.jsx
src/js/components/invoice/ConfirmInvoicePage.jsx
src/js/components/invoice/InvoiceItemsModal.jsx
src/js/components/product-select/ProductSelect.jsx
src/js/components/receiving/PartialReceivingPage.jsx
src/js/components/receiving/ReceivingCheckScreen.jsx
src/js/utils/Select.jsx
src/js/utils/form-values-utils.jsx
src/js/utils/option-utils.jsx

Scope:
- invoice
- request
- receiving
- product select global refactor
Those include only changes on React side, as GSP view pages will be done in other ticket and also it was blocked by the refactor of `<format:displayName>` ticket.

OBPIH-5502 Refactor product translations to use displayName instead of translatedName (scope: invoice, requests, receiving) [React]

---

src/css/main.scss
src/js/components/stock-movement-wizard/outbound/AddItemsPage.jsx
src/js/consts/rowSaveStatus.js

In this pr I added:
- Fix for `rowSaveStatus: RowSaveStatus.PENDING` after adding new line using tab or arrows
- Fix for duplicating items when they are being added too fast
- Fix for showing previously added item in next line (connected to previous point)
- Enable next button after using save button when item is not autosaved (i.e when we don't have internet connection and we click save button when connection is restored)
I fixed duplicating item by adding new property in `state`. In this variable we are storing items which were sent and then we are excluding it from checking items to save during next trigger of autosave.

OBPIH-5323 Save line by line in outbound add items step (Fix for duplicating items)

---

grails-app/i18n/messages.properties
src/js/components/stock-movement-wizard/inbound/AddItemsPage.jsx
src/js/components/stock-movement-wizard/outbound/AddItemsPage.jsx
src/js/components/stock-movement-wizard/request/AddItemsPage.jsx

In this ticket I finished:
- Getting rid of unnecesary performing saving current state after triggering `next` button
- Adding notification when user clicks on `next` button during the autosave
I had to disable `next` button when rows contains line with `qty == 0`, because when we have only items with qty 0, and we go to the next page we can see infinite spinner. (I can't add this validation in validating function, because it will disable `save` button also)
In function triggered by `save` button I added filtering out rows with qty 0, because this function removes these rows after performing save. There is no need to refetch the data because of the filtering.

OBPIH-5365 Update Next functionality on add items step of outbound workflow

---

src/js/components/stock-movement-wizard/outbound/AddItemsPage.jsx

Fix for incorrect coloring after editing recipient: 
When we set the quantity to positive number, the line will be autosaved. After changing to negative number, we don't trigger autosave, because there is no need for sending this line, I just set the `rowSaveStatus` to `ERROR`. When we fix the number to the same quantity as we had previously it will become green, because it is actually saved number. Within this activity I didn't take changing recipient into account, so when we changed only recipient (leaving quantity as it is) we mapped line to `SAVED`.
Fix for saving lines after clicking on available draft:
It's just triggering function for saving, and mapping all of the not saved lines to `SAVING`. The new edited / added lines will become colors connected to their statuses.

OBPIH-5324 Track unsaved changes when falling online to offline (fixes after QA)

---

build.gradle

Minor tweak to support remote agents on the new Bamboo server, since the old one seems dead

OBGM-419 Update node plugin to, among other things, build cleanly on remote agents

---

grails-app/services/org/pih/warehouse/inventory/StockMovementService.groovy

Past values weren't saved, because we didn't save the `expectedShippingDate`, so each request with past `expectedDeliveryDate` didn't pass the validation.

OBPIH-5555 Past values of ship and delivered dates are not saved in PO shipments

---

grails-app/conf/BuildConfig.groovy
grails-app/controllers/org/pih/warehouse/JsonController.groovy
grails-app/controllers/org/pih/warehouse/api/LocationApiController.groovy
grails-app/controllers/org/pih/warehouse/inventory/InventoryController.groovy
grails-app/controllers/org/pih/warehouse/product/ProductController.groovy
grails-app/controllers/org/pih/warehouse/product/ProductSupplierController.groovy
grails-app/controllers/org/pih/warehouse/reporting/ReportController.groovy
grails-app/controllers/org/pih/warehouse/requisition/RequisitionController.groovy
grails-app/services/org/pih/warehouse/data/DataService.groovy
src/groovy/org/pih/warehouse/importer/CSVUtils.groovy
src/groovy/util/ReportUtil.groovy
test/integration/org/pih/warehouse/product/ProductServiceIntegrationTests.groovy

There is solution for two tickets - OBPIH-5222 and OBPIH-5560
OBPIH-5222:
For this ticket I added a BOM to exporting files to allow users on Windows and Mac open files with special characters without problems with displaying them.
OBPIH-5560:
In this PR I fixed importing products with special characters. The main problem was that files from Windows / MacOS have different encodings, so the char codes used in this encodings had different meaning in UTF-8.
To solve this problem I created a function `detectCSVCharset` which takes file as an argument an return its encoding (It have to be a file, because most of the information about encoding is in [file signature](https://profilbaru.com/article/List_of_file_signatures). It is possible to guess the encoding basing only on file content, but it …

OBPIH-5222 / OBPIH-5560 Import and Export files for products with special characters

---

grails-app/conf/BuildConfig.groovy

This PR resolves a few issues I found while testing OBS-1360 Ansible deployments.
config-wise, I reduced the number of Quartz threads and "niced" them to prevent thrashing the CPU when a bunch of jobs kick off.
build-wise, the following nits are resolved:
- `gant` now uses the same `GPars` release across all build phases,
- We had duplicate symbols between a 15-year-old release and a 5-year-old one. `c3p0` was renamed in 2007 (`c3p0:c3p0` -> `com.mchange:c3p0`) and one of our old dependencies was pulling in the old version. At least once I saw Grails come up using the 2007 version, although I think the runtime dependency resolution was more or less arbitrary.
(See also #3810.)

OBS-1385 Update c3p0; resolve gpars dependency conflict; add default Quartz config

---

build.gradle

This PR resolves a few issues I found while testing OBS-1360 Ansible deployments.
config-wise, I reduced the number of Quartz threads and "niced" them to prevent thrashing the CPU when a bunch of jobs kick off.
build-wise, I cleaned up the way we pull in Quartz dependencies and added a clarifying comment to our future selves should we see connection-pooling problems in Grails 3. (See also #3809.)

OBS-1385 Improve Quartz configuration and dependency management under Grails 3

---

src/js/utils/Select.jsx

What was missing is `value` key in the object, so one idea would be just to map locations and add `value` key to them, but I wanted to dive into that issue deeper to fix the real cause of that bug.
It seems to have been broken here: https://github.com/openboxes/openboxes/commit/bba8150660ef56c2a202a04d0e4a2e158ece30fc#diff-bce166e150c0e5f362f0b1054d7d07b5446f360a5b1fac77a9ccb84d005e737bR166-R239 by doing the refactor of `mapOptions` function.
Before the refactor it was not returning, so it was adding both `label` and `value` if the following `if` statements were truthy:
```javascript
let option = value;
if (typeof value === 'string') {
return { value, label: value };
}
if (value && attributes.valueKey && !option.value) {
option = { ...option, value: option[attributes.valueKey] };
}
if …
```

OBPIH-5621 Fix filter selects on the stocklist list page

---

grails-app/services/org/pih/warehouse/product/ProductMergeService.groovy

Changed finding primary inventory items for lot number and expiry date pair to looking only by lot number. Lot is unique for inventory item for a product, and there can't be multiple inventory items with the same lot with different expiry dates.

OBPIH-5631 Find primary inventory items only by lot number

---

src/js/components/stock-movement-wizard/outbound/SendMovementPage.jsx

We decided to make the download options and exit button always enabled at send request page for both requesting and fulfilling location

OBPIH-5626 Make download options and exit button always enabled

---

grails-app/conf/UtilFilters.groovy
grails-app/domain/org/pih/warehouse/core/Location.groovy

1. Circular reference for the location JSON marshaller - it was happening if an organization had a defaultLocation and this location's locationTypeCode was NOT: `DEPOT`, `INTERNAL`, `BIN_LOCATION`, `ZONE` - if it was e.g. `SUPPLIER`, we were falling back to `toJson()` method, which was referencing again the organization, and the organization was again referencing the location.
Organization.groovy
```groovy
Map toJson() { 
return [
...
defaultLocation: Location.toJson(defaultLocation),
...
]
}
```
`Location.groovy`:
```groovy
static Map toJson(Location location) {
return location ? location.toJson(location?.locationType?.locationTypeCode) : null
}
```
...
```groovy
Map toJson(LocationTypeCode locationTypeCode) {
switch(locationTypeCode) {
...
default:
return toJson()
}
}
```
...
```groovy …
```

OBPIH-5621 Fix circular reference for the location JSON marshaller

---

grails-app/i18n/messages.properties
grails-app/services/org/pih/warehouse/shipping/ShipmentService.groovy

The reason why it was working before was that we were taking `defaultMessage` > `translatedMessage`, and as you can see, I changed the code of the message, because it was a copy paste from the outbound return validation message.
Why it is appearing just now, is because after my refactor of `ErrorsController`, we now take `translatedMessage` > `defaultMessage`, which is the correct way to handle messages.

OBPIH-5641 Invalid content of error message in outbound workflow

---

grails-app/services/org/pih/warehouse/inventory/InventorySnapshotService.groovy
grails-app/services/org/pih/warehouse/inventory/ProductAvailabilityService.groovy

Add guard condition for updateProductAvailability and updaeInventorySnapshots
prevent update query from executing if productCode on event.product object is null

OBPIH-5639 NullPointerException while updating product availability during product import 

---

grails-app/conf/UtilFilters.groovy

NullPointer in the afterView filter - the problem occured, because of not handled exception thrown from the `LocationApiController`:
```groovy
render([data: location] as JSON)
```
unfortunately if we get any marshaller exception, the `render` is already sent to the response, so we get the status 200, so I don't know if there is any option to handle that, because the exception occurs not with `[data: location] as JSON`, but when the `render([data: location] as JSON)` is called...
When we do not handle the error, the `UtilFilters` doesn't run the `after` closure, so we don't assign:
```groovy
request._timeAfterRequest = System.currentTimeMillis()
```
but it goes straight to the `afterView` having `request._timeAfterRequest` as `null`.
So the `NullPointerException` was about:
`Cannot invoke …

OBPIH-5640 Fix the NullPointerException in the afterView filter

---

grails-app/services/org/pih/warehouse/core/LocationService.groovy

The issue was most probably caused by the OSIV (OpenSessionInView filter). If you are interested in detalis - you can find an explanation of my research in the ticket.

OBPIH-5662 Unable to delete internal locations on GSP

---

grails-app/services/org/pih/warehouse/core/DashboardService.groovy

The reason why it wasn't working was that a deprecated property was used there:
https://github.com/openboxes/openboxes/blob/33b93dcf20c46c073d13b6335350400b7778e4c8/grails-app/domain/org/pih/warehouse/inventory/InventoryLevel.groovy#L62-L63
instead of:
https://github.com/openboxes/openboxes/blob/33b93dcf20c46c073d13b6335350400b7778e4c8/grails-app/domain/org/pih/warehouse/inventory/InventoryLevel.groovy#L23-L24
which is currently set when editing the inventoryLevel: https://github.com/openboxes/openboxes/blob/33b93dcf20c46c073d13b6335350400b7778e4c8/grails-app/views/inventoryLevel/_form.gsp#L69-L71

OBPIH-5699 Exclude items which have bin location from the reorder report

---

grails-app/conf/Config.groovy
package-lock.json
package.json
src/js/components/stock-movement-wizard/outbound/AddItemsPage.jsx

I have to check `item.quantityRequested === undefined` instead of `!item.quantityRequested` because `quantityRequest` can be 0, so `!item.quantityRequested` will be true, but the main idea of checking that is just to validate the items which have empty quantity.
`if (item.id && newQty === oldQty && oldQty === 0) {
lineItemsToBeUpdated.push(item);
return;
}` means that we want to send items with 0 qty which are added using stock list (before when we added items using stock list, they weren't sent to save, so items with 0 qty were visible on the next page / after save)
The issue with being unable to add new lines using arrows was caused by the asynchronous behavior of `setState`, so when I added `previousState` as an argument the issue was solved.
Additionally, I had to upgrade …

OBPIH-5714 Click Next on add items page should be enabled when some line items have qtt=0 (fixes after QA)

---

grails-app/conf/runtime.groovy

The issue was weird to me at first sight, because I was trying to find some weird parts in the controller/view, but then just read and compared scaffolding docs in Grails 3 vs Grails 1.3.9 and found the differences:
Grails 1.3.9:
Grails 3:
as you can see, in Grails 3 we don't have `list` action anymore and this is why the page was not working.

OBGM-406 Unable to access scaffolded pages

---

src/js/components/DocumentButton.jsx

Using the `stringUrlInterceptor` method caused here to generate an url like this:
```
localhost:8080/openboxes/http://localhost:8080/shipment/exportPackingList/ff80818188b99eca0188b9a5adb60001
```

OBGM-472 Unable to download all documents from send page

---

grails-app/controllers/org/pih/warehouse/inventory/StockMovementController.groovy

The error was that `fileItem` is undefined. I found in the documentation of the `MultipartFile` that there is another way to get those properties:

OBGM-473 Unable to upload documents on send page

---

grails-app/services/org/pih/warehouse/order/OrderService.groovy

Roles passed from the application.yaml weren't properly compared with the values from `getEffectiveRoles(user)` (it always returned `false`, so we didn't have appropriate privileges to perform actions).

OBGM-551 Unable to Place PO

---

grails-app/conf/application.yml

I know I could've deleted this setting at all, but I prefer to leave it with the `false` flag, because figuring out what Hibernate settings for an exact version are enabled/disabled by default, is a pain in the neck, so it will provide a better readability and understanding, what is enabled/disabled

OBGM-574 Disable allow_update_outside_transaction Hibernate setting

---

grails-app/services/org/pih/warehouse/product/ProductService.groovy

The problem was with a difference between joining type in Grails 1 vs Grails 3 - we were fixing this once, but the join was added in a wrong place, because we should join synonyms only if we provide `params.name`.
Additionally - the pagination was showing wrong results, because the `LEFT_JOIN` was giving us duplicate results which was then cut by the distinct. 
Why it was giving duplicate results is due to `LEFT_JOIN` being used - if a product has 4 synonyms, it was considered 4 times in the query.
A workaround for that was to add an additional criteria to the `createAlias`, which was to join by `product.id` and `synonym.product_id` AND `synonymTypeCode = SynonymTypeCode.DISPLAY_NAME` - this will remove the duplicates, because we can have only one `DISPLAY_NAME` synonym.
Fortunately we …

OBGM-545 Fix pagination for product list

---

grails-app/conf/application.yml
grails-app/domain/org/pih/warehouse/order/Order.groovy
grails-app/domain/org/pih/warehouse/picklist/PicklistItem.groovy
grails-app/services/org/pih/warehouse/shipping/ShipmentService.groovy

As this ticket drove me nuts, a little description (as always :smile: ):
**1. rollback problem** - we have a bidirectional relationship between `Transaction` and `Shipment`. The problem there was that we were not assigning `outgoingShipment` to the `Transaction` instance, we were only doing it for one direction, so for shipment like:
```groovy
shipmentInstance.addToOutgoingTransactions(debitTransaction)
```
For correct bidirectional relationships, we have to add it for both sides.
Grails is that clever, that when doing `addToOutgoingTransactions`, it was automatically assigning the `outgoingShipment` for the `debitTransaction` also, but it was not persisted. In grails 1 it was working due to OSIV, that was catching those "dirty" changes and here, it doesn't work, because we saved the …

OBGM-560 Fix association between transaction and shipment while rollbacking and fix refresh product availability when deleting outbound return

---

grails-app/controllers/org/pih/warehouse/product/ProductController.groovy

It turned out that there is some difference between `MultipartHttpServletRequest` implementation in Grails 1 and Grails 3 and this is probably why it couldn't cast this class now.
Since `CommonsMultipartFile` is an implementation of `MultipartFile` interface:
```groovy
public class CommonsMultipartFile implements MultipartFile, Serializable {
```
we can (and should) use it as a type here, since it is even more correct in terms of [dependency inversion principle](https://stackify.com/dependency-inversion-principle/), and the error disappears and the import works correctly.

OBGM-535 Fix synonyms import through edit product page

---

grails-app/conf/application.yml

I didn't notice it at first but after QA Katarzyna pointed out that the format of generated identifier for product source didn't match the one that is on `develop` branch so I compared both branches and in fact there was a difference in formats
https://github.com/openboxes/openboxes/blob/1e77b282da20c34b75ebec47b896e3528dae095e/src/groovy/org/pih/warehouse/core/Constants.groovy#L121
Based on commits I did not see any reasoning behind changing the format on `feature/upgrade-to-grails-3.3.10` so I assume it was probably a mistake

OBGM-577 Change product supplier identifier format to be the same as on develop branch

---

grails-app/views/inventory/_filters.gsp
grails-app/views/inventory/browse.gsp

Pagination was not visible because `commandInstance?.searchResults instanceof grails.orm.PagedResultList` was false - PagedResultList is an instance of `org.pih.warehouse.PagedResultList`.
After fixing the issue described above I noticed that there is an error after changing the page with filters applied. In the URL we had two similar params: `location.id=...` and `location=[id: ...]`. This second one wasn't visible after changing the page with filters. I saw that the command instance assigned location to its property when there was just `location.id` passed. After passing the `location=[id: ...]` command used this one parameter to get the location property and after that error with an invalid constructor of the Location class was thrown. I removed the `.id` from the location param, so …

OBGM-536 Pagination not visible on inventory browser 

---

grails-app/controllers/org/pih/warehouse/core/ErrorsController.groovy
grails-app/services/org/pih/warehouse/inventory/StockMovementService.groovy
src/js/components/stock-movement-wizard/outbound/PackingPage.jsx
src/js/components/stock-movement-wizard/outbound/PickPage.jsx
src/js/components/stock-movement-wizard/outbound/SendMovementPage.jsx
src/js/utils/apiClient.jsx

OBGM-566:
The previous handling of our messages in "red boxes" were deleted, so I reverted it, but I did it in a more reusable way - I created a new `apiClient` (we cannot override previously set `interceptor` behavior, adding new one results in showing popup error and the 'red box'). Within `apiClient.js` I override the behavior while getting a response but let us use custom behavior for a response. Additionally, I made the `handleValidationErrors` curried function to pass the `setState` for each component that needs the content of the message to be set.
OBGM-567:
The first thing was that the interceptor behavior wasn't overridden, so we didn't get the error messages in the 'red boxes'. The second thing was a change in Exception, we didn't have errors and fullMessage in the same place in …

OBGM-567 / OBGM-566 Unable to reload autopick after editing qty of pick item to 0 and styling of qty atp validation not visible

---

grails-app/controllers/org/pih/warehouse/product/ProductSupplierController.groovy
grails-app/services/org/pih/warehouse/data/DataService.groovy
grails-app/views/batch/_uploadFileForm.gsp

The core issue of this product supplier export bug was that some of the data was missing.
After debugging the code I figured out that the data that was missing involved records which had empty **supplier**, **manufacturer** or **contractPrice**. If you look at the previous criteria query you can see that all three of these attributes were specified as nested values in projections, like:
```
supplier {
property("name", "supplier.name")
}
manufacturer {
property("name", "manufacturer.name")
}
contractPrice {
property("price", "contractPrice.price")
property("toDate", "contractPrice.toDate")
}
```
so apparently when we want to access a nested value of a `null` attribute in a projection it ignores the whole record instead of returning a `null` for just this _attribute_.
Thank to @alannadolny …

OBGM-520 Fix export product supplier missing data

---

grails-app/services/org/pih/warehouse/core/DocumentService.groovy

Validation of merging regions in xls has changed. In the new version number of merging cells has to be higher than 1:
Meanwhile, in Grails 1 the only validation that is being checked is:
So, I removed the `initialRowIndex` and `finalRowIndex` variables. In the begging, both of them have 0 as a value. Later in each iteration, we assigned `row.getRowNum()` to both of them, so they have the same value every time.
When the number of cells was greater than 16, this part of the code was triggered:
`sheet.addMergedRegion(CellRangeAddress.valueOf("A${initialRowIndex + 1}:A${finalRowIndex + 1}"))`
So, because of the fact, that `initialRowIndex` and `finalRowIndex` are equal, we are doing sth like this:
`sheet.addMergedRegion(CellRangeAddress.valueOf("A17:A17"))` …

OBGM-539 No longer able to download certificate of donation from send page of outbound and requests

---

grails-app/views/stockMovement/_packingList.gsp

In Grails 1 `<g:set var="previousContainer"/>` set value of `previousContainer` to empty string:
In Grails 3 value of `previousContainer` is null.
So, `previousContainer != shipmentItem?.container` was evaluated to false at the beginning, because it was `null != null`. It should be true to display `unpacked` (in Grails 1 it was `'' != null`)

OBGM-549 Unpacked packing unit not visible on Packing list on SM view page 

---

grails-app/taglib/org/pih/warehouse/SelectTagLib.groovy
grails-app/views/location/edit.gsp

The `selectZoneLocationByLocation` is defined like this:
```groovy
def selectZoneLocationByLocation = { attrs, body ->
def location = Location.get(attrs.id)
if (location) {
attrs.from = locationService.getZones(location)
}
attrs["class"] = "chzn-select-deselect"
attrs["noSelection"] = ["null": ""]
attrs.optionKey = 'id'
attrs.optionValue = 'name'
out << g.select(attrs)
}
```
so we were only assigning `from` param if `location` is not falsy.
From the Grails 3 docs we can see that `from` param is required for `g:select`: 
and that the implementation of the select has this if statement (2nd from the top):
which I couldn't find in the implementation in Grails 1. It's weird, because Grails 1 docs also say, that `from` param is required.

OBGM-610 Fix creating an internal location

---

grails-app/controllers/org/pih/warehouse/requisition/RequisitionTemplateController.groovy

The problem was difficult to identify, because random errors were thrown at the end of the session - sometimes regarding the template, sometimes regarding the `isUserAdmin` etc functions, so that led me to the point, that something must be wrong with the user.
The error I was getting the most times:
The problem is that when we bind the properties to `requisition`, we also bind users instances here like `createdBy`, `requestedBy`, `updatedBy`.
When assigning the `requisition.updatedBy = session.user`, we were trying to assign a User object of identifier that is already known for this session (read the error message).
So in fact we were having two "different" (the same) objects with the same ID in the same session, which Hibernate doesn't allow.
Look at the numbers of the User object:
1. …

OBGM-586 Fix user reference that caused header of stocklist not editable

---

grails-app/controllers/org/pih/warehouse/core/LocationController.groovy

In Grails 1 `supportedActivities` before saving was LinkedHashSet and after saving it was PersistentSet.
In Grails 3 it was HashSet and after saving it hasn't changed. Grails didn't notice that `supportedActivities` has changed and it wasn't marked as dirty. One solution could be just marking it as dirty or doing this trick with params. As I saw we did something similar to this so I decided to follow this approach.

OBGM-623 Unable to unselect use default settings for locations 

---

grails-app/controllers/org/pih/warehouse/user/UserController.groovy
grails-app/services/org/pih/warehouse/core/UserDataService.groovy

It was meant to be a bigger issue due to a weird error Katarzyna has attached to the ticket. Since it was 5 SP I tried to reproduce the same issue what she had in the browser console, but I couldn't reproduce this particular issue. I think that this straight forward change is a clue to the problem and the error Katarzyna had, was a one time accident.
After the change a user is deleted properly and if it can't be deleted, we get an information that "User could not be deleted".

OBGM-625 Fix transaction required exception when deleting a user

---

src/main/groovy/org/pih/warehouse/inventory/InventoryCommand.groovy

The `showOutOfStockProducts` was not bound correctly, it is explained here: https://stackoverflow.com/questions/60990362/grails-command-object-not-binding-to-def-type
Part of the documentation linked in question above:
> Properties which are not bindable by default are those related to transient fields, dynamically typed properties and static properties.

OBGM-619 Include out of stock checkbox not working on inventory browser 

---

grails-app/services/org/pih/warehouse/inventory/InventoryService.groovy
src/main/groovy/org/pih/warehouse/inventory/RecordInventoryCommand.groovy

The problem was hard to spot, so I'll explain it:
In my opinion implementations of `validator` is different in Grails 1 and in Grails 3.
`validator` accepts up to three parameters: `value` (that we are validating), `object` (that owns this value/property), `errors`.
Instead of adding an error to `errors` (3rd parameter of `validator` closure), we were adding it to `object.errors` which in fact was the same in Grails 1 (more below with examples), but was not the same in Grails 3.
As you can see we were always operating on the same `BeanPropertyBindingResult` of hash `16619`, so: `obj.errors` and `errors` were the same thing and also the `commandInstance.errors` in the service were still pointing to the `16619`.
You can see that the `obj.errors` has initial hash of `21961` and the `errors` …

OBGM-635 Fix validation for negative quantity of RecordInventory

---

grails-app/controllers/org/pih/warehouse/reporting/ReportController.groovy

The `triggers` variable didn't contain any triggers after calling the `getTriggersOfJob` method. As I checked `JobKey` created a key with the `DEFAULT` group:
In the `quartzScheduler` I found that `RefreshTransactionFactJob` belongs to the `GRAILS_JOBS` group. After adding this second parameter, the triggers were correctly found.

OBGM-622 Previous and Next Refresh not filled with value on transaction report

---

grails-app/conf/application.yml
src/js/api/urls.js
src/js/components/locations-configuration/LocationAddress.jsx
src/js/utils/apiClient.jsx

In this ticket, I found two issues that needed fixing. First was connected to `flattenRequest` function, which we used to flatten our request before being sent (In Grails 1). Apart from flattening, this function removed properties that were null.
I logged results for empty properties in the address with `flattenRequest` and without it. The results were as follows:
So, removing empty properties solved saving addresses and moving forward and backward without addresses.
After fixing it, I was thinking about the case when we want to delete the address and going forward and backward - removing inputted address and going backward didn't send the changes we made, because we removed it in the solution described above. So, I had to check again what's the difference between Grails 1 and Grails 3 …

OBGM-627 Unable to go forward/backward on Address page in location configuration 

---

grails-app/views/purchaseOrder/_showOrderItems.gsp

This issue was caused by the quotation marks used in languages other than English. In the confirmation dialog in English, we used single quotation marks
But In the French language, we were using both - single quotation marks and standard quotation marks:
So changing it to backticks fixed this issue

OBGM-620 UI issue in Fr locale: where tabs on PO add items are displayed on the same page

---

grails-app/domain/org/pih/warehouse/receiving/Receipt.groovy
grails-app/services/org/pih/warehouse/inventory/StockMovementService.groovy

The issue was that there was a case where it was impossible to sort this list since all of the values specified in the comparator conditions had the same values so it resulted in a random order list each time it was generated.
To fix this I added an additional last fallback comparator to sort by product name.

OBGM-654 Add additional sort fallback condition for receiptItems sorting

---

grails-app/services/org/pih/warehouse/data/ProductSupplierDataService.groovy

When we were updating package size through import and we had previously added package and product price we were just updating our default product package like that:
`defaultProductPackage.productPrice.price = price`
So, the save action was performed only on `ProductPrice` object, because the reference didn't change. Our default product package is this one with the newest `lastUpdated`. So after this kind of update, the `lastUpdated` wasn't triggered and after update, we saw the same package size as we had before import.
As a solution, I decided to update the `lastUpdated` property manually.

OBGM-648 Unable to edit Package size from other to each in product source import 

---

grails-app/services/org/pih/warehouse/data/ProductSupplierPreferenceDataService.groovy
src/main/groovy/org/pih/warehouse/importer/CSVUtils.groovy
src/main/groovy/org/pih/warehouse/importer/ProductSupplierPreferenceImporter.groovy

This issue was caused by importing dates as Excel dates, not as a string. It leads to different dates in the table and in the message above the table. It's visible on the screenshot that Katarzyna pasted to the ticket:
This number is visible instead of the normal date, because of the method that Excel uses to store his dates - it is a number of days counted from 1st January of the 1900 year.
Here is an explanation of how it works:
https://community.fabric.microsoft.com/t5/Desktop/Convert-a-date-value-like-42917-to-date/m-p/559598
So, I created a function `getDateFromExcel` which converts days to normal dates. In this function, I had to subtract two days from the result, because of the Excel oddity. 
The first day to subtract is because of that, Excel counts 01/01/1900 as a first day, but …

OBGM-650 Unable to import dates in product source preference import 

---

grails-app/services/org/pih/warehouse/core/UserService.groovy

It was interesting that in the debugger roles were bound correctly, but during saving the error with mismatching type was thrown. When I added "no access" to the roles and evaluated the user's role after binding everything looked good. When I let the debugger go line after the save method I saw that one error was visible.
👇 This part of the code tried to bind the roles with appropriate mapping to the Role object, but the "no access" had a "null" value and it could not be fetched, so I bound the roles manually. Grails 1 looks like he didn't have a problem with just skipping the "null"
```
userInstance.properties = params
```
I also moved the `updatedRoles` higher in the function to avoid fetching the roles twice.

OBGM-670 Unable to assign to user "No access" role

---

grails-app/controllers/org/pih/warehouse/product/AttributeController.groovy
grails-app/domain/org/pih/warehouse/product/Attribute.groovy

The first change:
```
render(view: "edit", model: [attributeInstance: attributeInstance])
```
is precisely the same as Justin wrote under the ticket - there is only an edit view, and the create view doesn't exist. Even the create action renders the edit view page. The issue connected to this was visible when creating a new attribute with existing code other than an empty string.
The second change connected to validation is because of the situation - when we didn't input code, it is an empty string and it didn't fail on `unique: true` (I mean the situation when one product attribute with empty code already exists, so it should fail). It was throwing an exception
Katarzyna asked me to make this error more meaningful, so I have created our "unique" validation which takes empty strings into …

OBGM-637 Error message when try to create attribute without input Code

---

src/main/groovy/org/pih/warehouse/importer/ImportDataCommand.groovy

At this moment we had only one place where the `fileItem` was used.
So, the `MultipartFile` (which we are widely used in our command instances) looks like that:
```java
public interface MultipartFile extends InputStreamSource {
String getName();
String getOriginalFilename();
String getContentType();
boolean isEmpty();
long getSize();
byte[] getBytes() throws IOException;
@Override
InputStream getInputStream() throws IOException;
void transferTo(File dest) throws IOException, IllegalStateException;
}
```
We have also `CommonsMultipartFile` which implements the `MultipartFile` interface - here we have the `fileItem` property (We are using this class in some places also).
```java
public class CommonsMultipartFile implements MultipartFile, Serializable {
protected static final Log logger = …
```

OBGM-669 Investigate changes in importing file properties

---

grails-app/controllers/org/pih/warehouse/inventory/TransactionEntryController.groovy
grails-app/views/transactionEntry/create.gsp
grails-app/views/transactionEntry/edit.gsp
grails-app/views/transactionEntry/list.gsp
grails-app/views/transactionEntry/show.gsp

As I saw the data wasn't visible in any of our pages, so I fixed it for all of the pages connected to transaction entries. I don't know why IntelliJ added those spaces after saving those files, so I have to leave them.

OBGM-686 Unable to display transaction entries (fix after QA)

---

grails-app/controllers/org/pih/warehouse/api/StockMovementApiController.groovy

The ticket connected to this PR was reopened after QA because I didn't do the same changes which I did in #4246 .
In the previous PR I only changed the `StockMovementController` but I  also had to do the same for `StockMovementAPIController`.
The issue was of course that StockMvoementAPIController was transactional making it impossible to catch exceptions inside those controller methods.
I have looked through all of the methods in the `StockMvoementAPIController` and from what I can tell it should be safe to remove `@Transactional` from this controller since every method uses the transactional services.

OBGM-683 Fix error message for delete Stock Movement

---

grails-app/domain/org/pih/warehouse/inventory/InventoryLevel.groovy
grails-app/utils/org/pih/warehouse/EmptyStringsToNullBinder.groovy
grails-app/utils/org/pih/warehouse/NullBinderHelper.groovy

In one of my previous PRs, I introduced the `convertEmptyStringsToNull` setting in our config because, in the resources I found and pasted in https://github.com/openboxes/openboxes/pull/4212, it looked like it was introduced between Grails 3.1.9 and 3.3.1 versions of Grails and it looked like help for us to get closer with the Grails 1 behavior. This setting resolved actually some tickets, so I think it is a good change, but in this ticket, I found that we weren't able to assign empty strings to a few properties, because those empty strings were used in the BigDecimal constructor - it normally throws an error, so in this case Grails doesn't bind those values. Those values had to be null to be bounded correctly and they were nulls in Grails 1. 🤔 So it's a little bit different that in this …

OBGM-690 Unable to clear values on Forecasting tab on edit location

---

grails-app/services/org/pih/warehouse/product/ProductService.groovy

There were two problem that I was able to spot in this issue, so let me explain each of them:
When inspecting the category csv import files I noticed that the  `default_OB_categories.csv` has a ROOT category defined as an entry
Following the code of how we import the categories we can see that before importing the category list we _find/create_ a root category `findOrCreateRootCategory()` and later we loop through all of the csv file entries and import them.
https://github.com/openboxes/openboxes/blob/a18cecb090c97a07a10cc1b0f600730b79a9ac8f/grails-app/services/org/pih/warehouse/product/ProductService.groovy#L1430-L1446 
Everything looks right until we look a little deeper.
So first of all when we, _find/create_ the root category we are saving it at the end of the session, since we have …

OBGM-532 Fix issue of creating multiple ROOT categories on category import

---

grails-app/controllers/org/pih/warehouse/core/LocationController.groovy
grails-app/services/org/pih/warehouse/inventory/InventoryLevelDataService.groovy

This ticket is reopened because of the fact that `@Transactional` annotation was removed from LocationController in one of the Dariusz PRs (https://github.com/openboxes/openboxes/pull/4250/files) So the inventory level wasn't saved.

OBGM-690 Unable to clear values on Forecasting tab on edit location (fix after QA)

---

src/js/components/products/ProductsListTable.jsx

I asked Manon about the sorting behavior that needs to be applied here since it doesn’t work on obdev1 either (One product can have more than one formulary, so the question was if should we sort them by amount of formularies or in any other way). Manon said it would be better to remove this sorting option because users use filters to manage data in this column.

OBGM-706 Error message when sort by Formulary column on Product List 

---

grails-app/services/org/pih/warehouse/core/DocumentService.groovy

The newer version of document generation plugin does not allow merger of a single cell.
Comparing it to develop branch, previously it was possible to execute merger of cells give the argument eg. **A:1:A:1**.
Now, given such an argument, the merge method throws an error that two or more cells must be provided which is why this line was previously commented.

OBGM-685 Fix cell merging on packing list xlsx document

---

grails-app/migrations/0.9.x/changelog-2023-09-08-1340-remove-missing-price-fk-on-product-packages.xml
grails-app/migrations/0.9.x/changelog-2023-09-08-1340-remove-product-price-fk-on-product-package-pointing-to-non-existing-record.xml
grails-app/migrations/0.9.x/changelog.xml
grails-app/services/org/pih/warehouse/data/ProductSupplierDataService.groovy
grails-app/views/category/edit.gsp
grails-app/views/inventoryItem/_showSuppliers.gsp
grails-app/views/product/_productPackages.gsp

This is a rather ugly bug and I think we should investigate it a little more, but first, let me explain what is going on, because there are many connected things that cause this issue. 
_Sorry in advance for my complicated explanation_
First I need to give some context into domain structure and create product source logic, so Let me highlight the relationship and constraint on certain fields in this hierarchy tree.
On **ProductSupplier** we have a 1:many relationship with a **ProductPackage**, and **ProductPackage** has a `nullable: true` **ProductPrice** which has a field **price** that is `nullable: false`.
When creating a product source using import data, without specifying the package price in the column, we are expecting it to throw a validation exception, because we are assigning …

OBGM-687 price and package issue in product source import

---

grails-app/conf/Config.groovy
grails-app/controllers/org/pih/warehouse/api/ApiController.groovy
grails-app/i18n/messages.properties
grails-app/migrations/0.8.x/changelog-2023-09-13-1233-rename-approver-role-to-purchase-approver.xml
grails-app/migrations/0.8.x/changelog-2023-09-13-1252-add-request-approver-role.xml
grails-app/migrations/0.8.x/changelog-2023-09-13-1252-add-requisition-approver-role.xml
grails-app/migrations/0.8.x/changelog.xml
grails-app/services/org/pih/warehouse/core/UserService.groovy
grails-app/services/org/pih/warehouse/order/OrderService.groovy
grails-app/taglib/org/pih/warehouse/AuthTagLib.groovy
src/groovy/org/pih/warehouse/core/RoleType.groovy
test/unit/org/pih/warehouse/api/ApiControllerTests.groovy

As I know we decided to do [OBPIH-5800](https://pihemr.atlassian.net/browse/OBPIH-5800?atlOrigin=eyJpIjoiNWUxNjdhMDE0OWQ5NDM3OTkzNmUwZjVjYTkwMGZlMmYiLCJwIjoiaiJ9) within [OBPIH-5799](https://pihemr.atlassian.net/browse/OBPIH-5799?atlOrigin=eyJpIjoiZmQxYzIzNmUyYjhmNGJkZGIwODFhNTJlZGI1NzI2NGEiLCJwIjoiaiJ9), so I have pushed changes from both of them to this PR.
[OBPIH-5800]: https://pihemr.atlassian.net/browse/OBPIH-5800?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[OBPIH-5799]: https://pihemr.atlassian.net/browse/OBPIH-5799?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OBPIH-5799 / OBPIH-5800 Add purchase approver and request approver permissions

---

grails-app/i18n/messages.properties
grails-app/services/org/pih/warehouse/inventory/RequisitionStatusTransitionEventService.groovy
grails-app/views/email/_approvalsAlert.gsp

I am not calling this function in this PR, because in the draft created by Justin during TH, we decided to call it on an event. So it should be placed like that (code from notes from TH):
```
class RequisitionStatusTransitionEventService implements EventListener<RequisitionStatusTransitionEvent>
def onApplicationEvent (RequisitionStatusTransitionEvent event) {
triggerRequisitionTransitions(event)
publishWebhookEvent(event)
publishMessageQueueEvent(event) // FHIR event for a specific thingy thing
publishDefaultEmailNotifications(event)
}
}
```
I created here `RequisitionStatusTransitionEventService` just for the `publishDefaultEmailNotifications` method. The rest of the code (including event) is a part of another ticket.

OBPIH-5820 Email alert to approver(s) - Approvals email alerts

---

grails-app/services/org/pih/warehouse/core/UserService.groovy
src/js/components/stock-movement-wizard/request/CreateStockMovement.jsx
src/js/utils/Select.jsx

Forgot to add the location parameter on the frontend when fetching approvers based on location roles.
~Additionally fixed the multi-select tooltip, which was showing up because it's value is an `Array` instead of simple `[]`.
When casting an `Array(0)` to a `boolean` it returns `true` unlike casting a `[]` which returns `false`~
Additionally fixed the multi-select tooltip, which was showing up because it's value is an array which is a truthy even when it is empty.

OBPIH-5802 Fetch users based on role in fulfilling location

---

grails-app/domain/org/pih/warehouse/requisition/Requisition.groovy
grails-app/services/org/pih/warehouse/inventory/RequisitionStatusTransitionEventService.groovy
grails-app/services/org/pih/warehouse/inventory/StockMovementService.groovy
grails-app/services/org/pih/warehouse/report/NotificationService.groovy
grails-app/services/org/pih/warehouse/requisition/RequisitionService.groovy
grails-app/views/email/_approvalsAlert.gsp
src/groovy/org/pih/warehouse/requisition/RequisitionStatusTransitionEvent.groovy

@alannadolny When I called the `publishDefaultEmailNotifications()` in the `onApplicationEvent` there was a problem with `g.render` and `g.crealink` which threw an exception
```
Method threw 'java.lang.IllegalStateException' exception.
No thread-bound request found: Are you referring to request attributes outside of an actual web request, or processing a request outside of the originally receiving thread? If you are actually operating within a web request and still receive this message, your code is probably running outside of DispatcherServlet/DispatcherPortlet: In this case, use RequestContextListener or RequestContextFilter to expose the current request.
```
looking at other methods connected to sending mail located in `notificationService` I noticed that they use `renderTemplate()` …

OBPIH-5821 Move send notification logic to notificationService and add individual links for approvers to request list

---

src/groovy/org/pih/warehouse/requisition/RequisitionStatus.groovy

There were those 3 new statuses added in one of the previous pr, so I had to remove those, and I didn't add `REJECTED` status before

OBPIH-5854 New approval statuses in SM list pages - Approvals lists pages (fix after QA)

---

src/js/components/stock-movement-wizard/StockMovementVerifyRequest.jsx
src/js/components/stock-movement-wizard/request/EditPage.jsx
src/js/components/stock-movement/outbound/StockMovementOutboundTable.jsx
src/js/components/stock-transfer/utils.jsx
src/js/consts/requisitionStatus.js
src/js/utils/permissionUtils.js

I asked Manon about the designated behavior of the edit options:
1. When we are on the view page - after clicking edit we are redirected to the add items view page of the selected request, but this view is read-only. The "edit items" button is not visible.
2. When we are on the requests list - the edit option on the dropdown for the selected requests is not visible.
The edit option is not visible when:
1. Our location supports requests approval - request can be edited when it is not in approved/rejected status. It can be edited only by the requestor.
2. Our location doesn't support request approval - it should stay as it was before, every person can edit every request (restrictions are only based on locations)

OBPIH-5805 Approver cannot edit requests - Approvals end to end workflow

---

grails-app/services/org/pih/warehouse/inventory/StockMovementService.groovy
grails-app/services/org/pih/warehouse/requisition/RequisitionService.groovy
src/groovy/org/pih/warehouse/requisition/RequisitionStatus.groovy
src/js/components/stock-movement-wizard/request/AddItemsPage.jsx

lets discuss...
The issue came up when trying to create an outbound with a location which has the supported activity for request approval.
The expected behaviour would be that on Edit step an outbound should have status `VERIFYING` but instead it was `WAITING FOR APPROVAL`.
The reason for that was that in both cases (Request and Outbound) we update status with `{ status: 'REQUESTED' }` which is mapped to `PENDING_APPROVAL` (change which was introduced in [here](https://github.com/openboxes/openboxes/pull/4288/files#diff-64dcf115d2530bcb242b9a4d135db1e44c97f2ca945b602816d3b78f33eedd58R115))
Was there a particular reason why we didn't separate VERIFYING and PEWNDING_APPROVAL as individual cases?

OBPIH-5806 Update with PENDING_APPROVAL status on approval submit and REQUESTED on reagular outbound

---

grails-app/domain/org/pih/warehouse/core/Comment.groovy
grails-app/views/order/show.gsp
grails-app/views/stockMovement/_comments.gsp
grails-app/views/stockMovement/show.gsp
web-app/css/badge.css

- add comment count badge
- sort comments desc by last updated
- show comments only on requests (check by SourceType == Electronic)

OBPIH-5825 Add comments count on comments tab

---

grails-app/services/org/pih/warehouse/inventory/OutboundStockMovementService.groovy
src/js/components/stock-movement/outbound/FilterFields.jsx
src/js/hooks/list-pages/outbound/useOutboundFilters.jsx

Unfortunately, the approach with the subqueries that we discussed on the tech-huddle wasn't ideal, the issue that came up was with filtering by requests with **empty**  associations, so I decided to go with the simplest solution of querying the request ids and then querying the requests by the list of the these ids.
the approach with subqueries looks something like
```groovy
if (params.list("approver")) {
or {
createAlias("requisition", "requisition")
if (params.list("approver").contains("null")) {
isEmpty("requisition.approvers")
}
if (stockMovement.approvers) {
createAlias("requisition.approvers", "approver")
add Subqueries.exists(
DetachedCriteria.forClass(Person.class)
.add(Restrictions.in("approver.id", stockMovement.approvers.id))
.setProjection(Projections.property("id"))
)
}
}
} …
```

OBPIH-5814 Add NONE option to approvers filter

---

src/js/components/stock-movement/modals/RejectRequestModal.scss
src/js/components/stock-movement/modals/RejectRequestModalContent.jsx

The label was hidden under the comment field after adding `rows: 7`, so I had to resize the container to show the message.

OBPIH-5870 Add required label to comment field in reject request modal

---

src/js/components/form-elements/FieldArrayComponent.jsx

Since we are not taking advantage of the horizontal scroll on ArrayField tables it looks to be safe to set the `overflow-x` on the table content to `hidden` to prevent the glitching scrollbar from appearing on certain application widths.
The only overflow property that was set, was overflow-y which enabled scrolling on virtualized and paginated tables.

OBS-1540 Set overflow-x to hidden by default on arrayField table

---

src/js/hooks/list-pages/useTableData.jsx

The solution which I implemented in my previous PR
```js
tableRef.current.onPageChange(0);
tableRef.current.fireFetchData();
```
introduced I bug which caused the table to double fetch the data when resetting the pagination to the first page.
The issue seems to be that, `onPageChange(0)` triggers the `fireFetchData()` which would result in two `fireFetchData()` API calls to race (one with offset 0 and another with previous offset value).
At first, I thought that replacing `tableRef.current.fireFetchData();` with  `tableRef.current.onPageChange(0);` would solve the problem, but `onPageChange(0)` does not trigger the fireFetch on the initial load, basically it does not trigger the fireFetchData when we are trying to changePage to the same value as the currentPage.
I hope the comment I left …

OBPIH-5909 Fix list table pagination reset on filter change

---

grails-app/services/org/pih/warehouse/inventory/StockMovementService.groovy

When getting a list of stockMovementItems on inbound create page, inventoryItem variable was missing data which caused some validation issues.
I noticed that we are not assigning the inventoryItem on stockMovementItem for a case where SM is from requisition.
This is the logic how it;s done when SM is from shipment.
```groovy
StockMovementItem stockMovementItem = StockMovementItem.createFromShipmentItem(shipmentItem)
if (stockMovementItem.inventoryItem) {
def quantity = productAvailabilityService.getQuantityOnHand(stockMovementItem.inventoryItem)
stockMovementItem.inventoryItem.quantity = quantity
}
stockMovementItems.add(stockMovementItem)
```

OBPIH-5884 Add missing inventoryItem data on getStockMovementItem

---

grails-app/controllers/org/pih/warehouse/reporting/ConsumptionController.groovy
grails-app/utils/org/pih/warehouse/CommandUtils.groovy
grails-app/views/consumption/_filters.gsp

1. `selectedProperties` not being binded in `ShowConsumptionCommand` command in `show` method
2. getting rid of deprecated in Grails 3: `new DefaultGrailsDomainClass(Product.class)` and replacing it with `Holders.grailsApplication.mappingContext.getPersistentEntity(Product.class.name).persistentPropertyNames`
1. using TYPE instead of `def`, because `def` is not binded for command since Grails 2: [Properties which are not bindable by default are those related to transient fields, dynamically typed properties and static properties.](https://grails.github.io/grails2-doc/2.5.6/ref/Constraints/bindable.html)
2. The problem was that 1. we were using persistentProperty**Names**, not persistent**Properties**, but even with that, we didn't have access to fields such as `typePropertyName` and …

OBGM-264 Fix additional columns for CSV in consumption report

---

grails-app/domain/org/pih/warehouse/product/ProductSupplier.groovy
src/main/groovy/org/pih/warehouse/importer/ProductSupplierExcelImporter.groovy

The default value for this property was set in the domain:
In Grails 1 when we don't provide value for the active column, we don't have this property in the `params` object, so in this line:
`productSupplier = new ProductSupplier(params)`
we used the default value from the domain.
In Grails 3 when we don't provide the value, we have `active: null` in the params object, so the `true` value from the domain is overridden by the null value and this is treated as a false.
Besides the solution that I pushed, I am thinking also about:
- Just write:
```
productSupplier.active = params["active"] ? params["active"] : true
```
but I think the current solution is much cleaner.
- Use the `@BindUsing` annotation and check if we provide the value inside it.
```
@BindUsing({ obj, source -> …
```

OBGM-711 Empty active field read as inactive in product sources import

---

grails-app/controllers/org/pih/warehouse/api/ProductApiController.groovy

According to the MySQL documentation: https://dev.mysql.com/doc/refman/8.0/en/string-literals.html#character-escape-sequences
I added a `replaceAll` for all passed single quotes to execute within an SQL query. There is a table with special characters escape sequences:

OBPIH-5865 Apostrophe in product search gives error

---

grails-app/services/org/pih/warehouse/order/OrderService.groovy

It was once fixed by @alannadolny : https://github.com/openboxes/openboxes/pull/4129
The problem is that then, we had the `defaultRoleTypes` specified in `application.yml` and there, those were strings + `application.yml` is "overwriting" the `runtime.groovy`, hence the bug appeared after doing a cleanup here: https://github.com/openboxes/openboxes/pull/4357/files#diff-2345571d250535e4fc0497dd6c69264ff94e35858391237390112d005c9d1a36 where the `defaultRoleTypes` had been removed from the `application.yml` and it started taking the `runtime.groovy` into account.
To fix the issue I just reverted Alan's change from #4129, because in `runtime.groovy` we don't use strings, but enum classes.

OBGM-716 Unable to place PO

---

grails-app/services/org/pih/warehouse/picklist/PicklistService.groovy

This issue was hard to spot like any other issue caused by the OSIV. After clicking the "refresh" button on the frontend side, this happened on the backend:
clear picklist -> refresh product availability -> create picklist
When we are creating a picklist we are getting available and suggested items. Suggested items are based on available items and additionally, they have to meet the following conditions:
```
availableItems?.findAll { it.quantityAvailable > 0 && it.pickable }
```
but each item had a quantity available equal to 0.
Available items are calculated using this query:
```
ProductAvailability.executeQuery("""
select 
ii,
pa.binLocation,
pa.quantityOnHand,
pa.quantityAvailableToPromise
from ProductAvailability pa
left outer join pa.inventoryItem ii
left outer join pa.binLocation bl …
```

OBPIH-5793 Reload button issue in bin replenishment

---

grails-app/views/mobile/outboundList.gsp
grails-app/views/mobile/productList.gsp
grails-app/views/productComponent/index.gsp
grails-app/views/role/index.gsp
src/main/templates/scaffolding/index.gsp

Looking at commits I wasn't able to find any trail to when the eg. `class="pagination'` was changed to `class="paginateButtons"`.
Both develop and feature branch don't have any common commits, probably was a result of moving the files around the project.
The correct class for list pages are **paginateButtons** and **h2** instead of **h1** for the heading

OBGM-726 Fix gsp list table styles

---

grails-app/controllers/org/pih/warehouse/api/DashboardApiController.groovy
grails-app/services/org/pih/warehouse/dashboard/IndicatorDataService.groovy

On obdev3 I noticed one issue connected to the cache, which was not visible when I ran it locally. Two more indicators were throwing this issue with the cannot call `.toJson` method because we could not cast nested types in the cache to the originally created class, so I moved the rest of the `toJson`s to be sure that this issue is completely gone (I added a comment for each of that, of course)
It will be fixed when we will be able to use Cacheable on the controller method instead of service.

OBGM-71 Move toJsons for the rest of the methods to service

---

grails-app/services/org/pih/warehouse/inventory/RequisitionStatusTransitionEventService.groovy

In the end, the issue was with `LazyInitializationException` which occurred when building the approver emails.
The interesting part was that it didn't occur every time and at first, I had trouble reproducing this bug locally.
To be more specific there is a case where we access some values like `requisitions.events` inside of the GSP templates and extract status and comment from it, and that's the place where the lazyInitializationException is being thrown.
To fix this issue I decided to just fetch the Requisition again in the event handler instead of relying on the requisition passed in the `RequisitionStatusTransitionEvent`.
Wrapping the method with `Requisition.withSession` didn't help btw.
```
Requisition.withSession {
if (requisition.shouldSendApprovalNotification()) { …
```

OBPIH-5984 Fix lazyInitialization issue when building approval emails

---

grails-app/conf/application.yml
grails-app/init/org/pih/warehouse/BootStrap.groovy

Brought back changes lost in the rebase for the migration from https://github.com/openboxes/openboxes/commit/274c38b8f0d2d66db9222a18b27f2dbde8cea0cc
The changes aren't too big since it mostly involved moving some code in appropriate methods and calling them on init.
Besides some differences with new code that we had implemented in the mean time, in the old commit I noticed
```
log.info("Starting Quartz scheduler ...")
Scheduler scheduler = grailsApplication.mainContext.getBean("quartzScheduler")
scheduler.start()
```
I have omitted this chunk of code since we have configured `autoStartup: true` in the `application.yml` and from what I gathered it means that we don't have to call start on quartzScheduler manually since it will be started for us on startup.

OBGM-503 Bring back changes to bootstrap.groovy that were reverted during reabse

---

grails-app/services/org/pih/warehouse/data/PersonDataService.groovy

The issue is that somehow in the database there was a user which had an extra space in it's **firstname** column value like
```
firstname: "name ",
lastname: "lastname"
```
I don't know how that extra space appeared there, because I tested creating _Person/User_ in the UI and via import and in both cases it clears the extra white space, the only way I was able to reproduce it is updating the value directly in the database.
When exporting the PO items excel it exports the users value with that extra space "name  lastname"  _(there are two spaces in between)_ and trying to re-import the same file causes the system to not find the set user because when we do `split(" ")` it splits by the first space and now we are looking for users with a combo firstname and last name 
`[ firstname: "name", …

OBPIH-5972 trim white space from firstname and last name when binding user to recipient on PO items import

---

grails-app/init/org/pih/warehouse/BootStrap.groovy

The description / Question is moved to the [ticket](https://pihemr.atlassian.net/browse/OBGM-130?atlOrigin=eyJpIjoiMjI4M2FiN2IwMTlkNDkwZjliMmQ0NWRmZWNiNWFhZDAiLCJwIjoiaiJ9)

OBGM-130 Refactor database migration trigger in BootStrap.groovy to avoid having to update list of existing versions

---

grails-app/services/org/pih/warehouse/data/PersonService.groovy

Reverts openboxes/openboxes#4384

Revert "OBPIH-5972 trim white space from firstname and last name when binding user to recipient on PO items import"

---

grails-app/domain/org/pih/warehouse/invoice/InvoiceItem.groovy

when performing the validation on invoiceItem without shipmentItem attached
```groovy
Boolean isValid = quantity + (shipmentItem?.quantityInvoiced - originalQuantityInvoiced) <= shipmentItem?.quantity
```
Above code would throw an exception since we are trying to subtract a number from `null` (where null is shipmentItem?.quantityInvoiced)

OBGM-750 Fix validation on InvoiceItem quantity when invoiceItem does not have a shipmentItem associated

---

grails-app/controllers/org/pih/warehouse/core/LocationController.groovy

When creating a new location the `locationInstance.supportedActivities` is null.

OBGM-752 Supported activities of location type are not assigned by default when create location on grails pages 

---

grails-app/controllers/org/pih/warehouse/UrlMappings.groovy
grails-app/controllers/org/pih/warehouse/api/SelectOptionsApiController.groovy

Before @jmiranda resolves his spike related to the select options api convention, I used generic api `getList` even though we don't like it, just to avoid throwing my own convention with a service method, before you are back and because it is enough for now, to be able to proceed with the further work.

OBPIH-6033 Add endpoint to fetch preference type options

---

grails-app/controllers/org/pih/warehouse/UrlMappings.groovy
grails-app/controllers/org/pih/warehouse/api/ProductSupplierApiController.groovy
grails-app/services/org/pih/warehouse/data/ProductSupplierService.groovy
src/js/api/urls.js

It seems not to be necessary to add a url mapping for this (and it was not necessary to add it for the list method), as it's handled fine by the generic mappings:
```groovy
"/api/${resource}s"(parseRequest: true) {
controller = { "${params.resource}Api" }
action = [GET: "list", POST: "create"]
}
"/api/${resource}s/$id/status"(parseRequest: true) {
controller = { "${params.resource}Api" }
action = [GET: "status", DELETE: "deleteStatus", POST: "updateStatus"]
}
"/api/${resource}s/$id"(parseRequest: true) {
controller = { "${params.resource}Api" }
action = [GET: "read", POST: "update", PUT: "update", DELETE: "delete"]
}
```
By doing so, I've also applied @jmiranda 's suggestion from [here](https://github.com/openboxes/openboxes/pull/4435#discussion_r1437925142) to change the url to be in …

OBPIH-6021 Add an API endpoint to delete a product supplier + remove unnecessary url mapping 

---

src/js/utils/apiClient.jsx

You can find an explanation of the problem in the ticket.

OBPIH-6080 Fix displaying a toast message while connection is restored

---

src/js/components/form-elements/FilterSelectField.jsx

The point was to re-create the dropdown and its width when the options change, because before for the async select, the width has never dynamically changed regarding the options that were loaded.
Thanks for pair programing @drodzewicz @alannadolny

OBPIH-6014 Fix async select dropdown to be wider for longer labels

---

src/main/groovy/org/pih/warehouse/api/StockMovement.groovy

add nullsafe operator for cases where stockMovement is not from requisition

OBPIH-5826 Approval comment indicator fix

---

src/js/components/returns/inbound/AddItemsPage.jsx

Same logic as for next page should be applied to previous page on inbound returns

OBPIH-5932 Add validation to lot expiration date update when user clicks previous button on inbound returns

---

grails-app/domain/org/pih/warehouse/core/Organization.groovy
grails-app/services/org/pih/warehouse/core/OrganizationService.groovy

- added blank GORM validators to prevent from inserting empty string values
- added a consdition to search for exsiting organization by code and name which are not empty strings

OBGM-753 Empty string validation on name and code of organization

---

src/js/components/form-elements/v2/DateField.jsx
src/js/components/form-elements/v2/DateFieldInput.jsx
src/js/components/form-elements/v2/TextInput.jsx
src/js/components/form-elements/v2/style.scss
src/js/consts/timeFormat.js
src/js/wrappers/style.scss

Current styling of the date component:

OBPIH-6100 Create a reusable Date component

---

grails-app/i18n/messages.properties
grails-app/services/org/pih/warehouse/invoice/InvoiceService.groovy
src/js/api/services/InvoiceApi.js
src/js/api/urls.js
src/js/components/invoice/AddItemsPage.jsx

The most important part I would say is located in the `InvoiceService`.
To have the same behavior as we have in inbounde/outbound stockMovements I had to add additional logic that would eliminate invoiceItems with quantity == 0.
- Additionally it was preventing user from going forward if there are no items in the add items page table.
- Adding a confirmation modal with message that there are zeros in your rows and will be deleted.
- And I also used this opportunity to move some hardcoded services to `invoiceApi` like `getInvoiceItems`, `removeItems` and `saveInvoiceitems`

OBPIH-6052 validation for zero items to invoice in invoices workflow

---

src/js/components/form-elements/v2/Checkbox.jsx
src/js/components/form-elements/v2/style.scss
src/js/wrappers/InputWrapper.jsx
src/js/wrappers/style.scss

There are two modifications to the input wrapper
first, since this checkbox component has the label on it's right side I added a _modified_ to the InputWrapper to have the ability to position this label top, bottom, left and right so it would be much more reusable to future form components.
I have also added a `<label />` tag and attributes `htmlFor` and `ids` for better semantics. This will help us target these input elements for automated testing so this change is required.

OBPIH-6102 Create reusable checkbox  form component

---

docs/installation/ubuntu1804/deployment.md

Updated file name for log file - /opt/tomcat is a symlink to whatever version of tomcat got installed, so /opt/tomcat/tomcat-<version> does not make sense - corrected by removing extraneous component.
Also fixed documentation bug where java path ended up incorrect.

Minor bugs in documentation

---

src/js/components/productSupplier/create/ProductSupplierForm.jsx
src/js/components/productSupplier/create/ProductSupplierFormMain.jsx
src/js/components/productSupplier/create/sections/PricingSection.jsx
src/js/components/productSupplier/create/subsections/PackageSpecification.jsx
src/js/hooks/productSupplier/form/useProductSupplierForm.js

The bug has been introduced by this commit: https://github.com/openboxes/openboxes/pull/4524/commits/ad702489c329c9893e48f8b3af3460c1a05d78e5
When editing a source, the product package quantity was cleared (set to `undefined`) after initialization of default values of the product source.
It was due to two `useEffects` impacting on each other - at first we were setting the default values in `getDefaultValues` method, and since the `uom` was also set, it triggered the `useEffect` that was eventually setting the product package quantity to `undefined`.
This `useEffect` would be OK, but if it was triggered only for manual editing of the `uom`- since we can't distiungish whether it has been run manually or by the `uom` change of the `getDefaultValues`, I refactored this to be a method that is …

OBPIH-6111 Fix substitution and calculation of each price

---

src/js/components/form-elements/v2/DateField.jsx
src/js/components/productSupplier/create/ProductSupplierFormMain.jsx
src/js/components/productSupplier/create/sections/AttributesSection.jsx
src/js/components/productSupplier/create/sections/DetailsSection.jsx
src/js/components/productSupplier/create/sections/PreferenceTypeSection.jsx
src/js/components/productSupplier/create/sections/PricingSection.jsx
src/js/components/productSupplier/create/subsections/AdditionalDetails.jsx
src/js/components/productSupplier/create/subsections/BasicDetails.jsx
src/js/components/productSupplier/create/subsections/DefaultPreferenceType.jsx
src/js/components/productSupplier/create/subsections/FixedPrice.jsx
src/js/components/productSupplier/create/subsections/PackageSpecification.jsx
src/js/components/productSupplier/create/subsections/PreferenceTypeVariations.jsx
src/js/hooks/productSupplier/form/useCalculateEachPrice.js
src/js/hooks/productSupplier/form/useProductSupplierForm.js
src/js/hooks/productSupplier/form/useProductSupplierValidation.js
src/js/utils/propTypes.js

There is a bit of a refactor that I did on the validation schema that allowed me to add a custom `refine()` validation on the whole section.
Additionally, I believe that separating our validations schema into smaller subsections will be a lot more readable and maintainable. I believe we already talked about this and since there aren't any tickets that will have conflicts with these changes Id decided to proceed with this refactor.
**So what has changed?**
- I have split all of the fields in the validations schema into smaller subsections just like we have in the UI and imported them in the main schema
```jsx
z
.object({
id: z
.string()
.optional(),
basicDetails: basicDetailsSchema,
additionalDetails: additionalDetailsSchema,
defaultPreferenceType: defaultPreferenceTypeSchema, …
```

OBPIH-6108 Default Preference Type section (fixes after QA)

---

grails-app/views/product/_productSuppliers.gsp
grails-app/views/productSupplier/list.gsp

I looked through the whole project and one other case where `defaultProductPackage` was used instead of `defaultProductPackageDerived` was on old sources list page.
I decided to also fix that because I am not sure about the future of these files, should they be deleted since we have a working react list page for sources already?

OBPIH-6253 Fixed regression on defaultProductPackage on show page and old list page

---

src/main/groovy/org/pih/warehouse/api/StockMovement.groovy

This method has been missing in the `StockMovement` dto. It has been available only in the `OutboundStockMovement`. The problem was, that when we access the SM show page from the list page, we access it via requisition id (OutboundStockMovement id). 
When we were uploading documents, we were redirected to the SM page, but using the **shipment's id**, hence we were evaluating some stuff from the `StockMovement` dto, not `OutboundStockMovement`, and since this method had been missing, we were getting an exception.

OBPIH-6249 Fix upload of documents to e-requests

---

grails-app/services/org/pih/warehouse/order/OrderService.groovy

The issue that was discovered during QA was that productPackage would not be updated when creating a new product source through manual edit or import on PLACED Purchase Order.
Few things I modified are:
first I added an additional condition on edit `productSupplierChanged` which just like other conditions checks if product Source of the orderItem is the same as the one provided by the package.
Then secondly, after investigating the whole workflow I cam to the conclusion that the chunck of code 
```groovy
// If not found, then we look for a product package associated with the product
if (!productPackage) {
productPackage = orderItem.product.packages.find { ProductPackage productPackage1 ->
return productPackage1.product == orderItem.product &&
productPackage1.uom == orderItem.quantityUom …
```

OBPIH-6253 source pricing not visible when adding new product source on placed PO (manual and import)

---

grails-app/controllers/org/pih/warehouse/product/ProductController.groovy

The issue at first was difficult to spot, as the error had been throwing in the generic `transformObjects` method in the `DataService` and it is working fine on Grails 1.
It turned out, that this line:
```groovy
List<Map> objects = [[]]
```
caused the problem, as the `transformObjects` method, and this particular line:
```groovy
value = object.get(element) ?: element.tokenize('.').inject(object) { v, k -> v?."$k" }
```
expects to run the `.get` method on a `Map`, not on a `List`. This variable is even declared as `List<Map>`, but the default value for that is `[[]]`, so "list inside the list", not map inside the list.
To fix that issue I just changed the `[]` to `new HashMap<>()`, not to refactor the generic method in the `transformObjects`, as in my opinion, it should also work when the …

OBPIH-6324 Fix downloading the product synonyms import template

---

grails-app/domain/org/pih/warehouse/requisition/RequisitionItem.groovy
grails-app/views/requisition/_showRequisitionItem.gsp
src/test/groovy/unit/org/pih/warehouse/requisition/RequisitionItemSpec.groovy

I decided to avoid modifying the original function for getting statuses because it can introduce regression (as I saw it was in calculating line items in requisition, in this case, we based on our previous "APPROVED" status)

OBPIH-5813 Items statuses before fulfilment - Approvals statuses

---

grails-app/domain/org/pih/warehouse/inventory/OutboundStockMovementListItem.groovy
grails-app/migrations/views/stock-movement-list-item.sql
src/main/groovy/org/pih/warehouse/requisition/RequisitionStatus.groovy

… after state machine refactor + remove unused filters

OBPIH-6368 Fix statuses mapping on outbound list page while filtering after state machine refactor + remove unused filters

---

src/css/main.scss

Since there are some random behaviors in the placement of the crowdin modal, I've overwritten the style that is responsible for that behavior and made the crowdin modal always appear in the same place.

OBPIH-6422 Change the placement of crowdin's login modal

---

.github/release.yml
.github/templates/release-notes-template.md
.github/workflows/do-release.yml

JIRA Ticket: https://pihemr.atlassian.net/browse/OBPIH-6388
Discovery Document: https://pihemr.atlassian.net/wiki/spaces/OB/pages/3056828417/DISCOVERY%3A+OBPIH-6388+Investigate+new+CI+solution
Adds a new GitHub Action that auto-generates the release notes whenever a new tag is pushed to the repo.
Notes:
- only runs if the tag starts with "vX.Y.Z" (Ex: 0.9.2, 0.9.2-hotfix...)
- The action can also be run manually in case it fails for any reason.
- If the job is re-run, it will replace the existing artifacts in the release
An example of running the Action manually:
The release notes that are auto-generated once the action completes:

OBPIH-6388 github action for autogenerating release notes on new tag

---

build.gradle
grails-app/conf/application.yml
src/integration-test/groovy/org/pih/warehouse/component/base/ApiSpec.groovy
src/test/resources/testcontainers/my.cnf

The bulk of the leg work to get testcontainers set up was done by Justin, this is just to actually hook it up.
There's two methods of wiring up the test database to use testcontainers. You can do it directly via jdbc url, or via annotations. I chose via url because it's the smallest change, it automatically picks up the db config we have set in application.yml, and it immediately applies to all integration tests without issue.
More info here: https://java.testcontainers.org/modules/databases/jdbc/
If we wanted to do it the annotation way, it'd look something like this:
```
@Testcontainers
class Test extends Specification {
@Shared // Marking it shared allows us to preserve the database across tests.
MySQLContainer mySQLContainer = new MySQLContainer(DockerImageName.parse("mysql:5.7")) …
```

OBPIH-6387 Run MySQL in a testcontainer for integration tests

---

grails-app/conf/runtime.groovy
grails-app/i18n/messages.properties
grails-app/services/org/pih/warehouse/dashboard/IndicatorDataService.groovy
src/js/actions/index.js
src/js/components/dashboard/ColorPalette.scss
src/js/components/dashboard/Dashboard.scss
src/js/components/dashboard/NumbersTableCard.jsx
src/js/components/dashboard/TableCard.jsx
src/js/consts/dataFormat/customGraphConfig.jsx
src/main/groovy/org/pih/warehouse/dashboard/TableData.groovy

Things added after Manon's request:
- colours: green (1 shipment) > blue > orange > red (4+)
- instead of "4 or more shipments", just "4 or more"
- hyperlink the shipment IDs and the product codes
- date format: should be 31-Aug-2021
- narrowing columns

OBPIH-6328 Dashboard indicator for items with backdated shipments (disable string truncation)

---

grails-app/controllers/org/pih/warehouse/picklist/ImportPickCommand.groovy
grails-app/i18n/messages.properties
grails-app/services/org/pih/warehouse/inventory/StockMovementService.groovy
src/main/groovy/org/pih/warehouse/api/StockMovementItem.groovy

This PR was created to fix some points mentioned in #4650 
As you can see it's not so straightforward to add a validation of type (not a number) on a quantity, let me explain.
So the case is that a user uploads a file with a potential "invalid" quantity number.
We want our API to process this data and return to the user all of the errors that come up in the File.
Now if we set **quantity** as a type _Integer_, we lose the ability to even get to the custom validators because it will throw an exception something along the lines of `Can't cast String to an Integer` in constructor when assigning `this.quantity = quantity`, which is why I changed the type of the quantity so we can assign the quantity and then our validator can validate the value.
Additionally, I have added a …

OBPIH-6365 Add validation on quantity field

---

grails-app/i18n/messages.properties
src/js/components/stock-movement-wizard/outboundImport/OutboundImport.jsx
src/js/components/stock-movement-wizard/outboundImport/sections/OutboundImportDetails.jsx
src/js/components/stock-movement-wizard/outboundImport/subsections/OutboundImportSendingOptions.jsx
src/js/hooks/outboundImport/useOutboundImportForm.js
src/js/hooks/outboundImport/useOutboundImportValidation.js
src/js/utils/form-utils.jsx

- origin is filled by default with the current location
- date shipped validation (can't be date from the past)
- expected delivery date validation (can't be before the date shipped)

OBPIH-6329 Full outbound import - Details step (Fixes after QA)

---

grails-app/conf/application.yml
grails-app/controllers/org/pih/warehouse/api/ApiController.groovy
grails-app/controllers/org/pih/warehouse/api/LocalizationApiController.groovy
grails-app/controllers/org/pih/warehouse/core/LocalizationController.groovy
grails-app/controllers/org/pih/warehouse/user/UserController.groovy
grails-app/i18n/messages.properties
grails-app/i18n/messages_es_MX.properties
grails-app/services/org/pih/warehouse/core/LocalizationService.groovy
grails-app/services/org/pih/warehouse/core/UserService.groovy
grails-app/services/org/pih/warehouse/importer/ProductSynonymImportDataService.groovy
grails-app/services/org/pih/warehouse/product/ProductService.groovy
grails-app/taglib/org/pih/warehouse/SelectTagLib.groovy
grails-app/utils/org/pih/warehouse/LocalizationUtil.groovy
grails-app/views/admin/showSettings.gsp
grails-app/views/common/_footer.gsp
grails-app/views/user/create.gsp
grails-app/views/user/edit.gsp

"Some" context https://pihemr.atlassian.net/browse/OBPIH-6410?focusedCommentId=153567

OBPIH-6410 Allow configuring country specific localization

---

.github/workflows/on-change.yml
.github/workflows/slack-notifier.yml

Jira ticket: https://pihemr.atlassian.net/browse/OBPIH-6455
When the onchange job (https://github.com/openboxes/openboxes/actions/workflows/on-change.yml) fails, send a slack notification to the #build-status channel so that we can immediately be alerted to the failure.
I've tested the job already in a fork of the repo and it outputs the following:
Mainly this review is to see if there's any other info that you'd like included in the message

[OBPIH-6455] slack notification when github onchange job fails

---

grails-app/services/org/pih/warehouse/inventory/StockMovementService.groovy

This service function is executed on the import picklist controller, which should not mark the requisition item as `autoAllocated=true`.
In the import of picklist Items we have a case where we find the exact candidate and proceed with it or otherwise we don't find it, and the system tries to infer the candidate based on for example inventory item (eg. user provides only lot number).
Previously I mistakenly set this as `isAutoAllocated = true` which is not true for this case.

OBPIH-6558 Do not mark inferred items as auto allocated

---

grails-app/services/org/pih/warehouse/inventory/StockMovementService.groovy

This is a clone PR of https://github.com/openboxes/openboxes/pull/4740 because the former one was accidentally merged to develop.

OBPIH-6558 Do not mark inferred items as auto allocated (#4740)

---

grails-app/services/org/pih/warehouse/stockTransfer/StockTransferService.groovy

The issue here was an incomplete criteria on Product Avaialability lookup.
So there was a case where a single product had two similar Product Availability records in two different locations.
The similarity is in binLocation being `DEFAULT` and lotNumber being exact same as in the previous location.
So when we did a lookup
```groovy
ProductAvailability pa = ProductAvailability.findByInventoryItemAndBinLocation(stockTransferItem.inventoryItem,
```
it would find the first best one and return it, so doing an internal transfer on location `A` we would get quantity of location`B`, but when doing a transfer in location `B` we could have receive a correct one because it happens that the order of ProductAvaialability had quantity from location `B` first.
To fix this I just needed to fix the query …

OBPIH-6548 Fix wrong product availability data lookup on internal stock transfer

---

grails-app/controllers/org/pih/warehouse/core/DocumentController.groovy

This is a fix to the change I made recently. Apparently I have missed the case for uploading documents without specified document types, so when checking  `if (!nonTemplateDocumentTypes.contains(null))` it would fail on this step since null is not a part of nonTemplateDocumesTypes
I decided to go a little different route this time and instead of fetching all of the document Types with template document codes I figured we can just check if the document type that we are applying has a template document code

OBPIH-6577 Prevent only document types with template document codes to be uploaded on stockmovement, shipment, po and invoice add document endpoint

---

grails-app/controllers/org/pih/warehouse/api/PurchaseOrderApiController.groovy
grails-app/domain/org/pih/warehouse/order/Order.groovy
grails-app/domain/org/pih/warehouse/order/OrderAdjustment.groovy
grails-app/domain/org/pih/warehouse/order/OrderItem.groovy
grails-app/domain/org/pih/warehouse/shipping/ShipmentItem.groovy
grails-app/services/org/pih/warehouse/invoice/InvoiceService.groovy
src/js/components/invoice/ConfirmInvoicePage.jsx
src/test/groovy/unit/org/pih/warehouse/order/OrderSpec.groovy

https://pihemr.atlassian.net/browse/OBPIH-6497
This is a fix to issues found during QA. Turned out that we had a few places that were mixing up quantities in UoM and quantities in standard UoM. 
---
---
> *Please confirm and check each of the following to ensure that your change conforms to the coding standards of the project:*

OBPIH-6497 Fix comparing invoice quantities in UoM and in standard Uom

---

src/js/components/DataTable/DateCell.jsx
src/js/components/stock-movement-wizard/outboundImport/subsections/OutboundImportItems.jsx

**Link to GitHub issue or Jira ticket:** [OBPIH-6624](https://pihemr.atlassian.net/browse/OBPIH-6624)
This is a small UI change where we want to display an empty cell instead of a default value which is a `"-"`. I noticed that on `DateCell` components we do not have a customizable prop for this value so I implemented it and made appropriate changes to the Full outbound workflow table expiration date column
---
> *If this PR contains a UI change, consider adding one or more screenshots here or link to a screen recording to …

[OBPIH-6624] Default value on DateCell Component

---

grails-app/services/org/pih/warehouse/invoice/PrepaymentInvoiceService.groovy

https://pihemr.atlassian.net/browse/OBPIH-6499
Fix for the issue found during QA (If there will be created dangling item due to transactional it will be saved as an orphan and an error is thrown. There is need to change ordering to avoid this issue - first check if there is quantity to inverse and then create inverse item)
---
> *We require that all code changes come paired with a method of testing them. Please select which of the following testing approaches you've included with …

OBPIH-6499 Do not create inverse if no quantity to inverse

---

grails-app/domain/org/pih/warehouse/order/OrderItem.groovy
grails-app/views/order/_itemStatus.gsp

**Link to GitHub issue or Jira ticket:** [OBPIH-6659](https://pihemr.atlassian.net/browse/OBPIH-6659)
Issue was that when user would generate a partial invoice but "save & exit" instead of posting, it would display invoiced quantity on Item statuses. The expected behavior is that the quantity invoiced should display only after the the invoice has been posted
---
> *If this PR contains a UI change, consider adding one or more screenshots here or link to a screen recording to help reviewers visualize the change. Otherwise, …

[OBPIH-6659] Display quantity of invoiced items only after invoice has been posted

---

grails-app/services/org/pih/warehouse/invoice/PrepaymentInvoiceService.groovy

https://pihemr.atlassian.net/browse/OBPIH-6644
When an order item had quantity reduced after making a prepayment, then it was not fully inversed. There was a need for a fix while calculating inverse quantity to take a look if the ordered item is both fully shipped and fully invoiced, and then add inverse item with quantity available to inverse.
---
According to reproduction steps
---

OBPIH-6644 Fix calculating inverse item after reducing ordered quantity

---

grails-app/controllers/org/pih/warehouse/order/OrderController.groovy

https://pihemr.atlassian.net/browse/OBPIH-6636
The order summary materialized view was not refreshing when the order items quantity was edited.
---
According to the reproduction steps
---

OBPIH-6636 Trigger order summary refresh after editing existing item quantity

---

src/main/groovy/org/pih/warehouse/outbound/ImportPackingListItem.groovy

The query was missing an additional condition which was the origin location for Product Availability.
Without it, it would search for all PA in all available locations.
Additionally retuned lotNumber from inventory Item object because there is a difference in displaying these values.
InventoryItem object for default lot number has lotNumber as null while the property on ProductAvailability has a string value "DEFAULT".
QA requested to unify this display as in other similar places …

[OBPIH-6516] [Fix after QA] Add origin location to Product Availability search condition

---

grails-app/domain/org/pih/warehouse/core/Person.groovy

**Link to GitHub issue or Jira ticket:** [OBPIH-6673](https://pihemr.atlassian.net/browse/OBPIH-6673)
After #4829 was merged there was a typo in `searchTerm` variable or rather a wrong variable was used as an argument in a query search.
---
[OBPIH-6673]: https://pihemr.atlassian.net/browse/OBPIH-6673?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVm …

[OBPIH-6673] Fix searchTerm variable typo on Person search method

---

grails-app/migrations/0.9.x/changelog-2024-08-20-0000-migrate-prepayment-invoices-add-amount-and-inverse-items.groovy
grails-app/services/org/pih/warehouse/invoice/PrepaymentInvoiceMigrationService.groovy
src/test/groovy/unit/org/pih/warehouse/invoice/PrepaymentInvoiceMigrationServiceSpec.groovy

**Link to GitHub issue or Jira ticket:** https://pihemr.atlassian.net/browse/OBPIH-6612
**Description:** When migrating existing prepayment invoices, we need to also set the amount field for any existing final invoice items so that the "Total Price" column displays correctly when viewing the final invoice.

[OBPIH-6612] BUGFIX: set amount field when migrating existing final prepayment invoice items

---

src/main/groovy/org/pih/warehouse/outbound/ImportPackingListItem.groovy

**Link to GitHub issue or Jira ticket:** https://pihemr.atlassian.net/browse/OBPIH-6676
There was a case where user provided a non existing binLocation and as a result the expiration date for existing lot was not populated. To fix this issue I just changed the order of the validation and if the inventoryItem existing then bind the expiration date and only after that we validate for bin location
---
> *If this PR contains a UI change, consider adding one or more screenshots here or link to a screen recording to help …

OBPIH-6676 Fix binding of inferred lot expiration date

---

src/js/hooks/outboundImport/useOutboundImportForm.js

**Link to GitHub issue or Jira ticket: https://pihemr.atlassian.net/browse/OBPIH-6675?atlOrigin=eyJpIjoiZDA1OTBlNmVjN2U5NDk5ZmFhOGY1YWE3MmFkMmYwOTMiLCJwIjoiaiJ9**
The problem here was that the cached data was cleared, but two `useEffects` were affecting themselves, hence before they were cleared, the cached data was sent for validation, as it was not empty yet.
To fix that, we want to load the cached data only if we are on the confirm step.

OBPIH-6675 Errors cached despite leaving outbound import workflow

---

src/main/groovy/org/pih/warehouse/outbound/ImportPackingListItem.groovy

**Link to GitHub issue or Jira ticket:** [OBPIH-6679](https://pihemr.atlassian.net/browse/OBPIH-6679)
The use case describes a scenario where user did not provide a bin location in the packing list document but provided a lot number, so based on the provided lot nuymber we want to infer the bin location only in cases where there is a single possible bin location for provided lot number
---
> *If this PR contains a UI change, consider adding one or more screenshots here or link to a screen recording to help reviewers …

[OBPIH-6679] inferring bin in packing list import based on lot number

---

src/js/hooks/invoice/useInvoicePrepaidItemsTable.jsx

**Link to GitHub issue or Jira ticket:** https://pihemr.atlassian.net/browse/OBPIH-6690
**Description:** This PR is a fix for disabling buttons while we have not fully prepaid invoices.

OBPIH-6690 Add option to edit unit price on invoice items made from order adjustments (fix after QA)

---

src/js/components/invoice/create/ConfirmInvoicePage.jsx
src/js/hooks/invoice/useConfirmInvoicePage.jsx
src/js/hooks/invoice/useInvoicePrepaidItemsTable.jsx

**Link to GitHub issue or Jira ticket:** https://pihemr.atlassian.net/browse/OBPIH-6716
The first fix was to use a map as it is mentioned in the docs:
> InfiniteLoader is not a stateful component, meaning that it does not keep track of which rows it has requested to be loaded. Your component will need to track this information yourself to avoid loading rows multiple times. One way to do this is to to use a map to track the status of each row like so ...
The second fix is to allow react-virtualize to fetch the number of items that the table needs. Previously we were fetching only 10 items each time. So in case of quick scrolling, we missed some items.

OBPIH-6716 Sorting issue on invoice confirm page for long list of items 

---

src/main/groovy/org/pih/warehouse/outbound/ImportPackingListItem.groovy

**Link to GitHub issue or Jira ticket:** [OBPIH-6679](https://pihemr.atlassian.net/browse/OBPIH-6679)
**Description:** Had to modify the inferring bin location logic a bit due to following problem.
- inferring would work on out of stock bins, which is why I had to sue the product availability service which handles this search properly
- Were some issues with inferring default bin location
- providing a wrong bin location with correct lot would result in the algorithm trying to infer the bin location based on lot which we do not want in …

OBPIH-6679 Fix inferring bin location when providing a lot number

---

src/js/components/invoice/create/InvoicePrepayedItemsTable.jsx
src/js/hooks/invoice/useConfirmInvoicePage.jsx

**Link to GitHub issue or Jira ticket:** https://pihemr.atlassian.net/browse/OBPIH-6716
The issue was caused by the behavior of fetching implemented in react-virtualize - the stop index passed by the react table when deleting an item is 10 (our default page size). So when we deleted an item in the middle of the table, the react-virtualize started fetching the items again, and the sent requests were: (startIndex: 0, stopIndex: 10), and the next one is, for example (startIndex: 16, stopIndex: 40). So because of that we are missing 6 items, and then when scrolling through the table we are fetching those missing items, and they are placed at the end of the table when we are on their indexes. Our implementation of the react-virtualize causes it so it's better not to touch the …

OBPIH-6761 Sorting issue on invoice confirm page for long list of items (fix after QA)

---

grails-app/domain/org/pih/warehouse/invoice/InvoiceItem.groovy
grails-app/domain/org/pih/warehouse/order/OrderAdjustment.groovy
grails-app/services/org/pih/warehouse/invoice/PrepaymentInvoiceService.groovy
src/js/hooks/invoice/useInvoicePrepaidItemsTable.jsx
src/test/groovy/unit/org/pih/warehouse/invoice/PrepaymentInvoiceServiceSpec.groovy
src/test/groovy/unit/org/pih/warehouse/order/OrderAdjustmentSpec.groovy

https://pihemr.atlassian.net/browse/OBPIH-6689
This is basically a changing approach to determining inverse items. Previously we were relying on the amount field, which while comparing to unit prices could have different sign and could be reduced by prepayment percentage. To simplify things we should always rely on the unit price all the time while determining inverse items.

OBPIH-6689 Rely on unit price instead amount while calculating inverse items

---

grails-app/domain/org/pih/warehouse/invoice/InvoiceItem.groovy
grails-app/services/org/pih/warehouse/invoice/PrepaymentInvoiceMigrationService.groovy
grails-app/services/org/pih/warehouse/invoice/PrepaymentInvoiceService.groovy
src/test/groovy/unit/org/pih/warehouse/invoice/PrepaymentInvoiceMigrationServiceSpec.groovy

**Link to GitHub issue or Jira ticket:** https://pihemr.atlassian.net/browse/OBPIH-6726
**Description:** See ticket for the full breakdown. This fix is to ensure that when migrating existing invoices we're properly creating an inverse invoice item for each matching *shipment* item in a regular invoice. Previously we were only checking the prepayment invoice item, which is based on *order item* and so had no shipment association. This worked fine for cancelled items and adjustments, but for orders with shipments, the invoice needs to be …

OBPIH-6726 Bugfix to allow pre-migration prepayment invoices to be edited

---

grails-app/services/org/pih/warehouse/fulfillment/FulfillmentService.groovy
grails-app/services/org/pih/warehouse/inventory/ProductAvailabilityService.groovy
src/main/groovy/org/pih/warehouse/outbound/ImportPackingListItem.groovy
src/test/groovy/unit/org/pih/warehouse/fulfillment/FulfillmentServiceSpec.groovy
src/test/groovy/unit/org/pih/warehouse/fulfillment/InferringOutboundImportValuesSpec.groovy

**Link to GitHub issue or Jira ticket:** [OBPIH-6747](https://pihemr.atlassian.net/browse/OBPIH-6747)
The inferring bin Location and lot number required a bit of a refactor, I decided to move many parts into standalone service methods for better maintainability and readability because this feature has grown a bit.
Additionally since  there are many different inferring/binding scenarios I am working on implementing tests for these methods
---
> *If this PR contains a UI change, consider adding one or more screenshots here …

OBPIH-6747 support empty lot number in import that matches inventory item defined as null

---

grails-app/migrations/views/order-summary-helper-views.sql

**Link to GitHub issue or Jira ticket:** https://pihemr.atlassian.net/browse/OBPIH-6691
This reopen was due to the following behavior:
- Create PO, add an item, and adjustment with a percentage value for that item
- Generate prepayment invoice 
- Generate final invoice for adjustment
- Edit unit price/qty of the item to lower value
- Generate final invoice pending value difference for adjustment
- Ship item
- Generate invoice for item
See that status remains Partially Invoiced. 
This issue was caused by the fact, that if we are editing an order item that is bound with order adjustment we have to invoice the value difference, which is a negative value, but the value of the adjustment is positive. After summing the absolute amount values for the order we had, for example:
- …

OBPIH-6691 Add partially invoiced order summary status for order adjustments

---

src/js/components/stock-movement-wizard/combined-shipments/AddItemsPage.jsx

**Link to GitHub issue or Jira ticket:** [OBPIH-6225](https://pihemr.atlassian.net/browse/OBPIH-6225)
QA releaved a bug where the UoM label was not visible when splitting the line
---
[OBPIH-6225]: https://pihemr.atlassian.net/browse/OBPIH-6225?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cif …

OBPIH-6225 Include UoM when splitting the line

---

src/js/components/form-elements/BaseField.jsx

**Link to GitHub issue or Jira ticket:** [OBPIH-6698](https://pihemr.atlassian.net/browse/OBPIH-6698)
After some recent changes to the receiving workflow it appears that props `label` and `defaultMessage` were not properly passed to the BaseField component when passing them through dyanmicAttributes which broke the test because screen reader was not able to find the appropriate textfield when looking for Receving now field by label
---
> *If this PR contains a UI change, consider adding one or more screenshots here or …

OBPIH-6698 Include label and defaultMessage in base field componnt when props are passed as dynamic attributes

---

src/js/components/stock-movement-wizard/outbound/AddItemsPage.jsx

**Link to GitHub issue or Jira ticket:** /[OBPIH-6099](https://pihemr.atlassian.net/browse/OBPIH-6099)
**Description:** Issue was that on outbound workflow when autosave was enabled this globalr ecipient did not work propetly
Current autosave behacior only includes logic for individual edits on the row, since we are working with a "bulk" update I had to add some modifications like thi `editAll` prop
---
> *If this PR contains a UI change, consider adding one or more screenshots here or link to a screen recording to help reviewers …

OBPIH-6099 Fix issue with global recipient on outbound autosave

---

.github/workflows/backend-tests.yml
.github/workflows/on-change.yml
.github/workflows/test-pull-request.yml
build.gradle

**Link to GitHub issue or Jira ticket:** https://pihemr.atlassian.net/browse/OBPIH-6649
**Description:** Generates a code coverage report using Jacoco whenever tests are run and then uploads them to Codecov when commits are pushed to PRs or when PRs are merged to develop.
Codecov dashboard: https://app.codecov.io/gh/openboxes/openboxes/
And this is what the raw HTML Jacoco reports that codecov is built from look like (we probably won't use these much except for local testing):

OBPIH-6649 Add support for Jacoco code coverage reporting

---

.readthedocs.yaml

#4345 
Readthedocs integration has been failing on all branches derived from develop for a long time. That leads to a failing build check for every PR that gets created. 
Here's what the build on readthedocs looks like. 
We fixed the issue months ago, but it's on a long-lived feature branch (OBPIH-6197) aimed at updating our docs for the 0.9.x release. And unfortunately, those change have not been pushed to develop yet. 
So here we are. 
And here's a recent build of the current branch on readthedocs, showing that the changes allows builds to pass successfully.

Fix mkdocs build integration with readthedocs (fixes #4345)

---

grails-app/services/org/pih/warehouse/order/PurchaseOrderIdentifierService.groovy
src/main/groovy/org/pih/warehouse/core/identification/IdentifierGeneratorContext.groovy
src/test/groovy/unit/org/pih/warehouse/order/PurchaseOrderIdentifierServiceSpec.groovy

**Link to GitHub issue or Jira ticket:** https://pihemr.atlassian.net/browse/OBPIH-6821
**Description:** See ticket for details, but this PR fixes an issue where an organization's sequence number falls out of sync with the order numbers that we have generated for POs. Essentially the PR adds a retry mechanism where if the id we generate is not unique, check the next 10 sequence numbers if they're available.

OBPIH-6821 Try next sequence number if generating an order number fails

---

grails-app/conf/application.yml
grails-app/conf/logback-spring.xml
grails-app/controllers/org/pih/warehouse/SentryInterceptor.groovy
src/main/groovy/org/pih/warehouse/monitoring/SentryServletContextListener.groovy

**Link to GitHub issue or Jira ticket:** N/A
**Description:** Currently we see the following warning during startup when local testing:
`10:13:50,850 |-WARN in io.sentry.logback.SentryAppender[sentry] - Failed to init Sentry during appender initialization: DSN is required. Use empty string or set enabled to false in SentryOptions to disable SDK.`
This also causes logback to dump a whole bunch of other debug logs.
The fix sets a default value of empty string (which disables Sentry) for the dsn if the SENTRY_DSN_BACKEND or SENTRY_DSN …

Default to a blank dsn if sentry env vars are not set

---

grails-app/controllers/org/pih/warehouse/api/PurchaseOrderApiController.groovy
grails-app/jobs/org/pih/warehouse/jobs/RefreshOrderSummaryJob.groovy
grails-app/services/org/pih/warehouse/data/DataService.groovy
grails-app/services/org/pih/warehouse/order/OrderService.groovy
grails-app/services/org/pih/warehouse/order/OrderSummaryService.groovy
grails-app/services/org/pih/warehouse/order/RefreshOrderSummaryEventService.groovy
grails-app/views/order/_summary.gsp
grails-app/views/order/list.gsp
grails-app/views/order/show.gsp

https://pihemr.atlassian.net/browse/OBPIH-6839
I added OrderSummaryService which basically copies the queries from the order summary helper views (with only one difference, each of these now pulls data for a specific order ID). This OrderSummaryService is a temporary (or to be expanded) solution for performance issues with order summary helper views during fetching and reloading data. In the next iteration, we should migrate from using views to using queries and/or we should move these to stored procedures (imho we should get rid of the views and leave only the materialized views plus queries / stored procedures)

OBPIH-6839 Improve performance of order's derived status fetch and update

---

grails-app/services/org/pih/warehouse/data/PersonService.groovy
grails-app/services/org/pih/warehouse/order/OrderService.groovy
grails-app/services/org/pih/warehouse/shipping/CombinedShipmentService.groovy
grails-app/services/org/pih/warehouse/shipping/ShipmentService.groovy
src/test/groovy/unit/org/pih/warehouse/person/PersonServiceSpec.groovy

**Link to GitHub issue or Jira ticket:** https://pihemr.atlassian.net/browse/OBPIH-6825
**Description:** Because we don't enforce any uniqueness on name or email in our system for entries in the Person table, when fetching people by name and email, there's a chance we'll find more than one. When this happens, we simply pick the first one we get. This can cause inconsistent behaviour when we have two identical users, one active and one inactive.
This was uncovered in PO import but is relevant to all flows that fetch a single Person.
This …

OBPIH-6825 Prioritize active persons when fetching by name or email

---

grails-app/migrations/views/cycle-count-session.sql
grails-app/services/org/pih/warehouse/inventory/CycleCountService.groovy

**Link to GitHub issue or Jira ticket:** https://pihemr.atlassian.net/browse/OBPIH-6959
**Description:** When generating abcClass in cycle_count_session, first check if there's an inventory level defined for the product, and use abcClass from there. Otherwise fallback to the abcClass as defined in the product

OBPIH-6959 use ABC Class from inventory level in cycle count products list

---

src/js/hooks/cycleCount/useToResolveTab.jsx

OBPIH-6940 Adjust display of product name in cycle count tables to 2 rows only (to resolve tab)

---

grails-app/conf/application.yml
grails-app/controllers/org/pih/warehouse/api/StockMovementApiController.groovy
grails-app/init/org/pih/warehouse/BootStrap.groovy
grails-app/utils/org/pih/warehouse/DateUtil.groovy
grails-app/utils/org/pih/warehouse/databinding/DataBindingConstants.groovy
grails-app/utils/org/pih/warehouse/databinding/InstantValueConverter.groovy
grails-app/utils/org/pih/warehouse/databinding/LocalDateValueConverter.groovy
grails-app/utils/org/pih/warehouse/databinding/StringValueConverter.groovy
src/main/groovy/org/pih/warehouse/core/Constants.groovy
src/main/groovy/util/StringUtil.groovy
src/test/groovy/unit/org/pih/warehouse/utils/DateUtilSpec.groovy
src/test/groovy/unit/org/pih/warehouse/utils/databinding/InstantValueConverterSpec.groovy
src/test/groovy/unit/org/pih/warehouse/utils/databinding/LocalDateValueConverterSpec.groovy

**Link to GitHub issue or Jira ticket:** https://pihemr.atlassian.net/browse/OBPIH-6965
Add support for java.time.Instant and java.time.LocalDate data binding. With this change we can now use those data types in our Domain classes and DTO/Command objects. This is important because java.util.Date is functionally deprecated as of Java 8, so going forward we should stop using it if possible.
See my other PR for an example implementation that uses this change: https://github.com/openboxes/openboxes/pull/5022
This is based off [the discovery work I did on java.time in OBPIH-6916](https://pihemr.atlassian.net/wiki/spaces/OB/pages/3382542337/OBPIH-6916+Standardizing+datetime+parsing). I encourage you to read that if you want some background information on this change.

OBPIH-6965 add data binding support for java.time classes

---

grails-app/conf/application.yml

Fixed a long-standing bug with 0.9.x releases where the default configuration leads to a 404 error when rendering the default logo. See #5041 for more information.
This was tested locally using grails run-app, but I have not tested this as part of an actual deployment. If we encounter any issues with this approach, I'm going to hard-code the context path.

Default logo returns a 404 error (fixes #5041)

---

grails-app/conf/application.yml
grails-app/controllers/org/pih/warehouse/api/StockMovementApiController.groovy
grails-app/utils/org/pih/warehouse/DateUtil.groovy
grails-app/utils/org/pih/warehouse/databinding/DataBindingConstants.groovy
grails-app/utils/org/pih/warehouse/databinding/InstantValueConverter.groovy
src/main/groovy/org/pih/warehouse/core/Constants.groovy
src/test/groovy/unit/org/pih/warehouse/utils/DateUtilSpec.groovy
src/test/groovy/unit/org/pih/warehouse/utils/databinding/InstantValueConverterSpec.groovy

- https://pihemr.atlassian.net/browse/OBS-1831
- https://pihemr.atlassian.net/browse/OBS-1815
**Description:** This change switches the parsing of dateShipped and dateRequested fields during stock movements to use the new DateUtil.asDate method (with no SimpleDateFormat provided so that it uses the flexible format).
I also modified how the method works so that it uses the same DateTimeFormatter that we use when parsing a String to an Instant. That way it gets around the issue with parsing "MM/dd/yyyy" and defaulting to the local timezone (now it always uses UTC).
---

OBS-1831 Fix unparseable date: "01/01/2025 " exception during stock movements

---

grails-app/migrations/views/changelog.xml
grails-app/migrations/views/cycle-count-session.sql
grails-app/migrations/views/product-count-history.sql
grails-app/migrations/views/product-cycle-count-history.sql
grails-app/migrations/views/product-physical-count-history.sql
grails-app/migrations/views/product-receipt-history.sql
src/js/hooks/cycleCount/useAllProductsTab.jsx

Added views to calculate the last count date based on cycle count and product inventory transaction data. Last count date is being pulled into to the the cycle count session view and displayed on the All Product tab. 
The performance is still really bad for some locations, so I'm going to look into ways to make it faster.
https://pihemr.atlassian.net/browse/OBPIH-6939
TBD
> [!TIP]  
> For the best viewing experience while reviewing this code, I would recommend enabling **Unified view** and **Hide whitespace** 
> 
> ![image](https://github.com/user-attachments/assets/3a7029b0-2ba5-42ef-84e9-769eee7471a7)
> 
> Not doing this will make it very difficult to understand what's going on.

OBPIH-6939 Show minimum of cycle count date and inventory in Last Counted date column

---

grails-app/domain/org/pih/warehouse/inventory/CycleCountItem.groovy

**Link to GitHub issue or Jira ticket:** https://pihemr.atlassian.net/browse/OBPIH-6901
**Description:** Fix `CycleCountItem.getQuantityVariance()` so that it doesn't return null when either `quantityCounted` or `quantityOnHand` == 0
---
https://jam.dev/c/ed162de1-0420-4c82-839d-fcc395b7f185
[8581a846-4b1e-49e0-90d6-37d28346d590.webm](https://github.com/user-attachments/assets/bd6d3c7b-7f40-480b-b569-14a090c5fa56)

OBPIH- 6901 bugfix. Make QuantityVariance properly handle 0 quantity

---

grails-app/domain/org/pih/warehouse/inventory/CycleCount.groovy
grails-app/services/org/pih/warehouse/inventory/CycleCountService.groovy
src/test/groovy/unit/org/pih/warehouse/inventory/CycleCountProductAvailabilityServiceSpec.groovy

**Link to GitHub issue or Jira ticket:** https://pihemr.atlassian.net/browse/OBPIH-7074
**Description:** Follow up fix to https://github.com/openboxes/openboxes/pull/5125
Submitting a count with a custom item threw an error because we were adding to the customItemsOfLastCount list while looping through it:
```
for (CycleCountItem customCycleCountItem : customItemsOfLastCount) {
...
cycleCount.addToCycleCountItems(cycleCountItem)  // adds to customItemsOfLastCount. Errors!
}
```
I tested the following scenario:
- add custom item to count
- submit count
- start recount successfully, it has QoH == 0
and:
- add custom item to count
- submit count
- record stock, adding 20 quantity to the bin + lot of the custom item
- start recount successfully, it has QoH == 20

OBPIH-7074 bugfix. Prevent stack trace when adding to count items list within loop

---

grails-app/views/taglib/_globalSearch.gsp
grails-app/views/taglib/_globalSearchStatic.gsp

**Link to GitHub issue or Jira ticket:** https://pihemr.atlassian.net/browse/OBPIH-6994
**Description:** Currently when hovering over an item in the global search results the search input is replaced with that item's display text. My change prevents that (and preserves the original input)
---
an example of the undesired behaviour: https://jam.dev/c/f000d33d-c70c-41a3-b5fe-45cf2c3e3daf
[1482e703-66b1-4ba3-a3dc-7e168990678e.webm](https://github.com/user-attachments/assets/08636c0d-3a71-440d-8249-f6316bd1ae2a)

OBPIH-6994 don't auto fill global search input when hover over results

---

src/js/hooks/cycleCount/useInventoryValidation.js

**Link to GitHub issue or Jira ticket:** https://pihemr.atlassian.net/browse/OBPIH-7101
**Description:** The specific issue brought up here is triggered when an existing (non-custom) row has an expiry and you try to add a new, custom row for the same lot and expiry. The error is caused by the fact that InventoryItems use a custom date format which the frontend doesn't use when adding new rows.
`InventoryItem.groovy`:
```
Map toJson() {
[
...
"expirationDate" : expirationDate?.format("MM/dd/yyyy"),
...
]
}
```
So when we’re validating in `useInventoryValidation.checkDifferentExpirationDatesForTheSameLot`, we get rows that have the same date but in different formats, so it thinks they’re different and throws a validation error:
```
"03/03/2027"                 -> existing row returned from …
```

OBPIH-7101 fix unique expiration date validation

---

src/js/hooks/cycleCount/useInventoryValidation.js

**Link to GitHub issue or Jira ticket:** https://pihemr.atlassian.net/browse/OBPIH-7117
**Description:** When one or more custom rows have the same [bin + lot] as another row, display an error on both the bin and lot fields for that row. Previously we were just displaying the error on the bin field, which isn't present for facilities with bin disabled, and so the error wasn't visible.
---
For facility with bin location enabled:
For facility with bin location disabled:

OBPIH-7117 duplicate items error should also show on lot number field

---

grails-app/services/org/pih/warehouse/inventory/CycleCountTransactionService.groovy
src/test/groovy/unit/org/pih/warehouse/inventory/CycleCountTransactionServiceSpec.groovy

**Link to GitHub issue or Jira ticket:** https://pihemr.atlassian.net/browse/OBPIH-7096
**Description:** Force any adjustment transactions to always come after the product inventory transaction by setting the transaction date for the product inventory to be before the adjustment transaction date.
---
Before the change (adjustment comes first sometimes):
After (adjustment is always after):

OBPIH-7096 force adjustment transactions to be after product inventory ones

---

src/js/hooks/cycleCount/useInventoryValidation.js

**Link to GitHub issue or Jira ticket:** https://pihemr.atlassian.net/browse/OBPIH-7101
**Description:** Duplicate expiry date validation error was incorrectly triggering when two bins had the same lot and expiration date was null. https://jam.dev/c/1e1680e8-e3c6-44b9-994d-46d2b19af8e1
---
Fixed:

OBPIH-7101 FIX. Handle null when comparing expiration dates

---

grails-app/services/org/pih/warehouse/inventory/CycleCountService.groovy
src/js/hooks/cycleCount/useResolveStep.js

This PR fix not display the same items. It combines the first count **countIndex = 0** with the first recount **countIndex = 1** into one record, keeping details from both. Any extra **countIndex = 1** records for the same item stay separate, not merged together. So, if someone adds lots of the same item, you get one merged record plus the rest as individual ones
Here is proof that it works correctly: https://jam.dev/c/e0e97537-fc7c-4fc6-80cb-080315e35094
---
[//]: <> (If this PR contains a UI change, consider attaching one or more screenshots or recordings to help reviewers …

OBPIH-7122 Recount workflow validations

---

grails-app/domain/org/pih/warehouse/inventory/InventoryLevel.groovy
grails-app/domain/org/pih/warehouse/product/Product.groovy
grails-app/migrations/0.9.x/changelog-2025-03-26-2057-update-abc-class-convert-empty-string-to-null.xml
grails-app/migrations/0.9.x/changelog.xml

https://pihemr.atlassian.net/browse/OBPIH-7020
https://pihemr.atlassian.net/browse/OBPIH-7136
The ABC class property is a nullable varchar(255) column. That means it currently supports values like NULL, empty string, and alphanumeric characters up to a size of 255.  The default sorting used by MySQL/MariaDB ORDER BY mechanism will sort NULL and empty strings ahead of valid ABC classes (i.e. A, B, C). This has caused issues with the cycle session and ranking algorithm which should be treating NULL and empty string as the default class that comes after A, B, C. The ranking …

Obpih 7136

---

grails-app/domain/org/pih/warehouse/inventory/InventoryItem.groovy
grails-app/init/org/pih/warehouse/BootStrap.groovy
src/js/hooks/cycleCount/useCountStep.jsx
src/js/hooks/cycleCount/useResolveStep.js
src/main/groovy/org/pih/warehouse/inventory/CycleCountItemCommand.groovy

I decided to change the default row values (lot number) to null instead of an empty string, because it looks more appropriate in that case. The main issue here is that we can have *TWO* different values for the default lot number. Sometimes I got null, and the other time I got an empty string. The empty strings come from record stock, but I noticed that I was able to create an inventory item with null (I don't know how; it happened just once). So to unify the behavior, I added null as a fallback to always get the same default lot.
The issue with grouping rows that caused the duplicated rows behaviour again existed because, during finding an inventory item, we searched for null, but the inventory item had an empty string (it was also achievable to reproduce this the other way.)

OBPIH-7173 Rows duplicated when add the same inventory with no lot as added on recount (fixes after QA)

---

grails-app/services/org/pih/warehouse/inventory/CycleCountService.groovy

The issue was caused by the fact that we are calling the save action for every item before submitting a recount. During save, we were looking for existing inventory to assign the already existing QoH for the newly created inventory on recount. So, it led to the inability to detect discrepancies because the QoH was the same on the record stock and in the cycle count item. As a fix, I am setting QoH for the newly created row to 0, so that the discrepancy can be found during submitting a recount, and after refreshing, the existing inventory data will be fetched and correctly displayed. In that case, the information about the discrepancy will be visible for every cycle count that includes newly created inventory.
- in case when we added a new inventory on record stock and the recount stays …

OBPIH-7177 Inventory has changed not detected when add line on recount and the same line on record stock 

---

grails-app/migrations/views/cycle-count-candidate.sql
grails-app/migrations/views/cycle-count-session.sql
grails-app/migrations/views/pending_cycle_count_request.sql

**Link to GitHub issue or Jira ticket:** https://pihemr.atlassian.net/browse/OBPIH-7048
**Description:** We don't want to display inactive products on the all products, to count, or to recount tabs. This change filters them out from display but still allows you to submit a count/recount on a product that was marked inactive while you already had the count/recount step open.
---
https://jam.dev/c/3d0830b0-34ea-4f3e-ad36-f7b937d5be64
[946cc7c0-57d0-4940-987c-81712e1099c4.webm](https://github.com/user-attachments/assets/dd0523ae-7191-4c0f-8c7f-3facb4cfee31)

OBPIH-7048 filter out inactive products from cycle count tables

---

grails-app/migrations/0.9.x/changelog-2025-04-29-0000-add-inventory-baseline-transaction-type.xml
grails-app/migrations/0.9.x/changelog-2025-04-29-0000-add-product-inventory-snapshot-transaction-type.xml
grails-app/migrations/0.9.x/changelog.xml
grails-app/services/org/pih/warehouse/inventory/CycleCountProductInventoryTransactionService.groovy
grails-app/services/org/pih/warehouse/inventory/CycleCountTransactionService.groovy
grails-app/services/org/pih/warehouse/inventory/ProductInventoryTransactionService.groovy
src/main/groovy/org/pih/warehouse/core/Constants.groovy
src/main/groovy/org/pih/warehouse/inventory/ProductInventorySnapshotSource.groovy
src/test/groovy/unit/org/pih/warehouse/inventory/CycleCountProductInventoryTransactionServiceSpec.groovy
src/test/groovy/unit/org/pih/warehouse/inventory/CycleCountTransactionServiceSpec.groovy

**Link to GitHub issue or Jira ticket:** https://pihemr.atlassian.net/browse/OBPIH-7193
**Description:** Add the new "Product Inventory Snapshot" transaction type and switch cycle count to use it.
---
Cycle counts can successfully create the new "product inventory snapshot" transactions after the count is submitted:
And last counted date is still updated correctly:

OBPIH-7193: add product inventory snapshot transaction type

---

.github/workflows/backend-tests.yml

**Link to GitHub issue or Jira ticket:** N/A
**Description:** We're not supporting MySQL 5.7 for 0.9.x releases any longer, and since we've started using CTEs (which are not supported in 5.7), this marks the final nail in the coffin for abandoning 5.7 support.

Disable MySQL 5.7 test runner

---

grails-app/utils/org/pih/warehouse/DateUtil.groovy
grails-app/utils/org/pih/warehouse/databinding/DataBindingConstants.groovy
grails-app/utils/org/pih/warehouse/databinding/InstantValueConverter.groovy
grails-app/utils/org/pih/warehouse/databinding/LocalDateValueConverter.groovy
grails-app/utils/org/pih/warehouse/databinding/ZonedDateTimeValueConverter.groovy
src/main/groovy/org/pih/warehouse/core/Constants.groovy
src/test/groovy/unit/org/pih/warehouse/utils/DateUtilSpec.groovy
src/test/groovy/unit/org/pih/warehouse/utils/databinding/InstantValueConverterSpec.groovy
src/test/groovy/unit/org/pih/warehouse/utils/databinding/ZonedDateTimeValueConverterSpec.groovy

**Link to GitHub issue or Jira ticket:** https://pihemr.atlassian.net/browse/OBPIH-7255
- Switch Instant to error if time or zone aren't provided instead of defaulting to midnight UTC (Instant isn't being used anywhere yet so this is safe to do)
- Add support for parsing ZonedDateTime. ZDT is like Instant except it preserves timezone (Instant is only a UTC timestamp) so is needed for exports and GSPs where we need the backend to know what timezone to display
- Add XForDisplay methods for converting these data types to Strings for display (used by GSPs, and data exporters).

OBPIH-7255: add support for ZonedDateTime to backend

---

grails-app/services/org/pih/warehouse/inventory/InventoryService.groovy
grails-app/services/org/pih/warehouse/inventory/ProductAvailabilityService.groovy
grails-app/services/org/pih/warehouse/inventory/ProductInventoryTransactionService.groovy
src/test/groovy/unit/org/pih/warehouse/inventory/CycleCountProductInventoryTransactionServiceSpec.groovy

**Link to GitHub issue or Jira ticket:** https://pihemr.atlassian.net/browse/OBPIH-7195
**Description:** Two fixes:
1) Error creating a baseline transaction if a transaction already exists for the given transaction date
2) Exclude any items where QoH == 0 from the baseline transaction
---

OBPIH-7195 fix: error creating baseline if a transaction already exists for given date

---

grails-app/i18n/messages.properties
src/main/groovy/org/pih/warehouse/inventory/CycleCountStartCommand.groovy

**Link to GitHub issue or Jira ticket:** https://pihemr.atlassian.net/browse/OBPIH-7143
**Description:** Kasia had a good point that when the product is in a pending outbound, we should also block users from **starting** a count (the other PR was for erroring when **requesting** a count). However we should only block the count from being started while it's in the "to count" state. Once there is progress in the count, it should be able to finish.
Initial PR: https://github.com/openboxes/openboxes/pull/5276

OBPIH-7143 fail starting count when in pending outbound

---

grails-app/services/org/pih/warehouse/importer/InventoryImportDataService.groovy
grails-app/services/org/pih/warehouse/inventory/InventoryService.groovy
grails-app/services/org/pih/warehouse/inventory/ProductAvailabilityService.groovy
grails-app/services/org/pih/warehouse/inventory/ProductInventoryTransactionService.groovy

**Link to GitHub issue or Jira ticket:** https://pihemr.atlassian.net/browse/OBPIH-7195
**Description:** This is just embarassing now :upside_down_face: The original code that checked for duplicate transactions was using the items in product availability, but those available items were from the time of the baseline transaction. If there were items in the import that didn't have any availability at the time of the baseline (ie quantity == 0) they didn't have any product availability records, and so wouldn't get checked. Now I make sure to check ALL items that were given in the input data.
---
[//]: <> (If this PR contains a UI …

OBPIH-7195 fix3: inventory import, fix existing transaction check

---

grails-app/services/org/pih/warehouse/importer/InventoryImportDataService.groovy
grails-app/services/org/pih/warehouse/inventory/InventoryService.groovy
grails-app/services/org/pih/warehouse/inventory/ProductAvailabilityService.groovy
grails-app/services/org/pih/warehouse/inventory/ProductInventoryTransactionService.groovy

**Link to GitHub issue or Jira ticket:** https://pihemr.atlassian.net/browse/OBPIH-7195
**Description:** Two fixes:
1) Allow for duplicate lines in the import. They should each result in separate transaction entries whos quantities sum up to each other.
2) Any items that have stock but were not included in the import will have their stock set to zero
---
Video explaining the change: https://jam.dev/c/27edbf8b-a984-481e-ba15-a3285114913d

OBPIH-7195 fix4: handle inventory import duplicates and zero out stock for missing rows

---

grails-app/views/location/edit.gsp
grails-app/views/location/showBinLocations.gsp

**Link to GitHub issue or Jira ticket:** https://openboxes.atlassian.net/browse/OB-3258
- Ensure the spinner shows while the tab content is fetching, and that DataTables only initialize after the new HTML is loaded.
---

OB-3258: fix loader while applying data table styles

---

grails-app/i18n/messages.properties
grails-app/views/shipment/showDetails.gsp

**Link to GitHub issue or Jira ticket:** https://pihemr.atlassian.net/browse/OBPIH-7295
**Description:** Add the supplier code (of the origin org) to the shipment details page if the shipment is from a purchase order
---

OBPIH-7295 add supplier code to shipment details page if shipment is for a PO

---

.github/workflows/docker-image.yml

**Link to GitHub issue or Jira ticket:** N/A
**Description:** the docker-image.yml workflow is broken. This should hopefully fix it. The reason it broke was because the `actions/cache@v1` action was removed recently: https://github.com/orgs/community/discussions/148746. I switched the logic to behave like we have it elsewhere in our workflows (using the 'cache' attribute of the setup-java action).
I haven't run this yet to confirm if it works.

Fix broken workflow docker-image.yml

---

grails-app/services/org/pih/warehouse/inventory/InventoryService.groovy

**Link to GitHub issue or Jira ticket:** https://pihemr.atlassian.net/browse/OBPIH-7430
**Description:** Doing a record stock where the quantity for all items is unchanged (ie there are no adjustments) is valid and so should not throw an error.
---
A video recording of the issue: https://jam.dev/c/2309b701-383f-4c6b-b01b-59eced2b41c3

OBPIH-7430 don't error on record stock if no adjustments are made

---

grails-app/controllers/org/pih/warehouse/data/MigrationController.groovy
grails-app/services/org/pih/warehouse/data/MigrationService.groovy
grails-app/views/migration/dataMigration.gsp

- Display other transactions with dates overlapping with product inventory
- Properly zero out stock that is available, but is not in the transaction entries
- Save migration report CSV
- Do not remove multi-product transactions for the same transaction date

OBPIH-7329 Product Inventory migration improvements

---

grails-app/services/org/pih/warehouse/importer/InventoryImportDataService.groovy
grails-app/services/org/pih/warehouse/inventory/InventoryService.groovy

**Link to GitHub issue or Jira ticket:** https://pihemr.atlassian.net/browse/OBPIH-7437
**Description:** If an import has no products/items or all the items are skipped due to no quantity being defined, ALL products for the facility were getting zeroed out. This was due to how a query in InventoryService was working (if the given list of products is falsey, fetch ALL transactions).
A more proper fix would be to change the query to distinguish between an empty list of products and a null list of products, but that refactor would have potential knock on effects across users of that query so I opted for the safest option for now since …

OBPIH-7437 handle all items skipped during inventory import

---

grails-app/views/location/showBinLocations.gsp

**Link to GitHub issue or Jira ticket:** https://openboxes.atlassian.net/browse/OBLS-133
Dsplay zone name and location type in the proper column.
---

OBLS-133 display zone name and location type in the proper column
