openboxes/openboxes

- grails-app/services/org/pih/warehouse/shipping/ShipmentService.groovy
- grails-app/views/createShipmentWorkflow/createShipment/enterContainerDetails.gsp
> Hotfix/release 0.7.25

- .gitignore
- README.md
- docs/developer-guide/getting-started.md
- package.json
- src/js/index.jsx
- webpack.config.js
https://tickets.pih-emr.org/browse/OBPIH-823
> OBPIH-823 Add NPM as a dependency management tool plus webpack

- .babelrc
- README.md
- docs/developer-guide/getting-started.md
- package.json
- scripts/_Events.groovy
- src/js/components/app.jsx
- src/js/index.jsx
- src/js/tests/App.test.jsx
- webpack.config.js
https://tickets.pih-emr.org/browse/OBPIH-837
> Add Jest as Testing Framework for React

- package.json
- src/js/tests/api-client/apiClient.test.js
- src/js/utils/apiClient.js
https://tickets.pih-emr.org/browse/OBPIH-854
> Implement dummy JS API client (wrapper)

- src/css/main.scss
- src/js/components/form-elements/WizardSteps.jsx
- src/js/tests/form-elements/WizardSteps.test.jsx
- src/js/tests/form-elements/__snapshots__/WizardSteps.test.jsx.snap
https://tickets.pih-emr.org/browse/OBPIH-860
> OBPIH-860 Wizard form steps

- src/js/components/stock-movement-wizard/EditPage.jsx
- src/js/mockedData.jsx
-make reason code field disabled if revise qty is not entered
-add validation on reason code fields
-removed empty option for Stock list (it's already in select)
> OBPIH-879/873:

- src/css/main.scss
- src/js/components/stock-movement-wizard/AddItemsPage.jsx
- src/js/components/stock-movement-wizard/CreateStockMovement.jsx
- src/js/components/stock-movement-wizard/SendMovementPage.jsx
- src/js/components/stock-movement-wizard/modals/EditPickModal.jsx
- src/js/components/stock-movement-wizard/validate.jsx
https://tickets.pih-emr.org/browse/OBPIH-885
> Step 5: Send movement page (for all movements) general view

- src/js/components/form-elements/FieldArrayComponent.jsx
- src/js/components/form-elements/TableRow.jsx
- src/js/components/form-elements/TableRowWithSelector.jsx
Row Components for easy table row management (adding css classes etc.)
> Customizable Row Component

- src/js/components/stock-movement-wizard/AddItemsPage.jsx
- src/js/components/stock-movement-wizard/CreateStockMovement.jsx
- src/js/components/stock-movement-wizard/SendMovementPage.jsx
- src/js/mockedData.jsx
https://tickets.pih-emr.org/browse/OBPIH-951
https://tickets.pih-emr.org/browse/OBPIH-913
> Wire up API to Stock Movements - Step 1 (Create movement)

- grails-app/conf/BootStrap.groovy
- grails-app/conf/UrlMappings.groovy
- grails-app/controllers/org/pih/warehouse/api/ProductApiController.groovy
OBPIH-968 Create substitutions API to populate substitutions modal in step 3
> Improvements to stock movement API 

- docs/api-guide/stockMovement.md
- grails-app/controllers/org/pih/warehouse/api/ProductApiController.groovy
- grails-app/controllers/org/pih/warehouse/api/StockMovementApiController.groovy
- grails-app/services/org/pih/warehouse/inventory/StockMovementService.groovy
- src/groovy/org/pih/warehouse/api/StockMovement.groovy
- src/groovy/org/pih/warehouse/api/StockMovementItem.groovy
Also includes
* OBPIH-970 Return available items for active products only
> OBPIH-995 Create API for saving modifications to stock movements

- src/js/components/form-elements/BaseField.jsx
- src/js/components/form-elements/FieldArrayComponent.jsx
- src/js/components/stock-movement-wizard/AddItemsPage.jsx
- src/js/components/stock-movement-wizard/CreateStockMovement.jsx
- src/js/components/stock-movement-wizard/EditPage.jsx
- src/js/components/stock-movement-wizard/SendMovementPage.jsx
- src/js/tests/form-elements/__snapshots__/ArrayField.test.jsx.snap
https://tickets.pih-emr.org/browse/OBPIH-952
> Stock Movements - Step 2 API - create/update/delete line items

- src/js/components/stock-movement-wizard/EditPage.jsx
- src/js/components/stock-movement-wizard/PickPage.jsx
https://tickets.pih-emr.org/browse/OBPIH-974
https://tickets.pih-emr.org/browse/OBPIH-975
> Step 3/4 - main row styling

- src/js/components/stock-movement-wizard/CreateStockMovement.jsx
On Page 1 of stock movements, move Next button to right of the page
> OBPIH-1054 Next button moved to right of the page

- src/js/components/stock-movement-wizard/modals/SubstitutionsModal.jsx
include header in substitution pop-up window
> OBPIH-977 Quantity remaining replaced with Quantity selected

- src/js/components/stock-movement-wizard/AddItemsPage.jsx
Step 2: Improve validation and block "Next" button
Step 2 with no stocklist: limit number of rows
> OBPIH-900 && OBPIH-1058

- package.json
- src/css/main.scss
- src/js/components/stock-movement-wizard/AddItemsPage.jsx
- src/js/components/stock-movement-wizard/EditPage.jsx
- src/js/components/stock-movement-wizard/PickPage.jsx
- src/js/components/stock-movement-wizard/SendMovementPage.jsx
- src/js/components/stock-movement-wizard/StockMovement.jsx
- src/js/components/stock-movement-wizard/modals/EditPickModal.jsx
Step 5 - fetching data
Step 5 - printing delivery note (https://tickets.pih-emr.org/browse/OBPIH-891)
Step 5 - printing packing list (https://tickets.pih-emr.org/browse/OBPIH-892)
Step 5 - printing certificate of donation (https://tickets.pih-emr.org/browse/OBPIH-893)
Step 5 - uploading documents (https://tickets.pih-emr.org/browse/OBPIH-898)
> Step 5 - wiring api

- src/js/components/stock-movement-wizard/modals/EditPickModal.jsx
https://tickets.pih-emr.org/browse/OBPIH-935
> Step 4 - edit pick validation fix

- src/css/main.scss
- src/js/components/stock-movement-wizard/AddItemsPage.jsx
- src/js/components/stock-movement-wizard/CreateStockMovement.jsx
- src/js/components/stock-movement-wizard/EditPage.jsx
- src/js/components/stock-movement-wizard/PickPage.jsx
- src/js/components/stock-movement-wizard/SendMovementPage.jsx
- src/js/components/stock-movement-wizard/modals/AdjustInventoryModal.jsx
Wire up adjusting inventory modal behavior on step 4 of stock movements (save action)
> OBPIH-1074

- src/js/components/Layout/Header.jsx
https://tickets.pih-emr.org/browse/OBPIH-1027
> Remove Global search box on new pages

- src/js/components/stock-movement-wizard/AddItemsPage.jsx
* Add Export/Import of packing list on form step 2 if the movement is from a vendor
* Step 2 with no stock list: Export/Import template
> OBPIH-890 & OBPIH-897

- src/css/main.scss
- src/js/components/stock-movement-wizard/AddItemsPage.jsx
- src/js/components/stock-movement-wizard/CreateStockMovement.jsx
- src/js/components/stock-movement-wizard/EditPage.jsx
- src/js/components/stock-movement-wizard/SendMovementPage.jsx
- src/js/components/stock-movement-wizard/modals/AdjustInventoryModal.jsx
- src/js/components/stock-movement-wizard/modals/EditPickModal.jsx
- src/js/components/stock-movement-wizard/validate.jsx
https://tickets.pih-emr.org/browse/OBPIH-955
> Step 5 - sending shipment (plus small improvements)

- src/js/components/put-away/PutAwayCheckPage.jsx
- src/js/components/put-away/PutAwayPage.jsx
- src/js/components/put-away/PutAwaySecondPage.jsx
OBSYS: Make next and previous buttons consistent on put away pages
> OBPIH-1086

- src/css/main.scss
- src/js/components/receiving/PartialReceivingPage.jsx
- src/js/components/receiving/modals/EditLineModal.jsx
- src/js/utils/Checkbox.jsx
UI for https://tickets.pih-emr.org/browse/OBPIH-888
> Partial receiving - Edit line modal (ui)

- src/js/components/stock-movement-wizard/EditPage.jsx
- src/js/components/stock-movement-wizard/PickPage.jsx
- src/js/components/stock-movement-wizard/modals/AdjustInventoryModal.jsx
- src/js/components/stock-movement-wizard/modals/EditPickModal.jsx
- src/js/components/stock-movement-wizard/modals/SubstitutionsModal.jsx
> OBPIH-903 make qty column narrower

- src/js/components/stock-movement-wizard/EditPage.jsx
- src/js/components/stock-movement-wizard/PickPage.jsx
Fix issues with displaying columns on lower resolution
> OBPIH-903 resize column's width

- src/js/en.js
- src/js/fr.js
Add a possibility to go to put away from stock movement's level
> OBPIH-1135 Add put away to stock movement's menu

- src/js/components/receiving/PartialReceivingPage.jsx
- src/js/components/receiving/ReceivingCheckScreen.jsx
make all the buttons look like on other pages
> OBPIH-1106 make buttons consistent with other pages

- src/js/components/put-away/SplitLineModal.jsx
Missing information outlined in red + delete button added
> OBPIH-1137 improve validation for split lines in put away

- src/js/components/stock-movement-wizard/AddItemsPage.jsx
- src/js/utils/apiClient.jsx
API client should handle errors from the API
> OBPIH-1134

- src/js/components/stock-movement-wizard/CreateStockMovement.jsx
With this autofocus user can get through all the shipment using just a keyboard
> add autofocus on first field of step 1

- src/js/components/stock-movement-wizard/AddItemsPage.jsx
Adjust columns' width so user is able to see the full name of the item
> OBPIH-1125 adjust columns' width

- src/js/components/stock-movement-wizard/modals/SubstitutionsModal.jsx
arrayRemove and arrayInsert are no longer used in SusbsitutionsModal so they should be removed
> Remove unused propTypes

- src/js/components/stock-movement-wizard/EditPage.jsx
Make the product name column as close to 100 characters as possible. Other columns widths can be decreased.
> OBPIH-1155 make product name column on edit page wider

- src/js/components/stock-movement-wizard/AddItemsPage.jsx
https://tickets.pih-emr.org/browse/OBPIH-1144
> Stock movements - fix updating items (supplier case)

- src/js/components/stock-movement-wizard/PickPage.jsx
Try to make the product name column as close to 100 characters as possible
Other columns widths can be decreased.
> OBPIH-1152 make product name column on pick page wider

- src/js/components/receiving/ReceivingCheckScreen.jsx
Make only non-zero quantities highlighted red
> OBPIH-1165 Partial receipt-- If zero remaining, should not be red

- src/js/components/form-elements/DateField.jsx
Add possibility to select year in data selector in order to not to page thorough each month
> OBPIH-1167 add button to advance year on data selector

- src/js/components/stock-movement-wizard/AddItemsPage.jsx
If stock movement from a depot and without a stock list, add column for recipient
> OBPIH-1062 Need Recipient column for stock movement without stock list

- grails-app/controllers/org/pih/warehouse/api/StockMovementItemApiController.groovy
- src/js/components/stock-movement-wizard/modals/EditPickModal.jsx
If quantity picked is null or empty string, send 0
> OBPIH-1107 Pick qty not updating when one line left blank

- src/js/components/stock-movement-wizard/EditPage.jsx
- src/js/components/stock-movement-wizard/PickPage.jsx
https://tickets.pih-emr.org/browse/OBPIH-999
> OBPIH-999 - Undo change to a line on step 3 and 4

- src/js/components/stock-movement-wizard/PickPage.jsx
Small fix for https://tickets.pih-emr.org/browse/OBPIH-999
> Step 4 - undoing pick changes fix

- grails-app/services/org/pih/warehouse/inventory/StockMovementService.groovy
- src/js/components/stock-movement-wizard/AddItemsPage.jsx
- src/js/reducers/usersReducer.jsx
fix for recipient change on step 2 (https://tickets.pih-emr.org/browse/OBPIH-1062)
Plus i brought back https://github.com/openboxes/openboxes/pull/442, because this somehow got lost during some rebasing actions.
> Step 2 - recipient change save fix

- src/groovy/org/pih/warehouse/api/StockMovementItem.groovy
https://tickets.pih-emr.org/browse/OBPIH-1124
> Display quantity requested for substituted items

- src/js/components/stock-movement-wizard/EditPage.jsx
https://tickets.pih-emr.org/browse/OBPIH-1214
> Fix undoing a line with revised quantity equal to 0

- src/js/components/stock-movement-wizard/SendMovementPage.jsx
https://tickets.pih-emr.org/browse/OBPIH-1233
> After successful shipment sending redirect to shipment details page

- grails-app/services/org/pih/warehouse/inventory/StockMovementService.groovy
- src/js/components/stock-movement-wizard/EditPage.jsx
https://tickets.pih-emr.org/browse/OBPIH-1098
> Auto pick for substituted items

- src/js/components/stock-movement-wizard/EditPage.jsx
https://tickets.pih-emr.org/browse/OBPIH-1203
> Formatting changes to available qty in stock movement

- src/js/components/stock-movement-wizard/AddItemsPage.jsx
https://tickets.pih-emr.org/browse/OBPIH-1244
> Recipient list opening on click disabled

- src/js/components/stock-movement-wizard/PickPage.jsx
- src/js/components/stock-movement-wizard/modals/AdjustInventoryModal.jsx
- src/js/components/stock-movement-wizard/modals/EditPickModal.jsx
- src/js/components/stock-movement-wizard/modals/SubstitutionsModal.jsx
https://tickets.pih-emr.org/browse/OBPIH-1215
> Remove redundant internal locations fetches

- src/js/components/stock-movement-wizard/CreateStockMovement.jsx
https://tickets.pih-emr.org/browse/OBPIH-908
> Saving edits when go back and add stock list

- src/js/components/put-away/PutAwayCheckPage.jsx
- src/js/components/put-away/PutAwayMainPage.jsx
- src/js/components/put-away/PutAwayPage.jsx
- src/js/components/put-away/PutAwaySecondPage.jsx
- src/js/components/receiving/PartialReceivingPage.jsx
- src/js/components/receiving/ReceivingPage.jsx
- src/js/components/receiving/modals/EditLineModal.jsx
- src/js/components/stock-movement-wizard/AddItemsPage.jsx
- src/js/components/stock-movement-wizard/PickPage.jsx
- src/js/components/stock-movement-wizard/modals/AdjustInventoryModal.jsx
https://tickets.pih-emr.org/browse/OBPIH-1198
> OBPIH-1198 - Location-based API requests

- src/js/en.js
- src/js/fr.js
https://tickets.pih-emr.org/browse/OBPIH-1270
> Add receiving menu option

- src/js/components/DocumentButton.jsx
- src/js/components/stock-movement-wizard/SendMovementPage.jsx
https://tickets.pih-emr.org/browse/OBPIH-1276
> Reusable component for document download

- src/js/components/GlobalSearch.jsx
https://tickets.pih-emr.org/browse/OBPIH-1266
> Global search fix

- src/js/components/stock-movement-wizard/AddItemsPage.jsx
- src/js/components/stock-movement-wizard/EditPage.jsx
- src/js/components/stock-movement-wizard/PickPage.jsx
Send status update on every page transition without checking the current state
> OBPIH-1180 Send status update on every page transition

- src/js/components/put-away/PutAwayCheckPage.jsx
- src/js/components/put-away/PutAwayPage.jsx
- src/js/components/put-away/PutAwaySecondPage.jsx
1.      Remove dash in Put-Away in header on both pages
2.      Make lot column Lot/Serial No. on both pages (need to make sure serial number will pull through)
> OBPIH-1220 Tweaks to put away pages

- src/css/main.scss
- src/js/components/stock-movement-wizard/SendMovementPage.jsx
https://tickets.pih-emr.org/browse/OBPIH-1122
> Improvements to document upload

- src/js/components/stock-movement-wizard/AddItemsPage.jsx
Add "Delete all" button which allows user to remove all items from requisition's items list.
> OBPIH-1237 Add 'delete all' button on add items page of stock movement

- src/css/main.scss
- src/js/components/form-elements/LabelField.jsx
- src/js/components/stock-movement-wizard/PickPage.jsx
Wrap text in label fields and make lot column wider.
> OBPIH-1280 Make full lot/serial number visible and wrap text

- grails-app/services/org/pih/warehouse/inventory/InventoryService.groovy
Sort bin locations by available quantity before sorting by expiration date to pick the one with least number of items.
> OBPIH-1018 Pick from bin with least number of items first

- src/js/components/stock-movement-wizard/AddItemsPage.jsx
short fix to make sure that any time we delete all items, page is refreshing
> OBPIH-1237 fix refreshing after deleting all items

- src/js/components/stock-movement-wizard/PickPage.jsx
Update condition to fix autopick issue. Now it search not only by inventoryItem.id but also by binLocation.id.
> OBPIH-1209 Fix autopick

- src/groovy/org/pih/warehouse/api/StockMovement.groovy
- src/groovy/org/pih/warehouse/api/StockMovementItem.groovy
- src/js/components/stock-movement-wizard/AddItemsPage.jsx
Sort items in Stock Movement using sortOrder attribute
> OBPIH-1056 Sorting items in stock movement

- src/js/components/form-elements/DateField.jsx
- src/js/utils/Input.jsx
Prevent user from submitting form when enter is pressed
> OBPIH-1267 Disable form submission when enter is pressed

- src/groovy/org/pih/warehouse/api/PartialReceipt.groovy
- src/js/components/form-elements/FieldArrayComponent.jsx
- src/js/components/receiving/PartialReceivingPage.jsx
- src/js/components/receiving/ReceivingCheckScreen.jsx
- src/js/components/receiving/ReceivingPage.jsx
- src/js/components/receiving/modals/EditLineModal.jsx
- src/js/components/stock-movement-wizard/modals/AdjustInventoryModal.jsx
- src/js/components/stock-movement-wizard/modals/EditPickModal.jsx
- src/js/components/stock-movement-wizard/modals/PackingSplitLineModal.jsx
- src/js/components/stock-movement-wizard/modals/SubstitutionsModal.jsx
- src/js/tests/form-elements/__snapshots__/ArrayField.test.jsx.snap
- src/js/tests/form-elements/__snapshots__/TextField.test.jsx.snap
Redirect user to stock movement view page after clicking "receive shipment"
> OBPIH-1313 Redirect user to stock movement view page

- src/groovy/org/pih/warehouse/api/StockMovement.groovy
- src/js/components/stock-movement-wizard/CreateStockMovement.jsx
- src/js/components/stock-movement-wizard/SendMovementPage.jsx
- src/js/components/stock-movement-wizard/StockMovement.jsx
https://tickets.pih-emr.org/browse/OBPIH-1309
> OBPIH-1309: Change stock movement header without obliterating lines

- src/js/components/stock-movement-wizard/CreateStockMovement.jsx
https://tickets.pih-emr.org/browse/OBPIH-1344
https://tickets.pih-emr.org/browse/OBPIH-1340
> OBPIH-1344: Fixed bug during creation of new stock movement

- src/js/components/put-away/PutAwayCheckPage.jsx
- src/js/components/put-away/PutAwayPage.jsx
- src/js/components/put-away/PutAwaySecondPage.jsx
Put navigation buttons in both above and below the form to make it visible for users when they are on the bottom or top of the page
> OBPIH-1316 Make navigation buttons always visible

- src/js/components/stock-movement-wizard/SendMovementPage.jsx
https://tickets.pih-emr.org/browse/OBPIH-1317
> OBPIH-1317: Navigation buttons displayed twice on Send shipment page

- src/js/components/stock-movement-wizard/AddItemsPage.jsx
- src/js/components/stock-movement-wizard/EditPage.jsx
- src/js/components/stock-movement-wizard/PackingPage.jsx
- src/js/components/stock-movement-wizard/PickPage.jsx
Enable virtualization and change autofocus to improve performance with large imports
> OBPIH-1345 Improve performance with large imports

- grails-app/controllers/org/pih/warehouse/inventory/StockMovementController.groovy
- grails-app/views/dashboard/megamenu.gsp
- package.json
- src/js/components/stock-movement-wizard/CreateStockMovement.jsx
- src/js/components/stock-movement-wizard/StockMovement.jsx
- src/js/reducers/locationsReducer.jsx
If user selects Inbound>Create incoming stock movement, autofill destination of stock movement as the location the user is in.
If user selects Outbound>Create outgoing stock movement, autofill origin of stock movement as the location the user is in.
> OBPIH-1327 Autofill localization based on menu selection

- grails-app/domain/org/pih/warehouse/picklist/Picklist.groovy
- grails-app/domain/org/pih/warehouse/picklist/PicklistItem.groovy
- grails-app/migrations/0.8.x/changelog-2018-11-07-1501-alter-table-picklist-item-add-column-sort-order.xml
- grails-app/migrations/0.8.x/changelog.xml
- grails-app/services/org/pih/warehouse/inventory/StockMovementService.groovy
https://tickets.pih-emr.org/browse/OBPIH-1394
@jmiranda  please look at my comment in related ticket
> OBPIH-1394: Fixed ordering of items on pack page

- grails-app/services/org/pih/warehouse/inventory/InventoryService.groovy
First sorting by item codes that contian search term then sort by names that contain search term
https://tickets.pih-emr.org/browse/OBPIH-1397
> OBPIH-1397: Changed sorting during item search

- grails-app/services/org/pih/warehouse/core/LocationService.groovy
- src/js/en.js
Limit location chooser to depot and add direction param to url in react pages
> OBPIH-1449 Limit location chooser to depot

- src/js/components/stock-movement-wizard/CreateStockMovement.jsx
https://tickets.pih-emr.org/browse/OBPIH-1453
> OBPIH-1453: Turned off datepicker autocomplete on first step

- src/js/components/stock-movement-wizard/AddItemsPage.jsx
Remove unnecessary validation on add items page
> OBPIH-1468 Remove 'confirm save' validation when exporting template

- grails-app/controllers/org/pih/warehouse/api/PersonApiController.groovy
- grails-app/services/org/pih/warehouse/core/LocationService.groovy
- grails-app/services/org/pih/warehouse/core/UserService.groovy
- src/js/components/stock-movement-wizard/CreateStockMovement.jsx
- src/js/components/stock-movement-wizard/PackingPage.jsx
- src/js/components/stock-movement-wizard/SendMovementPage.jsx
- src/js/components/stock-movement-wizard/modals/PackingSplitLineModal.jsx
- src/js/utils/option-utils.jsx
https://tickets.pih-emr.org/browse/OBPIH-1351
> OBPIH-1351: Fixed filtering in location and person endpoints

- grails-app/controllers/org/pih/warehouse/JsonController.groovy
Search results in the global search first show items that have a match to the item code, followed by a match to the item name, followed by manufacturer code, followed by vendor code, followed by other searchable data.
> OBPIH-1513 Improve filter on global search

- src/js/components/receiving/PartialReceivingPage.jsx
- src/js/components/receiving/modals/EditLineModal.jsx
- src/js/components/stock-movement-wizard/AddItemsPage.jsx
- src/js/components/stock-movement-wizard/SendMovementPage.jsx
- src/js/components/stock-movement-wizard/modals/AdjustInventoryModal.jsx
https://tickets.pih-emr.org/browse/OBPIH-1520
> OBPIH-1520: date picker autocomplete turned off

- src/css/main.scss
- src/js/components/form-elements/FieldArrayComponent.jsx
- src/js/components/form-elements/LabelField.jsx
- src/js/components/stock-movement-wizard/EditPage.jsx
- src/js/components/stock-movement-wizard/PickPage.jsx
- src/js/tests/form-elements/ArrayField.test.jsx
- src/js/tests/form-elements/__snapshots__/ArrayField.test.jsx.snap
Adjust column's width, make font size smaller and add tooltip to column names
> OBPIH-1528 See full column names

- src/js/components/stock-movement-wizard/SendMovementPage.jsx
Send less data on SendMovementPage
> OBPIH-1517 Fix save issue

- grails-app/i18n/messages.properties
- grails-app/i18n/messages_fr.properties
- src/js/MainRouter.jsx
- src/js/components/form-elements/FieldArrayComponent.jsx
- src/js/components/put-away/PutAwayCheckPage.jsx
- src/js/components/receiving/PartialReceivingPage.jsx
- src/js/utils/form-utils.jsx
Set default message on missing translations and add new messages code to messages_fr.properties
> OBPIH-1561 Add default message on missing translations

- grails-app/i18n/messages.properties
- grails-app/views/picklist/_page.gsp
- grails-app/views/picklist/_printPage.gsp
@jmiranda this is ready to be merged, but we can wait and do it after release
> OBPIH-1531: Changed column names on exported pick list

- grails-app/views/product/_summary.gsp
@jmiranda feature is ready, but we can merge it after release
> OBPIH-1508: added clickable catalog box

- grails-app/services/org/pih/warehouse/core/DocumentService.groovy
@jmiranda feature is ready, but we can merge it after release
> OBPIH-1529: Added stock movement number to packing list spreadsheet

- grails-app/services/org/pih/warehouse/inventory/StockMovementService.groovy
- src/js/components/stock-movement-wizard/modals/SubstitutionsModal.jsx
plus fixed date comparison
@jmiranda feature is ready, but Jesse wanted to have this merged after todays release.
> OBPIH-1535: Changed line order during substitution

- grails-app/services/org/pih/warehouse/inventory/StockMovementService.groovy
- grails-app/views/stockMovement/_documents.gsp
- grails-app/views/stockMovement/show.gsp
@jmiranda feature ready, but lets wait with merge for release
> OBPIH-1342: some stock movement documents hidden

- src/js/components/stock-list-management/StocklistManagement.jsx
https://tickets.pih-emr.org/browse/OBPIH-1577
> OBPIH-1577: Clicking on stocklist name linkes to stocklist details

- grails-app/i18n/messages.properties
- src/js/components/stock-list-management/StocklistManagement.jsx
Add tooltips on headers, change columns' names and add translations to stocklist management pages.
> OBPIH-1578 Change column names, add translations and tooltips

- grails-app/i18n/messages.properties
- src/js/components/stock-movement-wizard/AddItemsPage.jsx
Add validation message if there are items with the same code on the second page of stock movement.
> OBPIH-1331 Add duplicates validation

- grails-app/controllers/org/pih/warehouse/order/OrderController.groovy
- grails-app/i18n/messages.properties
- grails-app/views/dashboard/megamenu.gsp
- grails-app/views/order/list.gsp
- src/js/en.js
https://tickets.pih-emr.org/browse/OBPIH-1538
> OBPIH-1538: Improvements to list put away page

- grails-app/views/stockMovement/list.gsp
Filter by "createdBy" instead of "requestedBy" field
> OBPIH-1525 Fix filter when click my stock movements

- grails-app/conf/Config.groovy
- grails-app/controllers/org/pih/warehouse/inventory/InventoryController.groovy
- grails-app/controllers/org/pih/warehouse/user/DashboardController.groovy
- grails-app/i18n/messages.properties
- grails-app/services/org/pih/warehouse/inventory/InventoryService.groovy
- grails-app/services/org/pih/warehouse/product/ProductService.groovy
- grails-app/taglib/org/pih/warehouse/SelectTagLib.groovy
- grails-app/views/dashboard/_catalogsSummary.gsp
- grails-app/views/dashboard/_tagSummary.gsp
- grails-app/views/dashboard/index.gsp
- grails-app/views/inventory/_filters.gsp
- src/groovy/org/pih/warehouse/inventory/InventoryCommand.groovy
- Add catalog feature to dashboard
- Add catalog filter to browser inventory
- Fix tags on dashboard (after clicking tag there were all products in inventory not filtered by tag)
> OBPIH-1330 Add catalog feature to dashboard

- grails-app/services/org/pih/warehouse/inventory/StockMovementService.groovy
https://tickets.pih-emr.org/browse/OBPIH-1342
> OBPIH-1342: Readded 'Export items' document

- grails-app/controllers/org/pih/warehouse/stocklist/StocklistController.groovy
- grails-app/views/stocklist/_itemList.gsp
- grails-app/views/stocklist/_print.gsp
https://tickets.pih-emr.org/browse/OBPIH-1572
> OBPIH-1572: Stocklist pdf export improvements

- grails-app/controllers/org/pih/warehouse/inventory/StockMovementController.groovy
> OBPIH-1378 Change columns names

- grails-app/services/org/pih/warehouse/core/DocumentService.groovy
- grails-app/views/deliveryNote/print.gsp
- grails-app/views/goodsReceiptNote/_header.gsp
- grails-app/views/stocklist/_print.gsp
This reverts commit f0eefb0b16882851e2c70bfa0e28023f71bdd30e.
> Revert "OBPIH-1615 Allow downloadable report to render custom logo"

- grails-app/services/org/pih/warehouse/core/LocationService.groovy
(cherry picked from commit 45591633935e7da3c9a3c48aefcc492b19ecf0be)
> OBPIH-1967 Fix location filtering on outbound stock movement

- grails-app/controllers/org/pih/warehouse/inventory/InventoryLevelController.groovy
- grails-app/domain/org/pih/warehouse/inventory/InventoryLevel.groovy
- grails-app/i18n/messages.properties
- grails-app/migrations/0.8.x/changelog-2019-05-01-2141-inventory-level-improvements.xml
- grails-app/views/inventoryLevel/_form.gsp
- grails-app/views/product/_inventoryLevels.gsp
- src/groovy/org/pih/warehouse/inventory/InventoryStatus.groovy
* OBPIH-1977 SBHF: Export of inventory levels report
* OBPIH-1997 Inventory level should be unique by product and inventory
* OBPIH-2000 Improvements to inventory level
> Inventory level improvements

- grails-app/controllers/org/pih/warehouse/inventory/StockMovementController.groovy
This reverts commit 26ac5865a399e9bbeab22f6b14313ba03f0a5c0a.
> Revert "OBPIH-2011 Fix issue with wrong shipment number"

- src/js/components/form-elements/ButtonField.jsx
- src/js/components/stock-movement-wizard/PickPage.jsx
- src/js/tests/form-elements/ButtonField.test.jsx
- src/js/tests/form-elements/__snapshots__/ButtonField.test.jsx.snap
Add tooltip
Add text truncate
Adjust pick page column's(to sum flexWidths to 12)
> OBPIH-2173 Add text truncate and tooltips on buttons

- grails-app/conf/Config.groovy
- grails-app/controllers/org/pih/warehouse/JsonController.groovy
- grails-app/controllers/org/pih/warehouse/reporting/ReportController.groovy
- grails-app/i18n/messages.properties
- grails-app/jobs/org/pih/warehouse/jobs/CalculateQuantityJob.groovy
- grails-app/migrations/0.8.x/changelog-2019-08-15-1229-alter-table-inventory-snapshot-add-unique-index.xml
- grails-app/migrations/0.8.x/changelog.xml
- grails-app/services/org/pih/warehouse/data/DataService.groovy
- grails-app/services/org/pih/warehouse/inventory/InventoryService.groovy
- grails-app/services/org/pih/warehouse/inventory/InventorySnapshotService.groovy
- grails-app/services/org/pih/warehouse/report/ReportService.groovy
- grails-app/views/report/_showTransactionReportMetadata.gsp
- grails-app/views/report/showTransactionReport.gsp
* OBPIH-2288 Qty in search bar is different to actual qty on hand
* OBPIH-2287 HOT FIX Inventory by location vs Stock download
* OBPIH-2266 add time stamp and refresh button on transaction report
> Hotfix PR for multiple tickets

- grails-app/controllers/org/pih/warehouse/inventory/InventoryController.groovy
This reverts commit d245fa44bcc0939fce634786236f661fbc42b661.
> Revert "OBPIH-2048 Fix baseline QOH report dates range"

- grails-app/conf/BootStrap.groovy
- grails-app/i18n/messages.properties
- src/groovy/org/pih/warehouse/core/ActivityCode.groovy
- src/js/components/stock-movement-wizard/PickPage.jsx
- src/js/components/stock-movement-wizard/StockMovement.jsx
- src/js/reducers/sessionReducer.jsx
> OBPIH-2547 Disable pack page for locations withoug packing activity

- grails-app/controllers/org/pih/warehouse/inventory/StockMovementController.groovy
- grails-app/services/org/pih/warehouse/inventory/StockMovementService.groovy
- grails-app/views/stockMovement/_list.gsp
- grails-app/views/stockMovement/list.gsp
- grails-app/views/stockMovement/show.gsp
- src/groovy/org/pih/warehouse/api/StockMovement.groovy
* OBPIH-2769 Date Created is not visible on Lists of Stock Movements
* OBPIH-2768 Stock Movement filters are missing/not working
* OBPIH-2771 Fixed issues related to status filters and columns; fixed
> OBPIH-2753 Various fixes for bugs found during regression testing

- package-lock.json
- src/js/components/tablero/Tablero.jsx
- src/js/reducers/indicatorsReducer.jsx
Fixed dashboard page not rendering on multiple page reloads
> OBPIH-2744 Dashboard should refresh on location change

- grails-app/services/org/pih/warehouse/tableroapi/IndicatorDataService.groovy
Small fix: initialize expiration at 0 for months with no items expiring
> OBPIH-2512 Dashboard: Imminent expiry

- grails-app/services/org/pih/warehouse/tableroapi/IndicatorDataService.groovy
- src/js/components/tablero/Tablero.jsx
Fixes OBPIH-2509 and OBPIH-2503
> OBPIH-2509 Fix sent and incoming stock movements indicators

- grails-app/services/org/pih/warehouse/tableroapi/NumberDataService.groovy
Select only putaways for the current location
> OBPIH-2518 Dashboard: Current user incomplete Putaways

- grails-app/services/org/pih/warehouse/tableroapi/NumberDataService.groovy
- src/js/components/tablero/tablero.scss
This fixes both OBPIH-2518 and OBPIH-2781
> OBPIH-2518 Number card layout

- grails-app/conf/Config.groovy
- grails-app/controllers/org/pih/warehouse/core/OrganizationController.groovy
- grails-app/controllers/org/pih/warehouse/user/DashboardController.groovy
- grails-app/domain/org/pih/warehouse/core/Organization.groovy
- grails-app/i18n/messages.properties
- grails-app/services/org/pih/warehouse/core/IdentifierService.groovy
- grails-app/services/org/pih/warehouse/order/OrderService.groovy
- grails-app/views/organization/_filters.gsp
- grails-app/views/organization/edit.gsp
- grails-app/views/organization/list.gsp
- grails-app/views/partyRole/create.gsp
- src/groovy/org/pih/warehouse/core/Constants.groovy
- src/groovy/org/pih/warehouse/core/RoleType.groovy
The following tickets were implemented in this PR
* OBPIH-2735 Add required unique PO prefix to organization upon creation
* OBPIH-2736 Enable edit of PO prefix only if org has no associated POs
* OBPIH-2778 Auto-generate Po prefix
The following ticket will be completed in a separate PR 
* OBPIH-2737 Generate incremental order number using prefix&"PO"&00001
DO NOT SQUASH MERGE THIS PR
> Various tickets related to generation of PO sequence numbers

- grails-app/conf/BuildConfig.groovy
- grails-app/conf/Config.groovy
- grails-app/controllers/org/pih/warehouse/core/OrganizationController.groovy
- grails-app/controllers/org/pih/warehouse/order/OrderController.groovy
- grails-app/domain/org/pih/warehouse/core/Organization.groovy
- grails-app/domain/org/pih/warehouse/order/Order.groovy
- grails-app/migrations/0.8.x/changelog-2020-05-22-2235-create-table-organization-sequences.xml
- grails-app/migrations/0.8.x/changelog.xml
- grails-app/services/org/pih/warehouse/core/IdentifierService.groovy
- grails-app/services/org/pih/warehouse/order/OrderService.groovy
- grails-app/views/errors/notFound.gsp
- grails-app/views/order/_summary.gsp
- grails-app/views/organization/edit.gsp
- src/groovy/org/pih/warehouse/core/IdentifierGeneratorTypeCode.groovy
- src/groovy/org/pih/warehouse/core/IdentifierTypeCode.groovy
Reminder: Add database migration before merging.
> OBPIH-2737 Generate sequential identifier using configured format

- grails-app/conf/Config.groovy
- grails-app/conf/DataSource.groovy
- grails-app/controllers/org/pih/warehouse/apitablero/ApitableroController.groovy
- grails-app/controllers/org/pih/warehouse/tablero/TableroController.groovy
- grails-app/domain/org/pih/warehouse/core/User.groovy
- grails-app/services/org/pih/warehouse/core/UserService.groovy
- src/js/actions/index.js
- src/js/components/tablero/Tablero.jsx
- src/js/components/tablero/tablero.scss
Reverts openboxes/openboxes#1683
> Revert "OBPIH-2880 Dashboard should be customizable by user"

- src/js/actions/index.js
- src/js/components/tablero/Tablero.jsx
Fixes when updating configuration
> OBPIH-2880 Dashboard customizable by user

- grails-app/conf/Config.groovy
- grails-app/controllers/org/pih/warehouse/api/ApiController.groovy
- grails-app/controllers/org/pih/warehouse/apitablero/ApitableroController.groovy
- grails-app/services/org/pih/warehouse/tableroapi/IndicatorDataService.groovy
- grails-app/views/requisitionTemplate/_summary.gsp
- package-lock.json
- src/groovy/org/pih/warehouse/tablero/IndicatorDatasets.groovy
- src/js/actions/index.js
- src/js/components/tablero/GraphCard.jsx
- src/js/components/tablero/Tablero.jsx
- src/js/components/tablero/tablero.scss
- src/js/consts/dataFormat/graphConfig.jsx
- src/js/reducers/sessionReducer.jsx
As the location filter contains more things, we did it a bit in a different way. If this proposition is accepted, we will improve the responsiveness of this one. Else, we could think about making a pop up for this kind of "big" filter
> OBPIH 2519.  Dashboard: fill rate (Historical)

- src/js/components/tablero/tablero.scss
Vertically align fill rate indicators
> OBPIH-3110: Create Fill Rate left nav page

- grails-app/i18n/messages.properties
- grails-app/views/stockMovement/show.gsp
> OBPIH-3150 Disable edit for partially

- grails-app/migrations/views/product-substitution-status.sql
Reverts openboxes/openboxes#1896
> Revert "OBPIH-3166 Fix product substitution status view"

- grails-app/conf/Config.groovy
- grails-app/controllers/org/pih/warehouse/core/BudgetCodeController.groovy
- grails-app/domain/org/pih/warehouse/core/BudgetCode.groovy
- grails-app/domain/org/pih/warehouse/order/OrderAdjustment.groovy
- grails-app/domain/org/pih/warehouse/order/OrderItem.groovy
- grails-app/i18n/messages.properties
- grails-app/i18n/messages_ar.properties
- grails-app/i18n/messages_de.properties
- grails-app/i18n/messages_es.properties
- grails-app/i18n/messages_fi.properties
- grails-app/i18n/messages_fr.properties
- grails-app/i18n/messages_it.properties
- grails-app/i18n/messages_pt.properties
- grails-app/migrations/0.8.x/changelog-2020-09-18-1135-create-table-budget-code.xml
- grails-app/migrations/0.8.x/changelog-2020-09-18-1150-alter-table-add-column-budget-code-order-adjustment.xml
- grails-app/migrations/0.8.x/changelog-2020-09-18-1155-alter-table-add-column-budget-code-order-item.xml
- grails-app/migrations/0.8.x/changelog.xml
- grails-app/views/budgetCode/create.gsp
- grails-app/views/budgetCode/edit.gsp
- grails-app/views/budgetCode/list.gsp
- grails-app/views/dashboard/megamenu.gsp
@jmiranda I made migrations on my own (manually). If you want to have generated ones, then please remove them and generate on your end and commit on top of this pr.
> OBPIH-3183: Add budget code domain with crud ui

- grails-app/conf/Config.groovy
- grails-app/controllers/org/pih/warehouse/apitablero/ApitableroController.groovy
- grails-app/i18n/messages.properties
- grails-app/i18n/messages_fr.properties
- src/js/components/tablero/UnarchiveIndicators.jsx
- src/js/consts/dataFormat/graphConfig.jsx
fix of labels on the abscissa, the name on the table, the all destination and implementation of a method to fix the color problem
Also a fix of the preview indicator
> OBPIH-2939 : Localize all labels / messages in the dashboard UI.     Fix

- src/js/components/stock-movement-wizard/StockMovement.scss
- src/js/components/wizard/WizardSteps.scss
- Change header of table to bold.
- Change back steplist at the top of the page from bold to normal.
> Formatting Changes to Stock Movement Design

- src/js/components/stock-movement-wizard/outbound/AddItemsPage.jsx
- src/js/components/stock-movement-wizard/outbound/EditPage.jsx
- src/js/components/stock-movement-wizard/outbound/PackingPage.jsx
- src/js/components/stock-movement-wizard/outbound/SendMovementPage.jsx
The align left change has been removed
> OBPIH-3259 Formatting Changes to Stock Movement Design

- src/js/consts/dataFormat/graphConfig.jsx
Fix of the color problem on the expiration graph
> OBPIH-2939 Localize all labels / messages in the dashboard UI

- src/js/components/stock-movement-wizard/outbound/AddItemsPage.jsx
- src/js/components/stock-movement-wizard/outbound/EditPage.jsx
- src/js/components/stock-movement-wizard/outbound/PackingPage.jsx
- src/js/components/stock-movement-wizard/outbound/PickPage.jsx
Removed the stock movement info box on all pages except the "Send" page
> OBPIH-3260 Stock movement design header and page fit changes

- grails-app/conf/Config.groovy
- grails-app/i18n/messages.properties
- grails-app/i18n/messages_fr.properties
- src/js/components/stock-movement-wizard/StockMovementPurchaseOrders.jsx
> OBPIH-3261 Update breadcrumbs to show shipment number, not ID 

- grails-app/services/org/pih/warehouse/tableroapi/IndicatorDataService.groovy
Graph fill rate now going until last month and not current month
> Fill rate indicators showing this month not last month

- grails-app/services/org/pih/warehouse/tableroapi/IndicatorDataService.groovy
- src/js/actions/index.js
- src/js/components/tablero/Filter.jsx
- src/js/components/tablero/Tablero.jsx
- Filter management improved
- Filter configuration of every pages saved.
- Now able to send a list of categories
> Maintain filters on dashboard reload

- grails-app/conf/Config.groovy
- grails-app/controllers/org/pih/warehouse/inventory/StockMovementController.groovy
- grails-app/i18n/messages.properties
- grails-app/i18n/messages_fr.properties
- grails-app/services/org/pih/warehouse/inventory/StockMovementService.groovy
- src/js/components/Router.jsx
- src/js/components/form-elements/BaseField.jsx
- src/js/components/receiving/PartialReceivingPage.jsx
- src/js/components/receiving/ReceivingCheckScreen.jsx
- src/js/components/stock-movement-wizard/StockMovementVerifyRequest.jsx
- src/js/components/stock-movement-wizard/combined-shipments/SendMovementPage.jsx
- src/js/components/stock-movement-wizard/inbound/SendMovementPage.jsx
- src/js/components/stock-movement-wizard/outbound/SendMovementPage.jsx
- src/js/components/stock-movement-wizard/request/EditPage.jsx
- src/js/utils/Input.jsx
@awalkowiak I have an issue on this ticket regarding what you mentioned on Slack yesterday: when the disabled condition is set in `getDynamicAttr` the field does not get disabled even if the condition is true. Do you know why this is the case?
For example on the PartialReceivingPage, the checkboxes get disabled as well as the top Bin Location select (where the disabled is set directly), but not the other fields.
> OBPIH-3215 Receiving design update

- .github/workflows/unit-tests.yml
@jmiranda take a look. If you are happy with this, then I'll swap branch names. 
Also which branches we should target? Develop, master and perhaps release/0.8.14? Or any pull request that is being opened? Perhaps we want also corn schedule the tests for dev and master?
> OBS-493: Migrate to GitHub Actions

- grails-app/conf/Config.groovy
- grails-app/domain/org/pih/warehouse/product/ProductType.groovy
- grails-app/migrations/0.8.x/changelog-2021-04-06-1200-add-code-and-sequence-number-to-product-type.xml
- grails-app/migrations/0.8.x/changelog.xml
- grails-app/services/org/pih/warehouse/core/IdentifierService.groovy
- grails-app/services/org/pih/warehouse/product/ProductService.groovy
- grails-app/services/org/pih/warehouse/product/ProductTypeService.groovy
- grails-app/views/productType/create.gsp
- grails-app/views/productType/edit.gsp
- src/groovy/org/pih/warehouse/core/Constants.groovy
@jmiranda this requires the dateService cleanup done here: https://github.com/openboxes/openboxes/pull/2329 to be merged before this one
> OBPIH-3105 Enable autoincrement format on product code

- grails-app/controllers/org/pih/warehouse/order/OrderController.groovy
@jmiranda you're right there is no need for both `validate` and `hasErrors` in there. Save should be enough.
> OBPIH-3759 Remove unnecessary validation

- grails-app/domain/org/pih/warehouse/invoice/InvoiceItem.groovy
Issues with total adjustments price were fixed in this PR https://github.com/openboxes/openboxes/pull/2403
> OBPIH-3847 Fix issues with total price on prepayment invoice

- grails-app/domain/org/pih/warehouse/invoice/InvoiceItem.groovy
Reverting openboxes/openboxes#2414 because it was already fixed.
> Revert "OBPIH-3847 Fix issues with total price on prepayment invoice"

- grails-app/services/org/pih/warehouse/inventory/StockMovementService.groovy
- src/groovy/org/pih/warehouse/api/StockMovement.groovy
- src/js/components/stock-movement-wizard/request/AddItemsPage.jsx
- src/js/components/stock-movement-wizard/request/CreateStockMovement.jsx
- src/js/components/stock-movement-wizard/request/EditPage.jsx
and selected stocklist field first page of wizard
> OBAM-117 Fix demand per replenishment period calculation

- grails-app/controllers/org/pih/warehouse/JsonController.groovy
- grails-app/controllers/org/pih/warehouse/inventory/InventoryController.groovy
- grails-app/domain/org/pih/warehouse/product/Product.groovy
- grails-app/services/org/pih/warehouse/inventory/InventoryService.groovy
- grails-app/services/org/pih/warehouse/inventory/ProductAvailabilityService.groovy
- grails-app/views/inventory/list.gsp
> OBAM-157 Add quantity available to promise to global search and inventory report

- grails-app/views/report/showBinLocationReport.gsp
- grails-app/views/stockMovement/_packingList.gsp
- src/css/main.scss
- src/js/components/stock-movement-wizard/outbound/SendMovementPage.jsx
Plus minor label change for the OBAM-156
> OBAM-148 Unify color of recalled rows

- grails-app/controllers/org/pih/warehouse/MobileController.groovy
- grails-app/services/org/pih/warehouse/integration/TripNotificationEventService.groovy
- src/groovy/org/pih/warehouse/integration/TripNotificationEvent.groovy
- src/java/org/pih/warehouse/integration/xml/trip/Orders.java
- src/java/org/pih/warehouse/integration/xml/trip/Trip.java
- src/java/org/pih/warehouse/integration/xml/trip/TripOrderDetails.java
- src/java/org/pih/warehouse/integration/xml/trip/jaxb.index
- src/java/org/pih/warehouse/integration/xml/trip/package-info.java
- src/java/org/pih/warehouse/integration/xml/trip/trip_notification_v1.xsd
Receive tracking number from eTruckNow
> OBKN-47 Receive tracking number from eTruckNow

- grails-app/conf/UrlMappings.groovy
- grails-app/controllers/org/pih/warehouse/api/ProductApiController.groovy
Global search of product from barcode
> OBKN-55 Allow a user to scan a barcode to retrieve details for a product

- grails-app/controllers/org/pih/warehouse/MobileController.groovy
- grails-app/views/mobile/outboundList.gsp
No date picker has been used. Manual text date input in the format MM-dd-yyyy for now.
> OBKN-112 Allow an OC stakeholder to filter outbound orders by venue

- README.md
> OBDS-61 Add link to the Confluence page about push-button deployment

- grails-app/conf/Config.groovy
- grails-app/domain/org/pih/warehouse/product/Product.groovy
- grails-app/services/org/pih/warehouse/integration/TmsIntegrationService.groovy
- grails-app/views/stockMovement/show.gsp
- src/groovy/org/pih/warehouse/api/StockMovement.groovy
- src/groovy/org/pih/warehouse/api/StockMovementItem.groovy
* OBKN-70 Send pallet dimensions as updated order to eTruckNow
* OBKN-211 Assign PlannedDateTime relative to expected delivery date
> Various tickets related to delivery order integration message

- grails-app/services/org/pih/warehouse/inventory/StockMovementService.groovy
OBKN-317 Unable to create stock movement on server side
> OBKN-317 Unable to create stock movement on server side

- grails-app/conf/Config.groovy
- grails-app/conf/UrlMappings.groovy
- grails-app/controllers/org/pih/warehouse/shipping/ContainerApiController.groovy
- grails-app/domain/org/pih/warehouse/shipping/Container.groovy
- grails-app/services/org/pih/warehouse/shipping/ShipmentService.groovy
OBKN-268 Generate unique container number based on identifier format
> OBKN-268 Generate unique container number based on identifier format

- grails-app/domain/org/pih/warehouse/product/ProductAvailability.groovy
- src/groovy/org/pih/warehouse/api/StockTransferItem.groovy
Reverts openboxes/openboxes#2825
> Revert "OBPIH-4153 Corrected displaying wrong qty to return/transfer after mo…"

- grails-app/conf/BuildConfig.groovy
- grails-app/controllers/org/pih/warehouse/order/OrderController.groovy
- grails-app/services/org/pih/warehouse/order/OrderService.groovy
- src/groovy/org/pih/warehouse/importer/CSVUtils.groovy
Two late-breaking fixes for the upcoming release:
1. Use CSVPrinter, not CSVWriter, to better handle commas and non-ASCII characters.
2. Improve logging on PO csv parse errors.
> OBPIH-4193 CSV I/O improvements

- grails-app/conf/BuildConfig.groovy
- grails-app/conf/Config.groovy
- grails-app/conf/SecurityFilters.groovy
- grails-app/conf/UrlMappings.groovy
- grails-app/controllers/org/pih/warehouse/notification/NotificationController.groovy
T2. Create endpoint for product creation and product update
T3. Create endpoint for order creation messages
Jar file is not committed because its 203 MB and we cannot push more than 100 mb
> OBDX-7 Create endpoint for product creation and product update

- grails-app/conf/UrlMappings.groovy
- grails-app/controllers/org/pih/warehouse/notification/NotificationController.groovy
- src/groovy/util/StringUtil.groovy
OBDX-21 T3. Create endpoint for order creation messages
> OBDX-21 T3. Create endpoint for order creation messages

- package-lock.json
Another vulnerability found while investigating log4j.
> OBPIH-4216 Update json-schema to fix a critical security vulnerability.

- package-lock.json
Another vulnerability found while investigating log4j.
> OBPIH-4215 Update handlebars to fix a critical security vulnerability.

- grails-app/services/org/pih/warehouse/product/ProductService.groovy
- test/integration/org/pih/warehouse/product/ProductNotificationTests.groovy
Fixed bug for creating product and product attributes from SNS.
> OBDX-7-bugfixes-and-integration-tests

- grails-app/services/org/pih/warehouse/product/ProductService.groovy
- test/integration/org/pih/warehouse/product/ProductNotificationTests.groovy
OBDX-29 Create product components off product message
> OBDX-29 Create product components off product message

- grails-app/conf/Config.groovy
- grails-app/services/org/pih/warehouse/product/ProductService.groovy
- test/integration/org/pih/warehouse/product/ProductNotificationTests.groovy
OBDX-26 Use external product ID as mapping key between systems
> OBDX-26 Use external product ID as mapping key between systems

- grails-app/conf/BuildConfig.groovy
- grails-app/jobs/org/pih/warehouse/jobs/PersistenceContextJobListener.groovy
- scripts/_Events.groovy
- src/groovy/org/pih/warehouse/log4j/net/DynamicSubjectSMTPAppender.groovy
- src/groovy/util/LiquibaseUtil.groovy
Reverts openboxes/openboxes#2861
> Revert "OBPIH-4218 Update to a (more) secure fork of log4j."

- grails-app/services/org/pih/warehouse/inventory/RefreshProductAvailabilityEventService.groovy
- grails-app/services/org/pih/warehouse/product/ProductService.groovy
T4. Product availability integration
> T4. Product availability integration

- grails-app/conf/BuildConfig.groovy
- grails-app/migrations/0.8.x/changelog-2022-01-03-1524-configure-invoice-templates.xml
Hi Artur, I think with these build changes your OBAM-308 work should compile and deploy cleanly. I thought it was easier to make a PR than to explain the nitty-gritty details on your existing PR! cheers, M
> OBAM-308 Clean up dependencies.

- grails-app/services/org/pih/warehouse/inventory/RefreshProductAvailabilityEventService.groovy
- grails-app/services/org/pih/warehouse/product/ProductService.groovy
- grails-app/services/org/pih/warehouse/report/NotificationService.groovy
Moved method in Notification service from Product service
> OBDX-13 moved method into Notification service

- grails-app/controllers/org/pih/warehouse/notification/OrderNotificationController.groovy
OBDX-26 READING PRODUCT FROM EXTERNAL ID
> OBDX-26 Use external product ID for order integration

- grails-app/views/stocklist/_itemList.gsp
It's deploying to stg presently; assuming it builds and deploys cleanly, I'd like to release this at around 7PM EST
> Merge 0.8.17-hotfix3 to master

- grails-app/services/org/pih/warehouse/inventory/ProductAvailabilityService.groovy
- grails-app/services/org/pih/warehouse/inventory/StockMovementService.groovy
- grails-app/services/org/pih/warehouse/stockTransfer/StockTransferService.groovy
- grails-app/views/stocklist/_itemList.gsp
Hey Justin, it looks like like three hotfix commits aren't in develop. This PR is a merge of master into develop, followed by a rebase, yielding 3 commits. But we could do a regular merge if you want to preserve the merge history. What's your preferred way to sync the changes?
> Merge hotfixes back to develop.

- src/js/components/dashboard/Dashboard.scss
modified archived indicator popover to open from the bottom instead of from the top
> OBPIH-4282 - open archived indicator popover from the bottom

- grails-app/services/org/pih/warehouse/core/LocationService.groovy
- src/js/components/locations-configuration/ZoneTable.jsx
Added the improvement to be able to fetch also inactive locations.
> OBDS-104 Zone and Bin: Zone modal

- grails-app/conf/BootStrap.groovy
- grails-app/controllers/org/pih/warehouse/api/LocationApiController.groovy
- grails-app/i18n/messages.properties
- package-lock.json
- src/js/components/Router.jsx
- src/js/components/locations-configuration/LocationAddress.jsx
- src/js/components/locations-configuration/LocationDetails.jsx
- src/js/utils/translation-utils.jsx
With the problems I had with the previous branch (OBPIH-4345) with conflicts and rebasing, I created a new one OBPIH-4345-new and making PR on that, because when trying to push changes from OBPIH-4345-new to OBPIH-4345, the conflicts were still appearing.
> OBPIH-4345-new: User cannot continue work in location configuration after page reload

- grails-app/i18n/messages.properties
- src/js/components/locations-configuration/BinTable.jsx
- src/js/components/locations-configuration/Forecasting.jsx
- src/js/components/locations-configuration/ForecastingNotsupported.jsx
- src/js/components/locations-configuration/LocationAddress.jsx
- src/js/components/locations-configuration/LocationDetails.jsx
- src/js/components/locations-configuration/SuccessMessage.jsx
- src/js/components/locations-configuration/SuccessMessage.scss
- src/js/components/locations-configuration/ZoneAndBinLocations.jsx
- src/js/components/locations-configuration/ZoneTable.jsx
From 1366x768 the scroll doesn't appear and the message is fully covered from that resolution. It's natural that when you decrease the height below that, the scroll has to appear at sometime.
> OBPIH-4350: Location configuration improvements

- grails-app/i18n/messages.properties
- src/js/components/form-elements/LabelField.jsx
- src/js/components/replenishment/CreateReplenishment.jsx
- src/js/components/replenishment/EditPickModal.jsx
- src/js/components/replenishment/ReplenishmentCheckPage.jsx
- src/js/components/replenishment/ReplenishmentSecondPage.jsx
- changed table column text alignment
- added tooltip to product name
- added label to select filter
> OBAM-313 UI changes to bin replenishment feature

- grails-app/conf/Config.groovy
- grails-app/services/org/pih/warehouse/api/MegamenuService.groovy
- grails-app/taglib/org/pih/warehouse/AuthTagLib.groovy
- grails-app/views/common/_menu.gsp
- grails-app/views/dashboard/megamenu.gsp
- src/groovy/org/pih/warehouse/core/ActivityCode.groovy
- src/js/actions/index.js
- src/js/components/location/LocationChooser.jsx
Disable Stock Transfer and Replenishment workflows in locations without bin tracking
> OBAM-310 Disable Stock Transfer and Replenishment workflows in locations without bin tracking

- src/groovy/org/pih/warehouse/inventory/InventoryLevelStatus.groovy
> OBAM-312 Removed ABOVE_MAXIMUM from options

- grails-app/services/org/pih/warehouse/order/OrderService.groovy
https://pihemr.atlassian.net/browse/OBAM-325
> OBAM-325 Ignore 0's when updating product source item price in Purchase Order

- grails-app/i18n/messages.properties
- grails-app/services/org/pih/warehouse/inventory/StockMovementService.groovy
- src/js/components/stock-movement-wizard/request/AddItemsPage.jsx
Requests from ward should change based on push or pull stock list
> OBAM-326 Requests from ward should change based on push or pull stock list

- grails-app/services/org/pih/warehouse/dashboard/IndicatorDataService.groovy
plus fix year intervals processing
> OBAM-321 Remove requisition templates from results

- grails-app/i18n/messages.properties
- src/js/components/stock-movement-wizard/request/AddItemsPage.jsx
https://pihemr.atlassian.net/browse/OBAM-326
> OBAM-326 Requests from ward should change based on push or pull stocklist like other requests (REOPENED)

- grails-app/conf/Config.groovy
- grails-app/views/dashboard/megamenu.gsp
It seems like "New report section not visible in GSP" has been done by Hubert, but it has been done after the ticket was created, so that's probably why this dot exists in the ticket.
> OBPIH-4383 Fix menu inconsistencies between React and GSP

- grails-app/views/stockMovement/show.gsp
- src/js/components/stock-movement-wizard/request/AddItemsPage.jsx
- src/js/components/stock-movement-wizard/request/EditPage.jsx
https://pihemr.atlassian.net/browse/OBPIH-4401
> OBPIH-4401 Hide inbound list when logged to ward

- grails-app/services/org/pih/warehouse/replenishment/ReplenishmentService.groovy
https://pihemr.atlassian.net/browse/OBAM-361
> OBAM-361 Hide lines with qty=0 after edit pick replenishment

- grails-app/controllers/org/pih/warehouse/inventory/ReplenishmentController.groovy
- grails-app/i18n/messages.properties
- grails-app/views/replenishment/_printPage.gsp
- grails-app/views/replenishment/print.gsp
- src/js/components/replenishment/ReplenishmentSecondPage.jsx
https://pihemr.atlassian.net/browse/OBAM-314
- Implement the same PDF printout that is available for a stock transfer with picklist
- Add button for “Print Transfer Order” to pick page
> OBAM-314 Generate a transfer order PDF

- grails-app/i18n/messages.properties
- src/js/components/dashboard/StockRequestDashboard.jsx
- src/js/components/stock-movement-wizard/request/AddItemsPage.jsx
https://pihemr.atlassian.net/browse/OBPIH-4402
> OBPIH-4402 Add success message after submit request when logged to ward

- grails-app/controllers/org/pih/warehouse/inventory/ReplenishmentController.groovy
- grails-app/views/replenishment/_printPage.gsp
- grails-app/views/replenishment/print.gsp
https://pihemr.atlassian.net/browse/OBAM-314
- added expiration date and lot number to print
- fixed grouping items by zone bug
> OBAM-314 Fixed group items by zones

- grails-app/views/replenishment/_printPage.gsp
I forgot to swap headers when I swapped cells
> OBAM-314 Swap lot and expiry date headers

- grails-app/controllers/org/pih/warehouse/reporting/ConsumptionController.groovy
- grails-app/services/org/pih/warehouse/inventory/InventoryService.groovy
- grails-app/views/consumption/show.gsp
> OBAM-271 Fix credit from inbound returns on the Consumption Report

- grails-app/views/replenishment/_printPage.gsp
based on the request changes after UAT https://pihemr.atlassian.net/browse/OBAM-314?focusedCommentId=132417
changed the order of few columns to fix the format of _bin replenishment_ PDF to be the same as the _stock transfer_ PDF
> OBAM-314 Fix bin replenishment table format

- grails-app/controllers/org/pih/warehouse/api/StockTransferApiController.groovy
It turned out that the problem was with the lotNumber, as it was considered as "null" (string of null) which was actually not null, but JSONObject.NULL which caused problems, because the method from inventoryService was expecting String.
> OBPIH-4421 Unable to go from pick to send page in outbound return

- src/js/components/replenishment/EditPickModal.jsx
https://pihemr.atlassian.net/browse/OBAM-366
- do not set pick value for bins that are NOT_AVAILABLE
- fix validation bug, check if quantityPicked is a number
> OBAM-366 Fix unable to manualy change pick when selected bin is NOT_AVAILABLE in EditPick

- grails-app/controllers/org/pih/warehouse/inventory/StockTransferController.groovy
- grails-app/i18n/messages.properties
Disable editing return from locations that are not origin or destination
> OBPIH-4434 Disable editing return from other locations

- application.properties
- grails-app/controllers/org/pih/warehouse/order/OrderController.groovy
Hi folks,
These changes have been soaking in develop for a while. Kelsey's requested they go out as a hotfix.
> OBPIH-4377 Excel download order shows wrong vendor and manu codes

- grails-app/domain/org/pih/warehouse/core/User.groovy
- grails-app/taglib/org/pih/warehouse/AuthTagLib.groovy
- grails-app/views/taglib/_displayLogo.gsp
~Should be merged to a new hotfix release branch.~
Disregard, I'm just going to deploy commit 302487cd91fd2c4947115aadc5fe555478463545 to OBNAVSTAGE and if that succeeds then I'll merge to master and bump the app version to hotfix1.
> OBS-1176 GrailsTagException: Error executing tag <g:render>

- .github/workflows/unit-tests.yml
- test/unit/org/pih/warehouse/api/ApiControllerTests.groovy
This PR fixes a test initialization error that affects my local instance but not GHA, and incorporates GHA improvements from the [integration tests PR](https://github.com/openboxes/openboxes/pull/3367).
> OBPIH-4603 unit test fixes

- grails-app/migrations/views/order-summary-view.sql
- properly exclude non posted invoices
- fix status of order with adjustments only
- quantity received should be divided by qty per uom to be in uom
> OBPIH-3860 Fixes to the invoiced quantity calculation

- grails-app/migrations/views/order-summary-view.sql
- add ifnulls in base views
- fix calculating adjustments status with non posted invoices
> OBPIH-3860 Minor improvements to order summary view

- application.properties
- grails-app/conf/Config.groovy
- grails-app/conf/RoleFilters.groovy
- grails-app/controllers/org/pih/warehouse/JsonController.groovy
- grails-app/controllers/org/pih/warehouse/api/CombinedShipmentItemApiController.groovy
- grails-app/controllers/org/pih/warehouse/api/StockMovementApiController.groovy
- grails-app/controllers/org/pih/warehouse/invoice/InvoiceController.groovy
- grails-app/controllers/org/pih/warehouse/order/OrderController.groovy
- grails-app/domain/org/pih/warehouse/order/Order.groovy
- grails-app/i18n/messages.properties
- grails-app/migrations/views/order-summary-view.sql
- grails-app/services/org/pih/warehouse/core/LocationService.groovy
- grails-app/services/org/pih/warehouse/core/UserService.groovy
- grails-app/services/org/pih/warehouse/data/LocationDataService.groovy
- grails-app/services/org/pih/warehouse/data/ProductSupplierDataService.groovy
- grails-app/services/org/pih/warehouse/inventory/StockMovementService.groovy
- grails-app/services/org/pih/warehouse/order/OrderService.groovy
- grails-app/taglib/org/pih/warehouse/SelectTagLib.groovy
- grails-app/views/errors/accessDenied.gsp
- grails-app/views/location/list.gsp
- grails-app/views/locationRole/_form.gsp
- grails-app/views/order/_itemDetails.gsp
- grails-app/views/order/_itemStatus.gsp
- grails-app/views/order/_orderSummary.gsp
- grails-app/views/order/_summary.gsp
- grails-app/views/order/list.gsp
- grails-app/views/order/show.gsp
- src/groovy/org/pih/warehouse/shipping/ShipmentStatusCode.groovy
- src/js/components/locations-configuration/SuccessMessage.jsx
- src/js/components/put-away/PutAwaySecondPage.jsx
@awalkowiak this PR contains things from the release/0.8.19 branch that are now in master, but are not in develop. They probably should be.
> Merge master (0.8.19) to develop and set app.version to 0.8.20-SNAPSHOT

- src/js/components/location/LocationChooser/LocationChooserModal/LocationChooserModal.scss
Make height of the location chooser more dynamic to the window size
> OBPIH-4705 Location chooser height fix

- grails-app/conf/Config.groovy
- grails-app/conf/spring/resources.groovy
- grails-app/domain/org/pih/warehouse/picklist/PicklistItem.groovy
- grails-app/domain/org/pih/warehouse/requisition/RequisitionItem.groovy
- grails-app/jobs/org/pih/warehouse/jobs/RefreshProductAvailabilityJob.groovy
- grails-app/services/org/pih/warehouse/inventory/ProductAvailabilityService.groovy
- grails-app/services/org/pih/warehouse/inventory/RefreshProductAvailabilityEventService.groovy
- src/groovy/org/pih/warehouse/inventory/RefreshProductAvailabilityEvent.groovy
I broke this down into multiple commits in case we wanted to cherry-pick commits for a hotfix from these candidates. Given that the issue hasn't recurred in a week (or two?), we should test this on obdev for a few days before pushing a hotfix to obnavstage.
> OBPIH-4686 Investigate why product availability issue requires intermittent reboots

- grails-app/controllers/org/pih/warehouse/api/StocklistApiController.groovy
- src/css/main.scss
- src/js/components/Layout/HeaderStyles.scss
- src/js/components/stock-list/StockListFilters.jsx
- src/js/components/stock-list/StockListHeader.jsx
- src/js/utils/ActionDots.jsx
- added meaningful error when try to delete stocklist already included in stock movement
- changed search filter placeholder
- set default state of filter as expanded
- hide add stocklist button for non Admin users
> OBPIH-4773 stocklist list page fixes

- build.gradle
- grails-app/controllers/org/pih/warehouse/product/ProductController.groovy
- grails-app/controllers/org/pih/warehouse/shipping/ShipmentController.groovy
- grails-app/services/org/pih/warehouse/product/BarcodeService.groovy
- grails-app/views/shipment/_barcodeLabel.gsp
`barcode4j` has gone a decade without maintenance and we are using another equally-functional barcode generator (`zxing`) elsewhere in the codebase.
> OBGM-326 Remove barcode4j dependency.

- build.gradle
- gradle.properties
- grails-app/conf/application.yml
- grails-app/conf/logback.xml
- grails-app/controllers/org/pih/warehouse/requisition/RequisitionController.groovy
- grails-app/controllers/org/pih/warehouse/shipping/CreateShipmentWorkflowController.groovy
- grails-app/controllers/org/pih/warehouse/user/DashboardController.groovy
- grails-app/init/org/pih/warehouse/BootStrap.groovy
- grails-app/migrations/changelog.groovy
- grails-app/migrations/upgrade/changelog.xml
- grails-app/services/org/pih/warehouse/inventory/InventoryService.groovy
- package-lock.json
- package.json
- webpack.config.js
This is the code that's running on obnavtest1.
- resolve Gradle build warnings (OBGM-349)
- fix GSP/asset-pipeline conflicts (OBGM-353)
- prevent TransactionRequiredException on Dashboard load (OBGM-355)
- set up logging (OBGM-356)
- run hibernate migrations successfully from within Tomcat
- configure connection pooling
- remove stale Hibernate 3 references in favor of 5.2
- bump Grails to 3.3.16 and update other dependencies
> OBGM-353 warfile fixes and other improvements

- package-lock.json
- src/groovy/org/pih/warehouse/api/StockMovement.groovy
I'm wondering if it's somehow possible to "inject" `def userService` like we do everywhere, so just using `def userService` at the top of file?
I had hard time to find how to use the `UserService` here, because using method like `UserService.someMethod()` didn't want to work.
@awalkowiak ?
> OBPIH-4932 Unable to delete request as superuser

- grails-app/i18n/messages.properties
- src/js/components/invoice/InvoiceListTable.jsx
- src/js/components/products/ProductsListTable.jsx
- src/js/components/purchaseOrder/PurchaseOrderList.jsx
- src/js/components/purchaseOrder/PurchaseOrderListTable.jsx
- src/js/components/stock-movement/inbound/StockMovementInboundTable.jsx
- src/js/components/stock-movement/outbound/StockMovementOutboundTable.jsx
- src/js/components/stock-transfer/list/StockTransferListTable.jsx
I also fixed PO page, because when moving all the filter logic to `PurchaseOrderList`, the destination when changing location didn't change - it always stayed the same, because when we initially go to the PO page, we pass our current location as destination in the URL, but when changing location, the queryParams didn't change and this part:
```
if (queryProps.destination) {
defaultValues.destination = props.currentLocation.id === queryProps.destination
? currentLocationOption
: await fetchLocationById(queryProps.destination);
}
```
always took initially set destination from URl so it had to be changed to: 
`await fetchLocationById(props.currentLocation?.id);`
it was agreed with Katarzyna and me that I would fix it while doing this ticket, just wanted to explain it if you were wondering, …
> OBPIH-4914 Errors with loading / fetching redesigned list pages

- grails-app/views/dashboard/chooseLocation.gsp
after location chooser redesign message element was lost in the process
> OBPIH-5023 Bring back error/validation message element on login location chooser view

- grails-app/controllers/org/pih/warehouse/api/StockMovementApiController.groovy
- grails-app/domain/org/pih/warehouse/receiving/Receipt.groovy
- grails-app/domain/org/pih/warehouse/shipping/Shipment.groovy
- grails-app/domain/org/pih/warehouse/shipping/ShipmentItem.groovy
- grails-app/services/org/pih/warehouse/inventory/StockMovementService.groovy
- grails-app/services/org/pih/warehouse/receiving/ReceiptService.groovy
- grails-app/services/org/pih/warehouse/shipping/ShipmentService.groovy
- src/js/components/stock-movement-wizard/combined-shipments/AddItemsPage.jsx
Improvements to get rid of dead lock issues related to multiple Order Summary refresh events for the same order
> OBPIH-5025 Improve Order Summary refreshing

- grails-app/services/org/pih/warehouse/core/UserService.groovy
> OBPIH-5031 Clone dashboard config to not overwrite the default values

- src/js/components/stock-movement-wizard/combined-shipments/AddItemsPage.jsx
> OBAM-388 Fix users can't save PO shipment when lot and expiry date is empty

- grails-app/controllers/org/pih/warehouse/api/ProductApiController.groovy
- grails-app/views/tag/_summary.gsp
plus add tag into exported file name
> OBPIH-5030 Hide export button if tag has no products

- src/js/components/stock-movement-wizard/request/AddItemsPage.jsx
(request from ward = location without manage inventory, but with submit request activity code)
> OBPIH-5137 Make quantity on hand not required on request from ward

- grails-app/conf/Config.groovy
- grails-app/controllers/org/pih/warehouse/inventory/StockMovementController.groovy
- grails-app/views/stockMovement/_actions.gsp
- grails-app/views/stockMovement/show.gsp
- src/js/components/stock-movement-wizard/request/AddItemsPage.jsx
- when deleting request from ward redirect to dashboard
- set minimum required role for request deletion to Assistant
> OBPIH-5136  Enable deletion of a stock request

- grails-app/services/org/pih/warehouse/inventory/StockMovementService.groovy
- src/js/components/stock-movement-wizard/request/AddItemsPage.jsx
the problem with saving occured, because there was `quantityRequested` missing for one of many cases when returning `stockMovementItems` when updating items.
> OBPIH-5138 Broken request from ward save when using stocklist + fixes after QA 

- src/js/components/Filter/FilterForm.jsx
Check for disabled filter attribute in dynamicAttributes
> OBPIH-5165 Fix selected filter badge counter for Central Purchasing locations

- grails-app/controllers/org/pih/warehouse/user/DashboardController.groovy
- grails-app/views/common/_menuicons.gsp
- web-app/css/openboxes.css
- hide configuration menu icon if config menu is not available for the user
- remove configuration section only if index is > 0
> OBPIH-5013 Fix megamenu configuration section breaking

- grails-app/i18n/messages.properties
- src/groovy/org/pih/warehouse/product/ProductAssociationTypeCode.groovy
> Revert "OBPIH-5169 Add Family as an association type"

- build.gradle
- grails-app/conf/logback.xml
@drodzewicz Here's the patch I was talking about.
I'm making a separate PR (#3703) with all the build changes I tried before stumbling on this!
> OBGM-372 Resolve root cause of renderPdf's ClassNotFoundException.

- grails-app/services/org/pih/warehouse/report/ReportService.groovy
> OBPIH-5191.2 Fix regression by restoring an import deleted in error.

- grails-app/controllers/org/pih/warehouse/api/StockMovementApiController.groovy
- grails-app/controllers/org/pih/warehouse/api/StockTransferApiController.groovy
- grails-app/services/org/pih/warehouse/shipping/ShipmentService.groovy
- src/js/components/stock-movement-wizard/modals/SubstitutionsModal.jsx
- src/js/components/stock-movement-wizard/outbound/AddItemsPage.jsx
- src/js/components/stock-movement-wizard/outbound/PackingPage.jsx
- src/js/components/stock-movement-wizard/outbound/PickPage.jsx
- src/js/components/stock-movement-wizard/outbound/SendMovementPage.jsx
- src/js/components/stock-movement-wizard/request/AddItemsPage.jsx
- refactor some payloads to have a normal instead of flattened object structure
- use apiClient on Packing Picking and Send movement for outbound workflow
> OBGM-390 Fix errors on certain steps on stock movement screation workflow

- grails-app/controllers/org/pih/warehouse/reporting/ReportController.groovy
pass methods as parameters using method reference operator
> OBGM-387 Fix binLocation report export crashing

- grails-app/services/org/pih/warehouse/inventory/InventoryService.groovy
- grails-app/services/org/pih/warehouse/product/ProductMergeService.groovy
and improve moving transaction entries
> OBPIH-5237 Fix getting distinct transactions by inventory

- grails-app/i18n/messages_es.properties
- grails-app/i18n/messages_fr.properties
- grails-app/i18n/messages_ht.properties
- grails-app/i18n/messages_pt.properties
- grails-app/views/consumption/_filters.gsp
- grails-app/views/report/showTransactionReport.gsp
- src/js/components/dashboard/GraphCard.jsx
- Fix single quotes on translation label for Select options
- Modify label for other languages for next and Last
- Fix wrong label on plural months option
> Obpih 5207 Fix "Next" and "Later" labels for other languages 

- grails-app/conf/BootStrap.groovy
- grails-app/domain/org/pih/warehouse/requisition/RequisitionItem.groovy
- grails-app/taglib/org/pih/warehouse/TranslatedProductNameTagLib.groovy
- grails-app/views/inventory/browse.gsp
- grails-app/views/inventoryItem/_editItemDialog.gsp
- grails-app/views/inventoryItem/_showProductAssociations.gsp
- grails-app/views/inventoryItem/_showRecordInventory.gsp
- grails-app/views/inventoryLevel/_form.gsp
- grails-app/views/product/_productAssociations.gsp
- grails-app/views/product/_productPackageDialog.gsp
- grails-app/views/product/_summaryDialog.gsp
- grails-app/views/productAssociation/_dialog.gsp
- grails-app/views/requisition/_showRequisitionItem.gsp
- grails-app/views/requisitionTemplate/edit.gsp
- grails-app/views/requisitionTemplate/show.gsp
- grails-app/views/stockMovement/_packingList.gsp
- grails-app/views/stockMovement/_receipts.gsp
- grails-app/views/taglib/_translatedProductName.gsp
- src/js/components/products/ProductsListTable.jsx
Translation of product name added to:
- product associations tab
- record stock
- edit product > details tab
- edit product > inventory levels > create inventory level modal : name in header
- edit product > inventory levels > create inventory level modal : name in “product” row
- edit product > product associations tab
- edit product > product associations tab > create product association modal : product name
- edit product > product associations tab > create product association modal : name of the associated product
- edit product > product packages tab > create product package modal : name of the product
- manage lot numbers > edit item modal : name in “product” row
- stocklist view page
- stocklist add items page
- browse inventory
- shipment view page (request details, packing list, …
> OBPIH-5336 Add translations of product name (part 2)

- grails-app/controllers/org/pih/warehouse/JsonController.groovy
- grails-app/services/org/pih/warehouse/data/DataService.groovy
- grails-app/views/taglib/_autoSuggest.gsp
Additionally:
- fixed an issue (NullPointerException) we discovered today for the Export inventory levels
> OBPIH-5399 Add product translation to autosuggest/autocomplete on GSP pages

- grails-app/controllers/org/pih/warehouse/shipping/ShipmentController.groovy
- grails-app/services/org/pih/warehouse/core/FileService.groovy
- grails-app/views/deliveryNote/_printPage.gsp
- grails-app/views/goodsReceiptNote/_body.gsp
- grails-app/views/inventoryItem/_showStockHistoryPrintable.gsp
- grails-app/views/order/print.gsp
- grails-app/views/picklist/_printPage.gsp
- grails-app/views/picklist/_returnPage.gsp
- grails-app/views/picklist/_returnPrintPage.gsp
- grails-app/views/putAway/_print.gsp
- grails-app/views/report/printPaginatedPackingListReport.gsp
- grails-app/views/report/printPickListReport.gsp
- grails-app/views/report/printShippingReport.gsp
- grails-app/views/stocklist/_itemList.gsp
- src/groovy/org/pih/warehouse/api/PutawayItem.groovy
use product translateName on:
- picklist
- delivery note
- goods and receipt
- print order
- stocklist
- generate putaway list
- packing list
- all other template documents that use fileService
> OBPIH-5338 Use translated product name on pdf files

- grails-app/domain/org/pih/warehouse/invoice/InvoiceItem.groovy
- grails-app/domain/org/pih/warehouse/invoice/InvoiceItemCandidate.groovy
- grails-app/views/invoice/_invoiceItems.gsp
- src/js/components/invoice/AddItemsPage.jsx
- src/js/components/invoice/ConfirmInvoicePage.jsx
- src/js/components/invoice/InvoiceItemsModal.jsx
Added product translations for:
- invoice view page
- invoice add items page, confirm page
- included for prepayment invoice, regular invoice, final invoice
> OBPIH-5413 Add product translations for invoices

- grails-app/controllers/org/pih/warehouse/reporting/ReportController.groovy
- grails-app/views/report/showCycleCountReport.gsp
┆Issue is synchronized with this [Trello card](https://trello.com/c/Jf8ZA3L7) by [Unito](https://www.unito.io)
> OBPIH-5447 Add product family to Cycle count report

- grails-app/services/org/pih/warehouse/product/ProductService.groovy
- src/groovy/org/pih/warehouse/core/Constants.groovy
┆Issue is synchronized with this [Trello card](https://trello.com/c/c12uUOqz) by [Unito](https://www.unito.io)
> OBPIH-5284 Add product family to product export

- grails-app/conf/BootStrap.groovy
- grails-app/domain/org/pih/warehouse/product/Product.groovy
- grails-app/utils/org/pih/warehouse/util/LocalizationUtil.groovy
- test/unit/org/pih/warehouse/core/SynonymTests.groovy
┆Issue is synchronized with this [Trello card](https://trello.com/c/Uxmf1jCq) by [Unito](https://www.unito.io)
> OBPIH-5481 Refactor product API to handle localized product names

- grails-app/services/org/pih/warehouse/inventory/StockMovementService.groovy
- src/groovy/org/pih/warehouse/order/RefreshOrderSummaryEvent.groovy
plus remove one unnecessary save while creating shipment for PO
> OBS-1422 Don't refresh order summary for prepayment invoices

- grails-app/controllers/org/pih/warehouse/api/CombinedShipmentItemApiController.groovy
- grails-app/domain/org/pih/warehouse/invoice/Invoice.groovy
- grails-app/services/org/pih/warehouse/inventory/StockMovementService.groovy
- grails-app/services/org/pih/warehouse/invoice/InvoiceService.groovy
- grails-app/services/org/pih/warehouse/shipping/CombinedShipmentService.groovy
- src/groovy/org/pih/warehouse/order/RefreshOrderSummaryEvent.groovy
- on creating combined shipments
- on adding or importing items to combined shipments
- on removing items from combined shipments
- on adding items to invoice
- on removing items from invoice
> OBS-1363 Disable unnecessary order summary refreshes

- grails-app/controllers/org/pih/warehouse/api/CombinedShipmentItemApiController.groovy
- src/js/components/form-elements/LabelField.jsx
- src/js/components/product-select/ProductSelect.jsx
- src/js/components/stock-movement-wizard/modals/CombinedShipmentItemsModal.jsx
Color code formulary was added in:
- Create Shipment from PO - Add Items page
- Create OB Shipment - Add Items page
> OBPIH-5189 Color Code Formulary

- grails-app/i18n/messages.properties
- src/js/components/returns/inbound/InboundReturnsWizard.jsx
- src/js/components/returns/inbound/SendInboundReturn.jsx
- src/js/components/returns/outbound/OutboundReturnsWizard.jsx
- src/js/components/returns/outbound/SendOutboundReturn.jsx
- src/js/components/stock-movement-wizard/combined-shipments/SendMovementPage.jsx
- src/js/components/stock-movement-wizard/inbound/SendMovementPage.jsx
- src/js/components/stock-movement-wizard/outbound/SendMovementPage.jsx
- replace error label on Outbound workflow
- replace error label on Inbound workflow
- replace error label on Outbound Return workflow
- replace error label on Inbound Return workflow
- replace error label on Combined Shipment workflow
> OBPIH-5115 Change error label for delivery date before shipment date

- grails-app/controllers/org/pih/warehouse/api/InternalLocationApiController.groovy
- grails-app/services/org/pih/warehouse/core/LocationService.groovy
- src/js/components/locations-configuration/BinTable.jsx
- src/js/components/put-away/PutAwaySecondPage.jsx
- src/js/components/receiving/ReceivingPage.jsx
- src/js/components/returns/outbound/AddItemsPage.jsx
- src/js/components/stock-transfer/StockTransferSecondPage.jsx
- add ability to include/exclude locations by providing a list of ActivityCodes
- return hold bins on Add items page on outbound returns workflow
- return hold bins on create Putaway workflow
- return hold bins on stock transfer workflow
- return hold bins on stock receiving workflow
> OBPIH-5466 Cannot move stock to hold bin

- src/js/components/receiving/PartialReceivingPage.jsx
Similar issue to the one here: https://github.com/openboxes/openboxes/blob/678dba1019dd668f9f6ec0db8684af51216f0b06/src/js/utils/form-values-utils.jsx#L34-L52
#3906
> OBPIH-5575 Unable to export on Receive page

- grails-app/controllers/org/pih/warehouse/reporting/ConsumptionController.groovy
…instead of calculating current inventory from transactions
> OBPIH-5486 Improved performance of consumption report by using product availability

- grails-app/i18n/messages.properties
- grails-app/views/order/_orderItemForm.gsp
- grails-app/views/order/_orderItemFormDialog.gsp
- grails-app/views/purchaseOrder/_showOrderItems.gsp
- grails-app/views/taglib/_decimalFormatField.gsp
validate quantity per UoM value to be not less than 1
> OBPIH-5710 Add validation for quantity per UoM input field

- grails-app/services/org/pih/warehouse/core/DashboardService.groovy
I feel confident about this one after a comprehensive discussion with Kelsey, you will find the details in the ticket comments.
> OBPIH-5699 Reorder report not showing the correct list of items

- grails-app/views/inventoryItem/_actionsCurrentStock.gsp
As previous PR where I was supposed to revert that change has been merged accidentally, I've created this PR to remove this, since there was not point in reverting the another one.
> OBPIH-5723 Revert hiding the transfer stock button when < superuser

- src/js/components/stock-movement-wizard/request/CreateStockMovement.jsx
- pass stocklist.id on request edit instead of stocklist
> OBGM-409 error message when edit stocklist field on request create page

- grails-app/domain/org/pih/warehouse/core/Organization.groovy
- grails-app/taglib/org/pih/warehouse/DecimalNumberFieldTagLib.groovy
Details of the research in the ticket.
> OBGM-396 Fix creating a PO with autogenerated order number

- grails-app/services/org/pih/warehouse/importer/ProductCatalogItemExcelImporter.groovy
This one was chained off OBGM-393 to take advantage of the hibernate.allow_update_outside_transaction, but I don't actually think it's required. However, to be on the safe side, we should merge OBGM-393 first, then change the target of this PR to feature/upgrade-to-grails-3.3.10
> OBGM-463 Unable to import product catalog items

- grails-app/domain/org/pih/warehouse/requisition/RequisitionItem.groovy
- grails-app/services/org/pih/warehouse/inventory/StockMovementService.groovy
- bring back checking if there is need to undo previous changes
- fix requisition refresh
- minor NPE fix
> OBGM-471 Fix revising items on outbound stock movements

- grails-app/controllers/org/pih/warehouse/inventory/InventoryItemController.groovy
- grails-app/domain/org/pih/warehouse/inventory/InventoryItem.groovy
- grails-app/domain/org/pih/warehouse/inventory/Transaction.groovy
- grails-app/services/org/pih/warehouse/inventory/InventoryService.groovy
- grails-app/services/org/pih/warehouse/inventory/StockMovementService.groovy
To fix issue with not having data from not yet finished session while refreshing product availability for all locations after recall or revert recall
> OBGM-386 Move recall logic to service layer

- grails-app/services/org/pih/warehouse/inventory/StockMovementService.groovy
Explanation: https://pihemr.atlassian.net/browse/OBGM-534?atlOrigin=eyJpIjoiMjQ5OTgzODA1MGQ3NDEyODk4NDQ2ODk5ODIxYzRjNzIiLCJwIjoiaiJ9
> OBGM-534 Substitutes are duplicated on pack and send page 

- grails-app/services/org/pih/warehouse/core/FileService.groovy
> OBGM-394 Fix getting data mappings for shipment templates

- grails-app/controllers/org/pih/warehouse/user/UserController.groovy
- grails-app/services/org/pih/warehouse/core/UserService.groovy
According to discussions we had both here: #4093 and in the ticket for now I went the easiest path, so just to make the persistence in the service layer. 
I think doing data binding in the controller is not that bad, since in spring we also use @RequestBody to do it for us, but eventually in the MVP1/2 we could follow path of creating DTOs for those, so to make
```groovy
User createUser(BasicUserDTO user) {
...
}
...
class BasicUserDto {
String firstName
String lastName
String email
}
```
```groovy
User createUser(UserWithDetailsDto user) {
...
}
...
class UserWithDetailsDto extends BasicUserDto {
Date dateOfBirth
Locale locale
...
}
```
but user is specific case. But I believe this would be still a better approach instead of extracting a lot of params and passing it to the service etc. …
> OBGM-413 Unable to create a new user

- grails-app/controllers/org/pih/warehouse/product/ProductTypeController.groovy
- grails-app/services/org/pih/warehouse/product/ProductTypeService.groovy
I remember you @jmiranda were confused of why the productTypeCode is hard-coded.
Actually, you can't edit it, so I think it's expected:
> OBGM-468 Unable to create a new product type

- grails-app/controllers/org/pih/warehouse/api/StockMovementApiController.groovy
- grails-app/services/org/pih/warehouse/inventory/StockMovementService.groovy
- grails-app/services/org/pih/warehouse/requisition/RequisitionService.groovy
Explanation: https://pihemr.atlassian.net/browse/OBGM-408?atlOrigin=eyJpIjoiYTUxMjQxZGZjYzcxNDQ5NGFiOTZlZDcxNzhmNDdmMWEiLCJwIjoiaiJ9
> OBGM-408 Unable to cancel requests

- grails-app/controllers/org/pih/warehouse/product/ProductTypeController.groovy
- grails-app/services/org/pih/warehouse/product/ProductTypeService.groovy
Katarzyna has asked me to fix also update and delete methods in this ticket, so those are the changes to include them.
> OBGM-468 Fix no transaction for product type update and delete methods

- grails-app/controllers/org/pih/warehouse/product/ProductController.groovy
- grails-app/domain/org/pih/warehouse/product/ProductPackage.groovy
- grails-app/i18n/messages.properties
- grails-app/views/product/edit.gsp
Currently, on the ProductPackage table, we have a database constraint that requires to have a unique set of ProductPackages based on _product, productSupplier, uom, quantity_.
This constraint is only set using the luquibase change log
https://github.com/openboxes/openboxes/blob/f63862292ba27bae0316e076f7bf3b40844619ef/grails-app/migrations/install/changelog-create-schema.groovy#L3441-L3443  
The issue that ticket mentions is that when a user triggers this validation constraint it doesn't display the validation error in a user-friendly way but just redirects to the common error page with a whole stack trace, meaning that we are not properly handling this error 
So after looking through [grails documentation](https://docs.grails.org/latest/ref/Constraints/unique.html), I found out that we …
> OBGM-601 Add a product package unique constraint on ProductPackage domain

- grails-app/domain/org/pih/warehouse/core/BudgetCode.groovy
- grails-app/domain/org/pih/warehouse/core/GlAccount.groovy
- grails-app/domain/org/pih/warehouse/core/GlAccountType.groovy
- grails-app/domain/org/pih/warehouse/core/Location.groovy
- grails-app/domain/org/pih/warehouse/core/PreferenceType.groovy
- grails-app/domain/org/pih/warehouse/core/ProductPrice.groovy
- grails-app/domain/org/pih/warehouse/core/Synonym.groovy
- grails-app/domain/org/pih/warehouse/core/Tag.groovy
- grails-app/domain/org/pih/warehouse/core/UnitOfMeasure.groovy
- grails-app/domain/org/pih/warehouse/core/UnitOfMeasureClass.groovy
- grails-app/domain/org/pih/warehouse/inventory/Transaction.groovy
- grails-app/domain/org/pih/warehouse/invoice/Invoice.groovy
- grails-app/domain/org/pih/warehouse/invoice/InvoiceItem.groovy
- grails-app/domain/org/pih/warehouse/invoice/InvoiceType.groovy
- grails-app/domain/org/pih/warehouse/order/Order.groovy
- grails-app/domain/org/pih/warehouse/order/OrderAdjustment.groovy
- grails-app/domain/org/pih/warehouse/order/OrderItem.groovy
- grails-app/domain/org/pih/warehouse/order/OrderType.groovy
- grails-app/domain/org/pih/warehouse/picklist/Picklist.groovy
- grails-app/domain/org/pih/warehouse/product/Product.groovy
- grails-app/domain/org/pih/warehouse/product/ProductMergeLogger.groovy
- grails-app/domain/org/pih/warehouse/product/ProductPackage.groovy
- grails-app/domain/org/pih/warehouse/receiving/Receipt.groovy
- grails-app/domain/org/pih/warehouse/requisition/Requisition.groovy
- grails-app/domain/org/pih/warehouse/requisition/RequisitionItem.groovy
Closures worked fine, but I also changed them to methods to make the code more consistent (I had to check all of the places during looking for createdBy / updatedBy, so there was no additional work because of that)
> OBGM-603 Replace GORM event handler closures with methods

- grails-app/domain/org/pih/warehouse/order/Order.groovy
location organzation should not be required on wards, dispensary and pharmacy type locations
> OBGM-659 Change origin and destination validators on Order

- grails-app/controllers/org/pih/warehouse/product/ProductGroupController.groovy
For now, since I am not sure which way the solution that I have implemented in #4240 will go I am pushing this PR as a simple fix to the problem mentioned in the ticket
> OBGM-657 Handle Validation errors on product group create and edit

- grails-app/controllers/org/pih/warehouse/core/LocationController.groovy
- grails-app/services/org/pih/warehouse/core/LocationDataService.groovy
- refactor LocationController from transaction to regular and use services to handle transaction actions
- create LocationDataService for location CRUD operations
> OBGM-691 Unable to catch exception inside of the controller when importing non existing location zone

- grails-app/controllers/org/pih/warehouse/api/LocationApiController.groovy
The main issue of this ticket was the binding the **logo** property to the Location.
For some reason, grails binding had some trouble binding the image which was sent in the payload into `byte[]` type, so instead of binding the location instance using the command approach, I decided to bind it manually.
I had to exclude the **logo** property from `bindData()` since I am doing the manual decoding and wanted to avoid validation errors to be thrown.
Additioanlly I had to exclude the `zoneId` property from binding because it is a readonly property which cannot be binded.
> OBGM-693 Fix data binding of location property logo and fix error messages thrown on validation

- grails-app/i18n/messages.properties
- grails-app/services/org/pih/warehouse/inventory/RequisitionStatusTransitionEventService.groovy
- grails-app/services/org/pih/warehouse/report/NotificationService.groovy
- grails-app/views/email/_fulfillmentAlert.gsp
- grails-app/views/email/_fulfilmentAlert.gsp
Some changes will probably be needed after @drodzewicz PR (this one with newStatus discussed during TH - will be done after merging the mentioned PR, etc.), but I am pushing it for review.
> OBPIH-5823 Fulfilment alert to requestor - Approvals email alerts

- grails-app/domain/org/pih/warehouse/inventory/OutboundStockMovement.groovy
- grails-app/services/org/pih/warehouse/inventory/StockMovementService.groovy
- grails-app/views/stockMovement/show.gsp
- src/groovy/org/pih/warehouse/api/StockMovement.groovy
- src/js/components/stock-movement/outbound/StockMovementOutboundTable.jsx
For now, I am setting OBPIH-5804 as a base branch, after merging it, the base should be changed to develop.
> OBPIH-5809 Approval rollback - Approvals end to end workflow (fix after QA)

- grails-app/services/org/pih/warehouse/inventory/StockMovementService.groovy
- grails-app/services/org/pih/warehouse/requisition/RequisitionService.groovy
The issue was that in Grails 3 we just have a different package name for this taglib.
> OBGM-713 Fix rollback approvals

- grails-app/controllers/org/pih/warehouse/core/LocationController.groovy
I deleted the `location/show` view (it was empty) and changed redirects from `show` to `edit`, to avoid one unnecessary redirect (the `show` action also redirects to `edit`)
> OBGM-359 /location/show/id won't load due to GORM error

- grails-app/controllers/org/pih/warehouse/invoice/InvoiceController.groovy
use invoiceService.deleteInvoice method which alongside deleteing an Invoice removes InvoiceItems which previosuly caused IntegrityVioliationExzception on invoice delete
> OBGM-717 Fix issue causing Invoice to not be deleted

- build.gradle
Minor housekeeping - closing out a stale ticket
> OBGM-403 Bump a few Gradle dependencies to latest versions

- build.gradle
- grails-app/controllers/org/pih/warehouse/api/DashboardApiController.groovy
- grails-app/controllers/org/pih/warehouse/user/DashboardController.groovy
- grails-app/services/org/pih/warehouse/dashboard/IndicatorDataService.groovy
- grails-app/services/org/pih/warehouse/dashboard/NumberDataService.groovy
The description is pasted in the comments under the ticket: https://pihemr.atlassian.net/browse/OBGM-71?atlOrigin=eyJpIjoiMjU1ODIzYTk4M2NiNDgzMDg3NjNiYjE2NDQ3ZDM1MzEiLCJwIjoiaiJ9
> OBGM-71 Replace springcache plugin

- grails-app/controllers/org/pih/warehouse/core/DocumentController.groovy
This change doesn't really add any additional or different functionality to the current one but after digging through commits I noticed that during [initial rebase](https://github.com/openboxes/openboxes/commit/0858c694ab1a3a838d9f06d1a156fea3c083405f#) for this feature branch this was probably omitted, so I am bringing this change back
> OBGM-194 Bring back changes deleted in the process of rebase for templateService

- grails-app/conf/application.yml
- grails-app/conf/runtime.groovy
- grails-app/controllers/org/pih/warehouse/user/AuthController.groovy
I removed the things that were agreed to delete and I also removed the reference to the raven plugin in the auth controller
> OBGM-310 Review configuration that was not migrated from Config.groovy

- grails-app/conf/application.yml
Add missing sentry config mentioned in the ticket
> OBGM-310 Review configuration that was not migrated from Config.groovy (add missing sentry config)

- grails-app/services/org/pih/warehouse/data/ProductSupplierDataService.groovy
description: https://pihemr.atlassian.net/browse/OBGM-736?focusedCommentId=147954
> OBGM-736 Very slow import of many items on Add items to PO

- grails-app/domain/org/pih/warehouse/order/OrderItem.groovy
For explanation please refer to the comment under [Jira ticket](https://pihemr.atlassian.net/browse/OBPIH-5989?focusedCommentId=148052)
> OBPIH-5989 Able to update unit price and budget code when at least pending invoice exists

- grails-app/controllers/org/pih/warehouse/product/ProductController.groovy
- grails-app/services/org/pih/warehouse/product/ProductDataService.groovy
- grails-app/views/product/_productGroups.gsp
- added @Transactional to addProductGroupToProduct which fixes the persistence of the change to the database
- added nulsafe operator on productGroups which fixes 500 error thrown upon adding product to product group
these are small fixes that I came across when testing ajax tags
> OBGM-149 Fix issues that came out during investigation of ajax tags

- grails-app/controllers/org/pih/warehouse/api/StockMovementApiController.groovy
I forgot to add the validation in the stock movement API controller (I added it only in the stock movement controller)
> OBPIH-5990 Able to delete POSM when at least pending invoice exists

- grails-app/services/org/pih/warehouse/core/UserService.groovy
Description: https://pihemr.atlassian.net/browse/OBGM-745?focusedCommentId=148114
> OBGM-745 Default dashboard configuration broken for new users 

- grails-app/services/org/pih/warehouse/core/DocumentTemplateService.groovy
Katarzyna asked me to add a sorting for order items also. Previously I added it only to order adjustments.
> OBPIH-5977 Display items in PO Template in the same order as entered during PO creation

- grails-app/controllers/org/pih/warehouse/core/LocationController.groovy
- grails-app/views/location/edit.gsp
Katarzyna asked me to check the issue with saving an address within this ticket
> OBGM-752 Supported activities of location type are not assigned by default when create location on grails pages 

- grails-app/controllers/org/pih/warehouse/product/ProductSupplierController.groovy
- grails-app/i18n/messages.properties
- src/css/colors.scss
- src/js/components/Router.jsx
- src/js/components/listPagesUtils/ListTitle.jsx
- src/js/components/productSupplier/ProductSupplierHeader.jsx
- src/js/components/productSupplier/ProductSupplierList.jsx
- src/js/components/productSupplier/ProductSupplierTabs.jsx
- src/js/components/productSupplier/styles.scss
- src/js/consts/applicationUrls.js
- src/js/consts/productSupplierList.js
- src/js/hooks/list-pages/productSupplier/useProductSupplierTabs.jsx
- src/js/hooks/useQueryParams.jsx
- src/js/wrappers/ListHeaderButtonsWrapper.jsx
- src/js/wrappers/ListHeaderWrapper.jsx
- src/js/wrappers/ListWrapper.jsx
> OBPIH-6013 Add header and tabs to a redesigned product supplier list

- grails-app/domain/org/pih/warehouse/product/ProductSupplier.groovy
- grails-app/i18n/messages.properties
- src/js/api/urls.js
- src/js/components/productSupplier/PreferenceTypeColumn.jsx
- src/js/components/productSupplier/ProductSupplierList.jsx
- src/js/components/productSupplier/ProductSupplierListTable.jsx
- src/js/components/productSupplier/ProductSupplierTabs.jsx
- src/js/hooks/list-pages/productSupplier/useProductSupplierListTableData.jsx
- src/js/wrappers/ListTableTitleWrapper.jsx
- src/js/wrappers/ListTableWrapper.jsx
- src/main/groovy/org/pih/warehouse/product/ProductSupplierListDto.groovy
> OBPIH-6018 Add product sources list table

- grails-app/controllers/org/pih/warehouse/api/SelectOptionsApiController.groovy
- grails-app/i18n/messages.properties
- grails-app/services/org/pih/warehouse/data/ProductSupplierService.groovy
- src/js/actions/index.js
- src/js/actions/types.js
- src/js/api/services/OrganizationApi.js
- src/js/api/services/ProductApi.js
- src/js/api/services/ProductSupplierApi.js
- src/js/api/urls.js
- src/js/components/productSupplier/FilterFields.jsx
- src/js/components/productSupplier/ProductSupplierList.jsx
- src/js/components/productSupplier/ProductSupplierListFilters.jsx
- src/js/components/productSupplier/ProductSupplierListTable.jsx
- src/js/hooks/list-pages/productSupplier/useProductSupplierFilters.jsx
- src/js/hooks/list-pages/productSupplier/useProductSupplierListTableData.jsx
- src/js/hooks/list-pages/useCommonFilters.jsx
- src/js/reducers/index.jsx
- src/js/reducers/productSupplierReducer.jsx
- src/js/utils/list-utils.jsx
- src/js/utils/option-utils.jsx
- src/js/wrappers/ListFilterFormWrapper.jsx
Added TODOs to eventually replace the organization and product fetch by a call to the proper APIs instead of the generic one when you are back and we agree on an approach.
For now I used the generic api even though I hate it and I believe you also do, but in order for the list to work, it seems to be enough for a while.
> OBPIH-6014 Product Sources list filters

- src/js/components/stock-movement-wizard/request/EditPage.jsx
I forgot to add colors on request/EditPage
> OBPIH-4930 Show catalog colors on outbound shipment pages (fix after QA)

- src/css/colors.scss
- src/js/components/listPagesUtils/Tabs.jsx
- src/js/components/productSupplier/ProductSupplierTabs.jsx
- src/js/components/productSupplier/styles.scss
- src/js/wrappers/ListFilterFormWrapper.jsx
- src/js/wrappers/ListHeaderButtonsWrapper.jsx
- src/js/wrappers/ListHeaderWrapper.jsx
- src/js/wrappers/ListTableTitleWrapper.jsx
- src/js/wrappers/ListTableWrapper.jsx
- src/js/wrappers/ListWrapper.jsx
Implemented suggested changes from: https://github.com/openboxes/openboxes/pull/4433
> OBPIH-6013-fix Add header and tabs to a redesigned product supplier list (fixes after post-code review)

- grails-app/conf/runtime.groovy
- grails-app/controllers/org/pih/warehouse/user/UserController.groovy
- grails-app/services/org/pih/warehouse/core/UserService.groovy
- grails-app/views/user/edit.gsp
description: https://pihemr.atlassian.net/browse/OBPIH-5135?focusedCommentId=148998
> OBPIH-5135 Browsers cannot change their password

- src/js/components/stock-movement-wizard/outbound/AddItemsPage.jsx
\+ I was able to remove the part of the code that calculates duplicated items between requests because when the queue is implemented it is not needed. We shouldn't be able to work on the same two items at the same time.
> OBPIH-6026 Changing quantities to 0 on very long stocklists breaks autosave (fix for infinite loading)

- grails-app/controllers/org/pih/warehouse/api/PutawayApiController.groovy
Follow the discussion [in the ticket](https://pihemr.atlassian.net/browse/OBPIH-5967?focusedCommentId=149178)
> OBPIH-5967 Can edit completed putaway when go back to edit page after complete

- src/js/api/services/StockTransferApi.js
- src/js/api/urls.js
- src/js/components/returns/inbound/AddItemsPage.jsx
- src/js/consts/stockTransferStatus.js
Some changes that are worth pointing out
**Removed updateFormValues**
After inspecting it closes I noticed that this function does not serve any purpose than to make the page probably slower and confuse the developer.
```
updateFormValues(values) {
this.setState({ formValues: values });
}
```
Before, `updateFormValues(values)` would have been called on each table field **onBlurr** callback to update the state of **formValues**. We do not need to manually update the formValues, the ReactForm does it for us and keeps track of the state. When we perform any kind of a save on this addItemsPage, the state that we are providing as a payload for update request is **values** prop which is provided by renderProps of the `react-final-form` component, we never used **formVlaues** anywhere on the …
> OBPIH-5932 Add validation for expiration date in inbound returns

- src/js/components/returns/inbound/AddItemsPage.jsx
While refactoring this part in the previous PR I missed that this checked if status is other than PLACED, so I forgot the negation here.
> OBPIH-5932 Submit inbound return with status PLACED when going to the next page with status other than PLACED

- src/js/components/productSupplier/ProductSupplierHeader.jsx
- src/js/components/productSupplier/modals/PreferenceTypeModal.jsx
- src/js/components/productSupplier/styles.scss
- src/js/hooks/list-pages/productSupplier/useProductSupplierActions.jsx
- src/js/utils/ConfirmModal.jsx
- src/js/utils/confirmationModalUtils.jsx
- src/js/utils/permissionUtils.js
I included fixes after @awalkowiak's review in the product source feature branch in this PR
> OBPIH-6020 Preference Type Modal

- grails-app/controllers/org/pih/warehouse/shipping/ShipmentController.groovy
- grails-app/domain/org/pih/warehouse/core/Event.groovy
- grails-app/init/org/pih/warehouse/BootStrap.groovy
- grails-app/services/org/pih/warehouse/shipping/ShipmentService.groovy
- src/js/components/dashboard/StockRequestDashboard.jsx
- src/js/utils/list-utils.jsx
- src/main/groovy/org/pih/warehouse/api/StockMovement.groovy
follow the discussion in [the ticket](https://pihemr.atlassian.net/browse/OBPIH-5826)
> OBPIH-5826 comment indication approvals comment

- src/css/colors.scss
- src/js/components/Layout/v2/Section.jsx
- src/js/components/Layout/v2/Subsection.jsx
- src/js/components/Layout/v2/styles.scss
> OBPIH-6023 Add reusable Section and Subsection components

- grails-app/domain/org/pih/warehouse/product/ProductSupplier.groovy
- src/js/components/form-elements/v2/TextInput.jsx
- src/js/components/form-elements/v2/style.scss
- src/js/components/productSupplier/create/subsections/AdditionalDetails.jsx
- src/js/components/productSupplier/create/subsections/BasicDetails.jsx
- src/js/components/productSupplier/create/subsections/DefaultPreferenceType.jsx
- src/js/components/productSupplier/create/subsections/FixedPrice.jsx
- src/js/components/productSupplier/create/subsections/PackageSpecification.jsx
- src/js/hooks/productSupplier/form/useProductSupplierForm.js
- src/js/hooks/productSupplier/form/useProductSupplierValidation.js
- src/js/utils/form-utils.jsx
One thing you may notice are changes to some other sections. This is because I have added the bootstrap grid system as a wrapper for our fields.
One of the reopen change requests I got was that my fields we not in the same layout as on the mock so I decided to use bootstrap grid system to solve this issue.
To not have different approaches in other sections I did the following modifications and also added `row` and `col-lg` classes
> OBPIH-6111 add pricing section with inputs

- src/js/components/productSupplier/create/ProductSupplierFormMain.jsx
- src/js/hooks/productSupplier/form/useProductSupplierForm.js
- src/js/hooks/productSupplier/form/useProductSupplierValidation.js
I missed the id on defaultPreferenceType
> OBPIH-6108 Add missing id on default preference type

- grails-app/controllers/org/pih/warehouse/api/ApiController.groovy
- grails-app/domain/org/pih/warehouse/core/User.groovy
- src/js/components/productSupplier/ProductSupplierHeader.jsx
- src/js/components/productSupplier/ProductSupplierListTable.jsx
- src/js/components/productSupplier/modals/PreferenceTypeModal.jsx
- src/js/hooks/list-pages/productSupplier/useProductSupplierActions.jsx
- src/js/hooks/useUserHasPermissions.js
- src/js/reducers/sessionReducer.jsx
- src/js/utils/permissionUtils.js
An additional case that I had to include in this ticket was conditionally rendered link to product sources edit if the user has sufficient roles (user is at least an admin and has product manager roles).
I have decided to create a custom hook `useUserHasPermission` to encapsulate the logic of retrieving user role data from redux and performing appropriate checks.
I also had to return location roles in the AppContext since I noticed that in a previous version of `hasPermission` util function we don't check for location roles on front end, only global roles.
> OBPIH-6232 show hyperlink to source edit and stockcard on sources list page when user has sufficient roles

- grails-app/controllers/org/pih/warehouse/api/OrganizationApiController.groovy
- grails-app/services/org/pih/warehouse/core/OrganizationService.groovy
- grails-app/services/org/pih/warehouse/importer/ProductSupplierPreferenceImportDataService.groovy
I have also made sure everything works on load demo data and there are no imports that collide with this new validation
> OBPIH-6248 add validation on non buyer organization in preference type import

- grails-app/views/layouts/custom.gsp
- grails-app/views/layouts/stockCard.gsp
- grails-app/views/order/show.gsp
Reverts openboxes/openboxes#4550
> Revert "OBPIH-6092 Experimental fix to the issue with jquery tabs loading"

- grails-app/i18n/messages.properties
- src/js/components/stock-movement-wizard/outbound/PickPage.jsx
This one has to be merged after merging OBPIH-6153
> OBPIH-6363 Validation and items requiring attention after clearing pick

- grails-app/controllers/org/pih/warehouse/picklist/PicklistController.groovy
> OBPIH-6341 Export only pickPage items for pick template

- grails-app/controllers/org/pih/warehouse/api/StockMovementApiController.groovy
- grails-app/controllers/org/pih/warehouse/core/StockMovementParamsCommand.groovy
- grails-app/controllers/org/pih/warehouse/picklist/ImportPickCommand.groovy
- grails-app/controllers/org/pih/warehouse/picklist/PicklistController.groovy
- grails-app/services/org/pih/warehouse/inventory/StockMovementService.groovy
changes requested #4625 and additional bug fix for refresh picklist items on read stockMovement
> OBPIH-6155 fixes after review

- grails-app/services/org/pih/warehouse/dashboard/IndicatorDataService.groovy
The query is not as much longer than the previous version as it seems at first glance :smile: I changed the formatting and made the previous version a subquery of the "main" filtering query, so the new query operates only on a few records and doesn't make the performance worst.
> OBPIH-6328 Dashboard indicator for items with backdated shipments (fixes after QA)

- grails-app/views/order/_itemStatus.gsp
- src/js/components/put-away/PutAwayCheckPage.jsx
- src/js/components/put-away/PutAwayPage.jsx
- src/js/components/put-away/PutAwaySecondPage.jsx
- src/js/components/put-away/SplitLineModal.jsx
Was trying to align with already existing solutions from https://github.com/openboxes/openboxes/pull/4707
> OBPIH-6413 localize dates on putaway workflow

- grails-app/conf/runtime.groovy
- grails-app/services/org/pih/warehouse/api/MegamenuService.groovy
Add ability to enable and disable individual navItems in the config
> OBPIH-6533 Hide Import complete outbound from menu

- grails-app/domain/org/pih/warehouse/order/Order.groovy
- grails-app/i18n/messages.properties
- grails-app/views/order/_summary.gsp
- src/test/groovy/unit/org/pih/warehouse/order/OrderSpec.groovy
**Link to GitHub issue or Jira ticket:** [OBPIH-6498](https://pihemr.atlassian.net/browse/OBPIH-6498)
Add a confirmation popup when users is trying to generate a partial invoice.
---
video: https://jam.dev/c/5b9137ba-ff96-4506-b86c-5fe6281ef3ac
[OBPIH-6498]: https://pihemr.atlassian.net/browse/OBPIH-6498?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OBPIH-6498 Show confirmation dialog when trying to generate a partial invoice

- src/js/components/DataTable/DataTable.jsx
- src/js/components/DataTable/TableRow.jsx
- src/js/components/Filter/FilterForm.jsx
- src/js/components/form-elements/DateFilter/DateFilter.jsx
- src/js/components/form-elements/FilterSelectField.jsx
- src/js/components/receiving/PartialReceivingPage.jsx
- src/js/components/receiving/ReceivingCheckScreen.jsx
- src/js/components/stock-movement/inbound/FilterFields.jsx
- src/js/utils/form-utils.jsx
**Link to GitHub issue or Jira ticket:** [OBPIH-6448](https://pihemr.atlassian.net/browse/OBPIH-6448)
Added **testId** and **ariaLabel** attributes to components used in the **inbound list page**
---
Changes required for the following implementation of E2E tests on inbound list page https://github.com/openboxes/openboxes-e2e/pull/9
---
> *Please confirm and check each of the following to ensure that your change conforms to the coding standards of the project:*
[OBPIH-6448]: https://pihemr.atlassian.net/browse/OBPIH-6448?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OBPIH-6448 Added accessibility attributes on inbound list components

- src/js/components/stock-movement-wizard/modals/EditPickModal.jsx
**Link to GitHub issue or Jira ticket:** https://pihemr.atlassian.net/browse/OBPIH-6613
**Description:** There is currently an error on obdev3 (can replicate locally) where we're unable to manually pick items during outbound stock movements since it shows a blank screen when the button is pressed. The EditPickModal is failing to create due to errors localizing reasonCode. This change is to fix that.
---
> *If this PR contains a UI change, consider adding one or more screenshots here or link to a screen recording to help reviewers …
> [OBPIH-6613] Fix localization on reasonCode label during pick

- grails-app/migrations/views/order-summary-helper-views.sql
https://pihemr.atlassian.net/browse/OBPIH-6610
See tickets description (File to review: [order-summary-helper-views.sql](https://github.com/openboxes/openboxes/pull/4785/files/0b0289b86b2e09265ff66ff69ea89591f2fee838#diff-194e443c60f6a67d45206aefff9827292ace6e4460a983c24d35b2ac92dfbf2b), rest is the calculate inverse items that's in separate PR)
---
Order summary (derived status) calculation for payment statuses (invoices) needs to be checked.
---
> *Please confirm and check each of the following to ensure that your …
> OBPIH-6610 Exclude inverse items from order summary view

- src/js/hooks/outboundImport/useOutboundImportForm.js
- src/js/hooks/useSpinner.js
**Link to GitHub issue or Jira ticket:** [OBPIH-6626](https://pihemr.atlassian.net/browse/OBPIH-6626)
TLDR; of the issue: After submitting the full outbound request user is waiting for the redirect to happen and is able to click "Finish" button since after first submit it is not disabled and as a result for each click submits a "NEW"  full outbound stock movement.
My solution was to display the spinner overlay which should prevent the user from interacting with the UI while the request is being processed.
---
> *If this …
> [OBPIH-6626] [Bug-Fix] Prevent multiple full outbound imports from happening

- grails-app/services/org/pih/warehouse/report/ReportService.groovy
**Link to GitHub issue or Jira ticket:** https://pihemr.atlassian.net/browse/OBPIH-6611
**Description:** Ensure that we don't include inverse prepayment invoice items in the amount outstanding report. See ticket for details.
---
---
> *We require that all code changes come paired with a method of testing them. Please select which of the following …
> [OBPIH-6611] filter inverse prepayment line items from amount outstanding report

- grails-app/services/org/pih/warehouse/fulfillment/FulfillmentService.groovy
**Link to GitHub issue or Jira ticket:** [OBPIH-6625](https://pihemr.atlassian.net/browse/OBPIH-6625)
In a regular outbound workflow when sending a shipment we have this exact code that triggers an event which handles sending appropriate notification to the user based on the provided `shipmentStatus`, the only problem was that the new implementation on the full outbound workflow was missing this event publish.
---
> *If this PR contains a UI change, consider adding one or more screenshots here or link to a screen …
> [OBPIH-6624] Trigger ShipmentStatusTransitionEvent event when sending a shipment on full outbound import

- grails-app/controllers/org/pih/warehouse/UrlMappings.groovy
- grails-app/controllers/org/pih/warehouse/api/PrepaymentInvoiceItemApiController.groovy
- grails-app/services/org/pih/warehouse/invoice/PrepaymentInvoiceService.groovy
https://pihemr.atlassian.net/browse/OBPIH-6501
Endpoint to remove invoice item
---
Will be tested with frontend changes
---
> *Please confirm and check each of the following to ensure that your change conforms to the coding standards of the project:*
> OBPIH-6501 Add endpoint to remove invoice item

- grails-app/i18n/messages.properties
- src/js/api/services/PrepaymentInvoiceItemApi.js
- src/js/api/urls.js
- src/js/components/invoice/create/ConfirmInvoicePage.jsx
- src/js/components/invoice/create/InvoicePrepayedItemsTable.jsx
- src/js/hooks/invoice/useInvoicePrepaidItemsTable.jsx
- src/js/tests/utils/__snapshots__/ActionDots.test.jsx.snap
- src/js/utils/ActionDots.jsx
**Link to GitHub issue or Jira ticket:** https://pihemr.atlassian.net/browse/OBPIH-6531
The PR adds a dropdown options on invoice items (only on regular items) with edit and remove options (in this pr only remove is working). Clicking remove on a regular item also removes the corresponding inverse item. This PR needs https://github.com/openboxes/openboxes/pull/4788 to be working.
---
> OBPIH-6531 [frontend] Ability to remove invoice item

- grails-app/services/org/pih/warehouse/invoice/InvoiceService.groovy
The reopening was caused by duplicating some invoice items / missing some invoice items. Pagination on the frontend fetched items in parts:
0-10 items
10-20 items
20-30 items
....
Each data fetching was in a different order, so each request can duplicate items.
> OBPIH-6500 [frontend] Modifications to the invoice confirmation page (fix after QA)

- grails-app/controllers/org/pih/warehouse/UrlMappings.groovy
- grails-app/controllers/org/pih/warehouse/api/PrepaymentInvoiceApiController.groovy
- grails-app/controllers/org/pih/warehouse/api/PrepaymentInvoiceItemApiController.groovy
- grails-app/domain/org/pih/warehouse/order/Order.groovy
- grails-app/domain/org/pih/warehouse/shipping/ShipmentItem.groovy
- grails-app/i18n/messages.properties
- grails-app/services/org/pih/warehouse/invoice/PrepaymentInvoiceService.groovy
https://pihemr.atlassian.net/browse/OBPIH-6502
Add API endpoints to edit prepaid invoice items
---
Will be tested with frontend changes
---
> *Please confirm and check each of the following to ensure that your change conforms to the coding standards of the project:*
> OBPIH-6502 Add API endpoints to edit prepaid invoice items

- grails-app/domain/org/pih/warehouse/invoice/Invoice.groovy
- grails-app/domain/org/pih/warehouse/invoice/InvoiceItem.groovy
- src/js/api/services/PrepaymentInvoiceApi.js
- src/js/api/services/PrepaymentInvoiceItemApi.js
- src/js/api/urls.js
- src/js/components/form-elements/v2/TextInput.jsx
- src/js/components/invoice/Invoice.scss
- src/js/components/invoice/create/ConfirmInvoicePage.jsx
- src/js/components/invoice/create/InvoiceOptionsForm.jsx
- src/js/components/invoice/create/InvoicePrepayedItemsTable.jsx
- src/js/consts/invoiceStatus.js
- src/js/hooks/invoice/useInvoicePrepaidItemsTable.jsx
**Link to GitHub issue or Jira ticket:** https://pihemr.atlassian.net/browse/OBPIH-6532
**This PR is still in progress but ready for initial review. Before merging this one, merge the PR with the remove action.**
> OBPIH-6532 [frontend] Ability to edit invoice item

- src/js/components/stock-movement-wizard/outboundImport/OutboundImport.jsx
- src/js/hooks/outboundImport/useOutboundImportForm.js
**Link to GitHub issue or Jira ticket:** [OBPIH-6627](https://pihemr.atlassian.net/browse/OBPIH-6627)
Issues found after QA testing:
- remove the uploaded file when clicking "Redo Import" button
- set cached **shipped date** value when refreshing the page
---
---
> *We require that all code changes come paired with a method of …
> OBPIH-6627 Clear uploaded file when trying to redo import and set cached dateShipped value on refresh

- src/js/api/services/LocationApi.js
- src/js/components/stock-movement-wizard/outboundImport/subsections/OutboundImportBasicDetails.jsx
- src/js/consts/StockMovementDirection.js
- src/js/utils/option-utils.jsx
**Link to GitHub issue or Jira ticket:** [OBPIH-6515](https://pihemr.atlassian.net/browse/OBPIH-6515)
The issue was that locations returned on import outbound workflow were a different set of locations than on regular outbound, the difference was that on regular outbound creation we send a request to locations api with `direction=OUTBOUND` parameter that was extracted from the url (for example when we are on page `/openboxes/stockMovement/createOutbound?direction=OUTBOUND`).
To fix this issue I have added an additional …
> [OBPIH-6515] Unify location search on outbound import with regular outbound creation

- src/js/components/stock-movement-wizard/outboundImport/subsections/OutboundImportDropzone.jsx
- src/js/components/stock-movement-wizard/outboundImport/subsections/OutboundImportItems.jsx
**Link to GitHub issue or Jira ticket:** [OBPIH-6621](https://pihemr.atlassian.net/browse/OBPIH-6621)
Fixes after first QA test.
- added Icon to export template buttons
-  fixed display of product name in tooltip
---
---
> *We require that all code changes come paired with a method of testing them. Please select which of the …
> [OBPIH-6621] Add icon to export button and fix tooltips labels on product column

- src/main/groovy/org/pih/warehouse/outbound/ImportPackingListItem.groovy
**Link to GitHub issue or Jira ticket:** [OBPIH-6513](https://pihemr.atlassian.net/browse/OBPIH-6513)
Added an ability to handle a case where user does not provide a lot number.
If provided binLocation has only one inventoryItem then we infer it since this is the only possible choice a user can make.
---
---
> *We require that all …
> feature/OBPIH-6516 Infer lot number based on provided bin location

- grails-app/services/org/pih/warehouse/invoice/PrepaymentInvoiceService.groovy
https://pihemr.atlassian.net/browse/OBPIH-6644
This is an improvement to my previous PR (https://github.com/openboxes/openboxes/pull/4820). I forgot about invoice item editing on confirm page...
---
According to the test plan
---
> OBPIH-6644 Fix calculating inverse item after reducing ordered quantity (invoice item edit)

- src/test/groovy/unit/org/pih/warehouse/invoice/PrepaymentInvoiceServiceSpec.groovy
**Link to GitHub issue or Jira ticket:** https://pihemr.atlassian.net/browse/OBPIH-6666
**Description:**  Add unit tests on PrepaymentInvoiceService.generatePrepaymentInvoice. We'll ideally also write tests on the other methods in the service but this can be a starting point.
---
---
> *Please confirm and check each of the …
> [OBPIH-6666] unit tests on generating prepayment invoice

- grails-app/services/org/pih/warehouse/report/ReportService.groovy
https://pihemr.atlassian.net/browse/OBPIH-6671
There was an issue with calculating the report when there were multiple (partial) invoice items per shipment item (the quantity shipped was unnecessarily duplicated). Fixed it by grouping rows by shipment item and summing the quantity invoiced.
> OBPIH-6671 Fix amount outstanding on orders report calculation

- src/js/components/invoice/create/InvoicePrepayedItemsTable.jsx
**Link to GitHub issue or Jira ticket:** https://pihemr.atlassian.net/browse/OBPIH-6670
> OBPIH-6670 Remove PO number column on confirm page of prepayment POs invoice workflow

- grails-app/controllers/org/pih/warehouse/api/PrepaymentInvoiceItemApiController.groovy
- grails-app/domain/org/pih/warehouse/order/OrderAdjustment.groovy
- grails-app/i18n/messages.properties
- grails-app/services/org/pih/warehouse/invoice/PrepaymentInvoiceService.groovy
- src/test/groovy/unit/org/pih/warehouse/invoice/PrepaymentInvoiceServiceSpec.groovy
https://pihemr.atlassian.net/browse/OBPIH-6689
Expand edit invoice item API endpoint to allow editing unit price on invoice items made from adjustments
> OBPIH-6689 Add ability to modify unit price on invoice items made from order adjustments

- grails-app/i18n/messages.properties
- src/js/components/invoice/create/ConfirmInvoicePage.jsx
- src/js/components/invoice/create/InvoicePrepayedItemsTable.jsx
- src/js/hooks/invoice/useConfirmInvoicePage.jsx
- src/js/hooks/invoice/useInvoicePrepaidItemsTable.jsx
**Link to GitHub issue or Jira ticket:** https://pihemr.atlassian.net/browse/OBPIH-6690
I adjusted the hook to be able to edit the unit price of order adjustments.
---
> OBPIH-6690 Add option to edit unit price on invoice items made from order adjustments

- grails-app/domain/org/pih/warehouse/order/OrderAdjustment.groovy
- src/test/groovy/unit/org/pih/warehouse/order/OrderAdjustmentSpec.groovy
**Link to GitHub issue or Jira ticket:** [OBPIH-6688](https://pihemr.atlassian.net/browse/OBPIH-6688)
The is invoiced transient value should handle case where we are trying to check if adjusment is invoiceable when there is only partially invoiced amount.
---
[OBPIH-6688]: https://pihemr.atlassian.net/browse/OBPIH-6688?atlOrigin=eyJpI …
> OBPIH-6688 modify method checking if order adjustment is invoiceable

- src/js/components/stock-movement-wizard/combined-shipments/AddItemsPage.jsx
**Link to GitHub issue or Jira ticket:** [OBPIH-6668](https://pihemr.atlassian.net/browse/OBPIH-6668?atlOrigin=eyJpIjoiOTE3NjZjZDAxNTg2NGI1YWJjYTYxZTFiMmY5OGJhYmIiLCJwIjoiaiJ9)
The issue with disappearing new lines was caused by managing the state in the component and in the form state at the same time, so when we were fetching new lines, we overrode the already created new lines.
[OBPIH-6668]: https://pihemr.atlassian.net/browse/OBPIH-6668?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OBPIH-6668 Responsiveness in very long shipments with split line appears and disappears

- grails-app/migrations/views/invoice-list.sql
ignore inverse items
**Link to GitHub issue or Jira ticket:** [OBPIH-6724](https://pihemr.atlassian.net/browse/OBPIH-6724)
Ignore the inverse items when counting invoice items on invoice list page
---
[OBPIH-6724]: https://pihemr.atlassian.net/browse/OBPIH-6724?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0 …
> OBPIH-6724 Fix invoice item count on invoice list page

- grails-app/migrations/views/order-summary-helper-views.sql
**Link to GitHub issue or Jira ticket:** https://pihemr.atlassian.net/browse/OBPIH-6691
> OBPIH-6691 Add partially invoiced order summary status for order adjustments

- src/js/actions/index.js
- src/js/actions/types.js
- src/js/components/form-elements/Button.jsx
- src/js/components/stock-movement-wizard/outboundImport/sections/OutboundImportConfirm.jsx
- src/js/components/stock-movement-wizard/outboundImport/sections/OutboundImportDetails.jsx
- src/js/hooks/outboundImport/useScrollToBottom.js
- src/js/reducers/index.jsx
- src/js/reducers/outboundImportReducer.jsx
> OBPIH-6734 Scroll down to bottom position of the page when redo import

- grails-app/conf/templates/configuration/productSuppliers.csv
> OBPIH-6274 Fix non-existing unit of measure in the load demo data file

- grails-app/domain/org/pih/warehouse/order/OrderAdjustment.groovy
- src/test/groovy/unit/org/pih/warehouse/order/OrderAdjustmentSpec.groovy
**Link to GitHub issue or Jira ticket:** [OBPIH-6693](https://pihemr.atlassian.net/browse/OBPIH-6693)
---
[OBPIH-6693]: https://pihemr.atlassian.net/browse/OBPIH-6693?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OBPIH-6693 fix adjustment invoice statuses

- grails-app/migrations/views/drop-all-views.xml
- grails-app/migrations/views/order-summary-helper-views.sql
- grails-app/services/org/pih/warehouse/report/ReportService.groovy
**Link to GitHub issue or Jira ticket:** [OBPIH-6692](https://pihemr.atlassian.net/browse/OBPIH-6692)
The goal was to check for the total adjustment amount and invoiced amount and add it as an additional condition to include these adjustments in amount outstanding report.
---
[OBPIH-6692]: …
> OBPIH-6692 modify order adjustments query on amount outstanding on orders report

- grails-app/services/org/pih/warehouse/product/ProductMergeService.groovy
https://pihemr.atlassian.net/browse/OBPIH-6631
A bit of comments in the product merge service
> OBPIH-6631 Add a bit more comments in product merge service

- src/js/components/form-elements/TableRow.jsx
**Link to GitHub issue or Jira ticket:** [OBPIH-6682](https://pihemr.atlassian.net/browse/OBPIH-6682)
Added attributes on table component for an easier access to table cells for e2e tests
---
[OBPIH-6682]: https://pihemr.atlassian.net/browse/OBPIH-6682?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvb …
> OBPIH-6682 Add accessibility attributes on table row component

- grails-app/controllers/org/pih/warehouse/JsonController.groovy
> OBPIH-6227 Add product UoM in add items to PO

- grails-app/services/org/pih/warehouse/product/ProductService.groovy
- src/js/components/product-select/ProductSelect.jsx
- src/js/components/stock-movement-wizard/request/AddItemsPage.jsx
- src/js/utils/option-utils.jsx
- src/main/groovy/org/pih/warehouse/product/ProductSearchDto.groovy
> OBPIH-6228 Add product UoM in add items to request

- grails-app/services/org/pih/warehouse/report/ReportService.groovy
**Link to GitHub issue or Jira ticket:** [OBPIH-6692](https://pihemr.atlassian.net/browse/OBPIH-6692)
There were two points needed fixing
-  remove fully invoiced adjustments with negative values from the report
- report did not include adjustments where adjustment has been invoiced but amount was edited to smaller
---
[OBPIH-6692]: …
> OBPIH-6692 handle negative invoiced amount numbers and invoiced amount not equal to total adjustment amount

- grails-app/conf/runtime.groovy
- grails-app/views/product/_productSuppliers.gsp
- src/js/consts/applicationUrls.js
- src/js/hooks/productSupplier/form/useProductSupplierForm.js
**Link to GitHub issue or Jira ticket:** [OBPIH-6224](https://pihemr.atlassian.net/browse/OBPIH-6224)
Modified redirect navigation from product stock card to new product sources pages
Added permission restrictions on product sources create/edit and delete
---
[OBPIH-6224]: https://pihemr.atlassian.net/browse/OBPIH-6224?atlOrigin=eyJpI …
> OBPIH-6224 redirect to new product source list form from the stockcard

- src/js/components/receiving/PartialReceivingPage.jsx
After discussing this with Manon, we decided to clear the field values after using the edit modal instead of auto-filling them.
> OBPIH-6623 Quantity receiving now should be cleared after using modal to edit receipt

- grails-app/controllers/org/pih/warehouse/invoice/InvoiceController.groovy
- grails-app/domain/org/pih/warehouse/invoice/Invoice.groovy
- grails-app/i18n/messages.properties
- grails-app/services/org/pih/warehouse/invoice/InvoiceService.groovy
- grails-app/views/invoice/_summary.gsp
- grails-app/views/invoice/show.gsp
**Link to GitHub issue or Jira ticket:** [OBPIH-6781](https://pihemr.atlassian.net/browse/OBPIH-6781)
---
When trying to rollback prepayment invoice while regular invoice exists 
When trying to delete prepayment invoice while regular invoice exists 
[OBPIH-6781]: https://pihemr.atlassian.net/browse/OBPIH-6781?atlOrigin=eyJpIjoiNWRkNTl …
> OBPIH-6781 prevent refreshing and deleting prepayment invoices that already have final invoices associated

- grails-app/conf/runtime.groovy
- grails-app/controllers/org/pih/warehouse/RoleInterceptor.groovy
- grails-app/services/org/pih/warehouse/core/UserService.groovy
- grails-app/taglib/org/pih/warehouse/AuthTagLib.groovy
- grails-app/views/product/_productSuppliers.gsp
**Link to GitHub issue or Jira ticket:** [OBPIH-6224](https://pihemr.atlassian.net/browse/OBPIH-6224)
Make edit, create and delete to be available to users with admin and product manager permissions
---
[OBPIH-6224]: https://pihemr.atlassian.net/browse/OBPIH-6224?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2 …
> OBPIH-6224 Fix permission issue on product supplier controller actions

- src/js/components/stock-movement-wizard/combined-shipments/AddItemsPage.jsx
**Link to GitHub issue or Jira ticket:** [OBPIH-6225](https://pihemr.atlassian.net/browse/OBPIH-6225)
---
[OBPIH-6225]: https://pihemr.atlassian.net/browse/OBPIH-6225?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OBPIH-6225 Add bigger fixed width for table columns

- src/js/components/returns/inbound/AddItemsPage.jsx
- src/js/components/stock-movement-wizard/combined-shipments/AddItemsPage.jsx
- src/js/components/stock-movement-wizard/inbound/AddItemsPage.jsx
- src/js/components/stock-movement-wizard/outbound/AddItemsPage.jsx
- src/js/utils/form-utils.jsx
**Link to GitHub issue or Jira ticket:** [OBPIH-6099](https://pihemr.atlassian.net/browse/OBPIH-6099)
Added a select in place of the recipient header for the ability to assign the same recipient to all of the rows below
---
PO Shipment
Inbound
Outbound
Inbound Return 
[OBPIH-6099]: …
> OBPIH-6099 fill multiple lines in shipments with the same recipient

- grails-app/services/org/pih/warehouse/putaway/PutawayService.groovy
> OBPIH-6744 Performance improvements in putaway workflow (backend)

- grails-app/controllers/org/pih/warehouse/UrlMappings.groovy
- grails-app/controllers/org/pih/warehouse/api/SelectOptionsApiController.groovy
- grails-app/i18n/messages.properties
- grails-app/services/org/pih/warehouse/product/ProductService.groovy
- src/js/api/services/SelectOptionsApi.js
- src/js/api/urls.js
- src/js/components/products/FilterFields.jsx
- src/js/components/products/ProductsList.jsx
- src/js/hooks/list-pages/product/useProductFilters.jsx
- src/js/hooks/list-pages/product/useProductsListTableData.jsx
- src/js/utils/option-utils.jsx
> OBPIH-5739 Add filter for handling requirement in products list page

- grails-app/services/org/pih/warehouse/core/DocumentService.groovy
- grails-app/services/org/pih/warehouse/core/DocumentTemplateService.groovy
> OBPIH-6321 Show supplier product name in po documents

- grails-app/controllers/org/pih/warehouse/api/CombinedShipmentItemApiController.groovy
- grails-app/taglib/org/pih/warehouse/FormatTagLib.groovy
- grails-app/views/order/_itemDetails.gsp
- grails-app/views/order/_itemStatus.gsp
- grails-app/views/order/_orderAdjustments.gsp
- grails-app/views/order/_orderInvoices.gsp
- grails-app/views/order/_orderShipments.gsp
- grails-app/views/order/_orderSummary.gsp
- grails-app/views/stockMovement/_packingList.gsp
- grails-app/views/stockMovement/_receipts.gsp
- grails-app/views/taglib/_productDisplayName.gsp
- src/js/components/stock-movement-wizard/combined-shipments/AddItemsPage.jsx
- src/js/components/stock-movement-wizard/combined-shipments/SendMovementPage.jsx
- src/js/components/stock-movement-wizard/modals/CombinedShipmentItemsModal.jsx
- src/js/utils/Select.jsx
- src/js/utils/form-utils.jsx
- src/js/utils/form-values-utils.jsx
- src/main/groovy/org/pih/warehouse/api/StockMovementItem.groovy
**Link to GitHub issue or Jira ticket:** [OBPIH-6320](https://pihemr.atlassian.net/browse/OBPIH-6320)
---
[OBPIH-6320]: https://pihemr.atlassian.net/browse/OBPIH-6320?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OBPIH-6320 show supplier product name in tooltips

- grails-app/services/org/pih/warehouse/product/ProductService.groovy
> OBPIH-5739 Fix filtering for handling requirements in products list page

- grails-app/services/org/pih/warehouse/core/DocumentService.groovy
> OBPIH-6321 Wrap supplier name onto a next line in packing list document

- src/js/components/stock-movement-wizard/outbound/PackingPage.jsx
**Link to GitHub issue or Jira ticket:** https://pihemr.atlassian.net/browse/OBPIH-6802
**Description:** Added a dropdown to the "Recipients" header in the Pack step of a stock movement that will bulk set the recipient for all rows. Based on the changes in this PR: https://github.com/openboxes/openboxes/pull/4919
--- …
> OBPIH-6802 Bulk set recipient during a stock movement pack step

- grails-app/views/order/_orderInvoices.gsp
**Link to GitHub issue or Jira ticket:** [OBPIH-6320](https://pihemr.atlassian.net/browse/OBPIH-6320)
---
[OBPIH-6320]: https://pihemr.atlassian.net/browse/OBPIH-6320?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OBPIH-6813 Fix product source not displaying on invoice tab of PO show page

- grails-app/domain/org/pih/warehouse/core/Event.groovy
- grails-app/domain/org/pih/warehouse/receiving/Receipt.groovy
- grails-app/domain/org/pih/warehouse/shipping/Shipment.groovy
- grails-app/i18n/messages.properties
- src/main/groovy/org/pih/warehouse/core/EventCode.groovy
- src/main/groovy/org/pih/warehouse/core/Historiable.groovy
- src/main/groovy/org/pih/warehouse/core/Historizable.groovy
- src/main/groovy/org/pih/warehouse/core/HistoryItem.groovy
- src/main/groovy/org/pih/warehouse/core/ReferenceDocument.groovy
> OBPIH-6804 Build shipment history to display shipment events

- grails-app/controllers/org/pih/warehouse/inventory/StockMovementController.groovy
- grails-app/controllers/org/pih/warehouse/shipping/ShipmentController.groovy
- grails-app/domain/org/pih/warehouse/core/Event.groovy
- grails-app/domain/org/pih/warehouse/core/EventType.groovy
- grails-app/domain/org/pih/warehouse/core/Location.groovy
- grails-app/domain/org/pih/warehouse/receiving/Receipt.groovy
- grails-app/domain/org/pih/warehouse/shipping/Shipment.groovy
- grails-app/i18n/messages.properties
- grails-app/views/stockMovement/_events.gsp
- grails-app/views/stockMovement/show.gsp
- src/main/groovy/org/pih/warehouse/core/HistoryItem.groovy
> OBPIH-6472 Reintroduce shipment events tab in stock movement UI

- grails-app/services/org/pih/warehouse/order/OrderService.groovy
**Link to GitHub issue or Jira ticket:** https://pihemr.atlassian.net/browse/OBPIH-6825
**Description:** Fail importing order items if one of the recipients is an inactive user
---
[Screencast from 11-26-2024 09:42:37 AM.webm](https://github.com/user-attachments/assets/58e3606a-dad7-41f2-9b2e-b481fc32d678)
> OBPIH-6825 Fail order items import if recipient is an inactive user

- src/js/hooks/outboundImport/useOutboundImportForm.js
> OBPIH-6859 Handle unexpected errors in full outbound import

- grails-app/jobs/org/pih/warehouse/jobs/AssignIdentifierJob.groovy
- grails-app/services/org/pih/warehouse/core/IdentifierService.groovy
- grails-app/services/org/pih/warehouse/core/LocationIdentifierService.groovy
- grails-app/services/org/pih/warehouse/data/ProductSupplierIdentifierService.groovy
- grails-app/services/org/pih/warehouse/inventory/TransactionIdentifierService.groovy
- grails-app/services/org/pih/warehouse/invoice/InvoiceIdentifierService.groovy
- grails-app/services/org/pih/warehouse/order/OrderIdentifierService.groovy
- grails-app/services/org/pih/warehouse/order/PurchaseOrderIdentifierService.groovy
- grails-app/services/org/pih/warehouse/product/ProductIdentifierService.groovy
- grails-app/services/org/pih/warehouse/receiving/ReceiptIdentifierService.groovy
- grails-app/services/org/pih/warehouse/requisition/RequisitionIdentifierService.groovy
- grails-app/services/org/pih/warehouse/shipping/ShipmentIdentifierService.groovy
- src/main/groovy/org/pih/warehouse/core/identification/BlankIdentifierResolver.groovy
**Link to GitHub issue or Jira ticket:** https://pihemr.atlassian.net/browse/OBPIH-6864
**Description:** The AssignIdentifierJob wasn't running properly because it was unable to auto-wire in the BlankIdentifierResolver beans. This should work according to Springboot, but it's not worth the hassle trying to debug why it's not working here so I just switched it to wire in the BlankIdentifierResolver classes explicitly.
---
> *If this PR contains a UI change, consider adding one or more screenshots here or link to a screen recording to help …
> OBPIH-6864 Fix assign identifier job

- grails-app/controllers/org/pih/warehouse/inventory/StockMovementController.groovy
- grails-app/domain/org/pih/warehouse/inventory/OutboundStockMovement.groovy
- grails-app/services/org/pih/warehouse/inventory/StockMovementService.groovy
- grails-app/views/stockMovement/_comments.gsp
- grails-app/views/stockMovement/addComment.gsp
- grails-app/views/stockMovement/show.gsp
> OBPIH-6867 Add comments tab for PO shipments

- package-lock.json
- package.json
**Link to GitHub issue or Jira ticket:** https://pihemr.atlassian.net/browse/OBPIH-6837
**Description:** Because of the changes in packages in a newer version of react table I didn't have to use a forked library as a replacement for react-table version 6. I was able to add the newest version of the library and I tested it and it worked fine. The example that I tried to run in the app: https://tanstack.com/table/v8/docs/framework/react/examples/basic
---
> *If this PR contains a UI change, consider adding one or more screenshots here or …
> OBPIH-6837 TD: Install second react table package

- grails-app/controllers/org/pih/warehouse/shipping/ShipmentApiController.groovy
- grails-app/services/org/pih/warehouse/shipping/ShipmentService.groovy
- src/test/groovy/unit/org/pih/warehouse/api/ShipmentApiControllerTests.groovy
ShipmentApiController has been added to handle the requests from mobile app. 
Also method updates in ShipmentService to handle mobile feature as well as:
**Extracted Common Logic:** Moved repeated filtering logic to a helper method getShipmentsByCriteria.
**Improved Readability:** Simplified method structure by reducing redundancy.
**Added Flexibility:** Optional ordering parameters (orderByField, orderDirection) for sorting.
https://allofresh.atlassian.net/browse/WMS-3
related to: https://github.com/openboxes/openboxes-mobile/pull/276
> WMS-3 Add ShipmentApiController

- grails-app/controllers/org/pih/warehouse/UrlMappings.groovy
- grails-app/controllers/org/pih/warehouse/api/CycleCountApiController.groovy
- grails-app/domain/org/pih/warehouse/inventory/CycleCountCandidate.groovy
- grails-app/init/org/pih/warehouse/BootStrap.groovy
- grails-app/migrations/views/changelog.xml
- grails-app/migrations/views/cycle-count-session.sql
- grails-app/services/org/pih/warehouse/inventory/CycleCountService.groovy
- src/main/groovy/org/pih/warehouse/inventory/CycleCountCandidateFilterCommand.groovy
> OBPIH-6870 Add endpoint to fetch cycle count candidates

- README.md
**Link to GitHub issue or Jira ticket:** N/A
**Description:** As of MySQL 8, you can no longer create a user and grant them permissions in the same command. https://stackoverflow.com/questions/50177216/how-to-grant-all-privileges-to-root-user-in-mysql-8-0 Updated the readme to reflect this.
> Update openboxes sql user instructions

- grails-app/controllers/org/pih/warehouse/UrlMappings.groovy
- grails-app/controllers/org/pih/warehouse/api/CycleCountApiController.groovy
- grails-app/domain/org/pih/warehouse/inventory/CycleCountRequest.groovy
- grails-app/i18n/messages.properties
- grails-app/init/org/pih/warehouse/BootStrap.groovy
- grails-app/migrations/0.9.x/changelog-2024-12-18-1300-create-table-cycle-count-request.xml
- grails-app/migrations/0.9.x/changelog.xml
- grails-app/services/org/pih/warehouse/inventory/CycleCountService.groovy
- src/main/groovy/org/pih/warehouse/inventory/CycleCountRequestBatchCommand.groovy
- src/main/groovy/org/pih/warehouse/inventory/CycleCountRequestCommand.groovy
- src/main/groovy/org/pih/warehouse/inventory/CycleCountRequestStatus.groovy
- src/main/groovy/org/pih/warehouse/inventory/CycleCountRequestType.groovy
- src/main/groovy/org/pih/warehouse/inventory/CycleCountStatus.groovy
> OBPIH-6903 Implement cycle count request API (create)

- src/js/components/DataTable/v2/DataTable.jsx
- src/js/components/cycleCount/allProductsTab/CycleCountAllProducts.jsx
- src/js/hooks/useDataTable.js
Fixed pagination resetting to the first page after applying filters, ensuring filtered results are immediately visible.
---
> OBPIH-6927 fixed pagination bug

- grails-app/controllers/org/pih/warehouse/UrlMappings.groovy
- grails-app/controllers/org/pih/warehouse/api/CycleCountApiController.groovy
- grails-app/domain/org/pih/warehouse/inventory/CycleCountCandidate.groovy
- grails-app/migrations/views/cycle-count-session.sql
- grails-app/services/org/pih/warehouse/inventory/CycleCountService.groovy
- src/js/api/urls.js
- src/js/hooks/cycleCount/useAllProductsTab.jsx
- src/main/groovy/org/pih/warehouse/inventory/CycleCountCandidateFilterCommand.groovy
> OBPIH-6889 Implement get cycle counts API

- grails-app/i18n/messages.properties
- src/js/components/DataTable/v2/DataTableBody.jsx
- src/js/components/DataTable/v2/DataTableHeader.jsx
- src/js/components/cycleCount/allProductsTab/CycleCountAllProducts.jsx
- src/js/components/cycleCount/cycleCount.scss
- src/js/components/form-elements/v2/Checkbox.jsx
- src/js/components/form-elements/v2/style.scss
- src/js/hooks/cycleCount/useAllProductsTab.jsx
- src/js/hooks/useTableCheckboxes.js
**Description:** I modified the checkbox component to be able to use an indeterminate state. I also added a hook for managing checkboxes in the table.
---
> OBPIH-6846 Build checkbox logic

- src/js/hooks/cycleCount/useAllProductsTab.jsx
> OBPIH-6928 fixed incorrect redirect after clicking product link

- src/js/api/services/CycleCountApi.js
- src/js/api/urls.js
- src/js/components/cycleCount/CycleCount.jsx
- src/js/components/cycleCount/allProductsTab/CycleCountAllProducts.jsx
- src/js/hooks/cycleCount/useAllProductsTab.jsx
***This PR should be merged after OBPIH-6889 and OBPIH-6846***
> OBPIH-6848 Count selected button all products tab

- src/js/hooks/useTablePagination.js
> OBPIH-6932 Incorrect page indicator after changing rows per page

- src/js/components/cycleCount/cycleCount.scss
- src/js/hooks/cycleCount/useAllProductsTab.jsx
> OBPIH-6940 Adjust display of product name in cycle count tables to 2 rows only

- src/js/api/services/CycleCountApi.js
- src/js/api/urls.js
- src/js/hooks/cycleCount/useToCountTab.jsx
> OBPIH-6967 Connect start count API with the frontend

- grails-app/controllers/org/pih/warehouse/UrlMappings.groovy
- grails-app/controllers/org/pih/warehouse/api/CycleCountApiController.groovy
- grails-app/services/org/pih/warehouse/inventory/CycleCountService.groovy
> OBPIH-6966 Create an endpoint to get cycle counts

- grails-app/domain/org/pih/warehouse/inventory/CycleCountItem.groovy
- grails-app/migrations/0.9.x/changelog-2025-02-06-2200-drop-not-null-constraint-on-bin-location-in-cycle-count-item.xml
- grails-app/migrations/0.9.x/changelog.xml
> OBPIH-6978 Fix creating a cycle count item with the default bin assigned

- src/js/hooks/cycleCount/useToCountTab.jsx
> OBPIH-6940 Adjust display of product name in cycle count tables to 2 rows only (fix after QA)

- src/js/hooks/useTableCheckboxes.js
> OBPIH-6938 Checkbox state and indicator persist across location changes

- src/js/components/DataTable/v2/DataTableBody.jsx
- src/js/components/DataTable/v2/DataTableHeader.jsx
- src/js/hooks/cycleCount/useAllProductsTab.jsx
- src/js/hooks/cycleCount/useToCountTab.jsx
- src/js/hooks/cycleCount/useToResolveTab.jsx
> OBPIH-6941 Adjust columns widths in cycle count tables

- grails-app/i18n/messages.properties
- src/js/components/DataTable/DataTable.scss
- src/js/components/DataTable/v2/ArrowValueIndicator.jsx
- src/js/components/cycleCount/cycleCount.scss
- src/js/components/cycleCount/toResolveTab/ResolveStepTable.jsx
- src/js/consts/arrowValueIndicatorVariant.js
- src/js/hooks/cycleCount/useResolveStepTable.jsx
This PR should be merged after *OBPIH-6974*
---
> OBPIH-6975 Create component for columns with up vs down styling

- grails-app/controllers/org/pih/warehouse/UrlMappings.groovy
- grails-app/controllers/org/pih/warehouse/api/CycleCountApiController.groovy
- grails-app/domain/org/pih/warehouse/inventory/Transaction.groovy
- grails-app/i18n/messages.properties
- grails-app/migrations/0.9.x/changelog-2025-02-11-1530-add-column-cycle-count-to-transaction.xml
- grails-app/migrations/0.9.x/changelog-2025-02-12-1300-add-cycle-count-related-transaction-types.xml
- grails-app/migrations/0.9.x/changelog.xml
- grails-app/services/org/pih/warehouse/inventory/CycleCountService.groovy
- src/main/groovy/org/pih/warehouse/core/Constants.groovy
- src/main/groovy/org/pih/warehouse/inventory/CycleCountSubmitCountCommand.groovy
> OBPIH-6896 Implement perform count API

- src/js/components/cycleCount/CycleCount.jsx
- src/js/components/cycleCount/allProductsTab/CycleCountAllProducts.jsx
- src/js/hooks/cycleCount/useAllProductsTab.jsx
- src/js/hooks/cycleCount/useToCountTab.jsx
- src/js/hooks/cycleCount/useToResolveTab.jsx
- src/js/hooks/useTableDataV2.js
> OBPIH-6944 Content refreshes twice when switching tabs (fix)

- src/js/components/Filter/FilterForm.jsx
- src/js/components/Filter/FilterStyles.scss
- src/js/components/cycleCount/CycleCount.jsx
- src/js/components/cycleCount/CycleCountFilters.jsx
- src/js/hooks/cycleCount/useCycleCountFilters.js
I haven't found a better way to fix this bug at the moment. I've tried different methods in the clearFilterValues ​​function but it doesn't work
---
> OBPIH-6945 Incorrect bin location displayed after changing location

- src/css/main.scss
- src/js/components/DataTable/DataTable.scss
- src/js/components/DataTable/TableHeaderCell.jsx
- src/js/hooks/inboundV2/addItems/useInboundAddItemsColumns.jsx
- src/js/hooks/inboundV2/addItems/useInboundAddItemsForm.jsx
- src/js/wrappers/CustomTooltip.jsx
movement header is still static I planning to do the movement header when I will work on the next ticket
---
> OBPIH-6960 Create items array form (fix after QA)

- src/js/hooks/cycleCount/useAllProductsTab.jsx
- src/js/hooks/cycleCount/useToCountTab.jsx
- src/js/hooks/cycleCount/useToResolveTab.jsx
- src/js/utils/Badge.jsx
- src/js/utils/utils.scss
> OBPIH-7028 Show catalogue entries on one row only in lower resolutions

- src/js/components/form-elements/FilterSelectField.jsx
> OBPIH-7005 Allow multiselect in bin location filter without erasing string

- grails-app/services/org/pih/warehouse/importer/InventoryLevelImportDataService.groovy
Also, added fail-fast validation for inventory levels tied to internal locations
> OBPIH-7017 Fixed bug with imported inventory levels not being saved

- src/js/components/cycleCount/CycleCount.jsx
- src/js/components/cycleCount/allProductsTab/CycleCountAllProducts.jsx
- src/js/components/cycleCount/toCountTab/CycleCountToCount.jsx
- src/js/hooks/cycleCount/useAllProductsTab.jsx
- src/js/hooks/cycleCount/useToCountTab.jsx
- src/js/hooks/useTableCheckboxes.js
> OBPIH-6946 Apply checkbox on To Count tab after selecting from All Products tab

- src/js/components/cycleCount/CycleCount.jsx
The code should probably work. I tried to test it via ngrok, but there was a problem with that "http" browsers overwriting "https" and I tested it on an old browser "pale moon" on windows and it worked.
---
> OBPIH-6958 Jump back to top of the page when changing page

- src/main/groovy/org/pih/warehouse/inventory/CycleCountItemCommand.groovy
> OBPIH-6981 Fix creating a cycle count item with default bin

- grails-app/i18n/messages.properties
- src/js/components/cycleCount/toResolveTab/ResolveStepHeader.jsx
…nt instead of To Resolve)
---
> OBPIH-7055 Back button on Resolve page redirects to wrong tab (To Count instead of To Resolve)

- src/js/actions/index.js
- src/js/hooks/cycleCount/useCountStep.jsx
> OBPIH-7057 Continue resolve workflow with products from last count after save

- src/js/hooks/cycleCount/useToCountTab.jsx
- src/js/hooks/cycleCount/useToResolveTab.jsx
> OBPIH-7071 Count and Recount page do not immediately show the selected products

- grails-app/services/org/pih/warehouse/inventory/CycleCountService.groovy
> OBPIH-7072 Error occurs when adding a new line without a lot number

- grails-app/controllers/org/pih/warehouse/api/CycleCountApiController.groovy
- grails-app/services/org/pih/warehouse/inventory/CycleCountService.groovy
- src/main/groovy/org/pih/warehouse/inventory/CycleCountStartRecountBatchCommand.groovy
- src/main/groovy/org/pih/warehouse/inventory/CycleCountStartRecountCommand.groovy
> Fix resolving workflow to look for cycle count, not cycle count request

- src/js/hooks/cycleCount/useAllProductsTab.jsx
> OBPIH-6939 Show minimum of cycle count date and inventory in Last Counted date column

- grails-app/services/org/pih/warehouse/inventory/CycleCountService.groovy
**Link to GitHub issue or Jira ticket:** https://pihemr.atlassian.net/browse/OBPIH-6931
**Description:** Fixes a bug where a cycle count status was staying at "To count" (instead of moving to "In progress", even after being edited.
---
https://jam.dev/c/665fdbb2-861f-4c2b-b0e7-a689a76df42d
> OBPIH-6931 fix status not updating to "in progress" when editing a count

- grails-app/domain/org/pih/warehouse/inventory/CycleCount.groovy
- src/main/groovy/org/pih/warehouse/inventory/CycleCountItemStatus.groovy
- src/test/groovy/unit/org/pih/warehouse/inventory/CycleCountSpec.groovy
- src/test/groovy/unit/org/pih/warehouse/inventory/CycleCountTransactionServiceSpec.groovy
- src/test/groovy/unit/org/pih/warehouse/inventory/ProductInventoryTransactionServiceSpec.groovy
> OBPIH-7092 Fix issue related to null cycle count status

- src/js/hooks/cycleCount/useCountStep.jsx
> OBPIH-7071 Count and Recount page do not immediately show the selected products (fix after QA)

- src/js/hooks/cycleCount/useCountStep.jsx
> OBPIH-7094 Invalid redirect when finish to count without discrepancies

- grails-app/migrations/views/cycle-count-session.sql
- src/css/main.scss
- src/js/components/DataTable/TableCell.jsx
- src/js/hooks/cycleCount/useResolveStepTable.jsx
- src/js/wrappers/CustomTooltip.jsx
> OBPIH-7054 Expand "Root Cause" selector for better visibility

- grails-app/controllers/org/pih/warehouse/api/CycleCountApiController.groovy
- grails-app/services/org/pih/warehouse/inventory/CycleCountService.groovy
- grails-app/views/cycleCount/_printCount.gsp
- grails-app/views/cycleCount/_printRecount.gsp
- src/js/api/services/CycleCountApi.js
- src/js/hooks/cycleCount/useResolveStep.js
- fix NoSuchElementException on cycle count list action
- print assignee and date counted if filled
- fix printing count and recount form
- fix row height if row with default (null) bin and lot and empty expiry date
- remove unnecessary format adding to the params
> OBPIH-7015 Improve blind count form

- src/js/hooks/cycleCount/useCountStep.jsx
> OBPIH-7018 Fix erasing the draft when submitting a count

- src/js/components/cycleCount/ConfirmStepHeader.jsx
- src/js/components/cycleCount/toCountTab/CountStep.jsx
- src/js/hooks/cycleCount/useCountStep.jsx
- src/js/hooks/cycleCount/useCountStepTable.jsx
- src/js/utils/confirmationModalUtils.jsx
> OBPIH-7099 Prevent doing multiclik on Save on to count and recount steps

- src/js/components/cycleCount/ConfirmStepHeader.jsx
- src/js/components/cycleCount/toCountTab/CountStep.jsx
- src/js/components/cycleCount/toResolveTab/ResolveStep.jsx
- src/js/hooks/cycleCount/useCountStep.jsx
- src/js/hooks/cycleCount/useResolveStep.js
> OBPIH-7099 Fix disabling save button on count/recount step

- src/js/hooks/cycleCount/useCountStep.jsx
- src/js/hooks/cycleCount/useResolveStep.js
- src/js/utils/cycleCountUtils.jsx
> OBPIH-7125 Trim spaces for lot number while creating a cycle count item

- src/js/components/stock-movement-wizard/request/AddItemsPage.jsx
https://pihemr.atlassian.net/browse/OBPIH-6986 
Fix for the one of the issues with the recalculate (when `demandPerReplenishmentPeriod` was 0 it was not calculating properly)
> OBPIH-6986 Fix recalculating quantity requested on e-requests

- src/js/hooks/cycleCount/useAllProductsTab.jsx
- src/js/hooks/cycleCount/useToCountTab.jsx
- src/js/hooks/cycleCount/useToResolveTab.jsx
> OBPIH-7134 Fix blank cycle count tabs when qoh of a product changed to 0

- src/js/components/form-elements/FilterSelectField.jsx
> OBPIH-7152 Fix Single-select filter input issue

- grails-app/conf/runtime.groovy
- src/main/groovy/org/pih/warehouse/core/Constants.groovy
https://pihemr.atlassian.net/browse/OBPIH-7149
> OBPIH-7149 Fix default display date format

- grails-app/domain/org/pih/warehouse/inventory/CycleCountItem.groovy
- src/test/groovy/unit/org/pih/warehouse/inventory/CycleCountProductAvailabilityServiceSpec.groovy
- src/test/groovy/unit/org/pih/warehouse/inventory/CycleCountSpec.groovy
- src/test/groovy/unit/org/pih/warehouse/inventory/CycleCountTransactionServiceSpec.groovy
> OBPIH-7128 Fix bug with elements not being removed from a SortedSet

- src/css/main.scss
- src/js/components/DataTable/DataTable.scss
- src/js/components/stock-movement-wizard/inboundV2/inboundV2.scss
- src/js/hooks/inboundV2/addItems/useInboundAddItemsColumns.jsx
In this ticket, I used several styles from the ticket OBPIH-7150 to properly implement the recipient select
---
> OBPIH-7157 Add multi-fill for recipients in inbound add items

- grails-app/views/goodsReceiptNote/print.gsp
> OBPIH-6381 Wrap Text for long product names on Goods Receipt Note

- grails-app/views/deliveryNote/print.gsp
- grails-app/views/picklist/print.gsp
> OBPIH-6780 Add Page numbers on Picklist and Delivery Note

- grails-app/domain/org/pih/warehouse/inventory/CycleCount.groovy
- grails-app/i18n/messages.properties
- src/js/components/cycleCount/toResolveTab/ResolveStep.jsx
- src/js/components/cycleCount/toResolveTab/ResolveStepTable.jsx
- src/js/hooks/cycleCount/useResolveStep.js
- src/js/hooks/cycleCount/useResolveStepTable.jsx
I am creating a second pr with the rest of the changes from the https://github.com/openboxes/openboxes/pull/5193 without the changes in statuses
> OBPIH-7168 Delete all inventories when recount in progress (without status changes)

- src/js/hooks/cycleCount/useCycleCountFilters.js
> OBPIH-7231 Fix storing internal locations filter when refreshing a page

- src/js/components/receiving/PartialReceivingPage.jsx
> OBPIH-7236 Clicking 'X' on order dropdown causes infinite loading spinner in receiving page

- grails-app/controllers/org/pih/warehouse/api/CycleCountApiController.groovy
- grails-app/domain/org/pih/warehouse/inventory/CycleCount.groovy
- grails-app/services/org/pih/warehouse/inventory/CycleCountProductAvailabilityService.groovy
- grails-app/services/org/pih/warehouse/inventory/CycleCountService.groovy
- src/js/api/services/CycleCountApi.js
- src/js/hooks/cycleCount/useResolveStep.js
- src/test/groovy/unit/org/pih/warehouse/inventory/CycleCountProductAvailabilityServiceSpec.groovy
> OBPIH-7237 Fix reload issue for empty cycle count items

- grails-app/services/org/pih/warehouse/inventory/CycleCountService.groovy
> OBPIH-7237 Fix submitting a count/recount while having discrepancy

- src/css/main.scss
- src/js/components/DataTable/DataTable.scss
- src/js/components/DataTable/TableCell.jsx
- src/js/components/form-elements/v2/style.scss
- src/js/components/stock-movement-wizard/inboundV2/InboundV2.jsx
- src/js/components/stock-movement-wizard/inboundV2/inboundV2.scss
- src/js/components/stock-movement-wizard/inboundV2/sections/InboundV2AddItems.jsx
- src/js/components/stock-movement-wizard/inboundV2/sections/InboundV2Create.jsx
- src/js/consts/inboundColumns.js
- src/js/hooks/inboundV2/addItems/useInboundAddItemsColumns.jsx
- src/js/hooks/inboundV2/addItems/useInboundAddItemsForm.jsx
- src/js/hooks/inboundV2/addItems/useInboundAddItemsValidation.js
- src/js/hooks/useArrowsNavigation.jsx
In addition to adding arrow navigation, I also added an option to copy a cell. By using Ctrl + Arrow Down, you can copy the text/product. I also improved the table's appearance. The rows are smaller in height, and the table is larger in height. Additionally, when you're on the last row and in the last cell, pressing the down arrow will add a new row
---
> OBPIH-7150 Arrow navigation in inbound add items pages

- src/js/hooks/cycleCount/useCountStep.jsx
- src/js/hooks/cycleCount/useResolveStep.js
> OBPIH-7108 Save progress when clicking Next on count and recount workflows

- src/js/hooks/cycleCount/useCountStepTable.jsx
- src/js/hooks/cycleCount/useCycleCountFilters.js
- src/js/hooks/cycleCount/useResolveStepTable.jsx
- src/js/utils/groupBinLocationsByZone.jsx
> OBPIH-7042 Add Zone to Bin location filter in cycle count tabs

- src/js/hooks/inboundV2/addItems/useInboundAddItemsForm.jsx
- src/js/hooks/inboundV2/create/useInboundCreateForm.js
OBPIH-7157 Change comments
---
> OBPIH-7157 Add multi-fill for recipients in inbound add items (fix)

- grails-app/conf/application.yml
- grails-app/controllers/org/pih/warehouse/UrlMappings.groovy
- grails-app/controllers/org/pih/warehouse/api/PutawayItemApiController.groovy
- grails-app/services/org/pih/warehouse/putaway/PutawayService.groovy
- src/main/groovy/org/pih/warehouse/core/RoleType.groovy
> Migrate the `/api/locations/$id/putawayCandidates` endpoint to support the **Putaway Candidates** functionality on mobile.
> [WMS-16](https://allofresh.atlassian.net/browse/WMS-16)
> Use the `feature/okbn-integration` branch as a reference to enhance the existing **PutawayService** and **PutawayItemApiController** by adding the functionalities (methods) required for the mobile app.
> WMS-16 migrate missing putaway methods from obkn branch

- build.gradle
- grails-app/conf/application.yml
- grails-app/controllers/org/pih/warehouse/UrlMappings.groovy
- grails-app/controllers/org/pih/warehouse/shipping/ContainerApiController.groovy
- grails-app/domain/org/pih/warehouse/shipping/Container.groovy
- grails-app/services/org/pih/warehouse/core/DocumentService.groovy
- grails-app/services/org/pih/warehouse/core/IdentifierService.groovy
- grails-app/services/org/pih/warehouse/core/ZebraService.groovy
- grails-app/services/org/pih/warehouse/shipping/ShipmentIdentifierService.groovy
- grails-app/services/org/pih/warehouse/shipping/ShipmentService.groovy
- src/main/groovy/org/pih/warehouse/core/Constants.groovy
- src/main/groovy/org/pih/warehouse/inventory/LotStatusCode.groovy
- added ContainerApiController from obkn branch
https://allofresh.atlassian.net/browse/WMS-20
> WMS-20 add ContainerApiController

- grails-app/controllers/org/pih/warehouse/api/ApiController.groovy
- grails-app/services/org/pih/warehouse/api/SearchService.groovy
- grails-app/services/org/pih/warehouse/core/LocationService.groovy
- grails-app/services/org/pih/warehouse/inventory/ProductAvailabilityService.groovy
Adding logic for new endpoint globalSearch that is used by mobile to search the barcodes.
https://allofresh.atlassian.net/browse/WMS-25
> WMS-25 Add global search endpoint

- grails-app/i18n/messages.properties
- src/css/colors.scss
- src/js/components/DataTable/DataTable.scss
- src/js/components/DataTable/v2/ValueIndicator.jsx
- src/js/consts/valueIndicatorVariant.js
- src/js/hooks/cycleCount/useResolveStepTable.jsx
> OBPIH-7242 Create "box" component for alignment and transaction type columns

- grails-app/services/org/pih/warehouse/inventory/CycleCountService.groovy
- src/js/hooks/cycleCount/useCountStep.jsx
**Link to GitHub issue or Jira ticket:** https://pihemr.atlassian.net/browse/OBPIH-7268
**Description:** Given we're going to implement importing cycle counts via xls, we need to make some improvements to the xls export, mainly to also export any user input fields, ie Quantity Counted, Comment, User Counted, and Date Counted.
---
Count export with current count data included:
> OBPIH-7268 include user input fields in count export

- grails-app/i18n/messages.properties
- src/js/components/DataTable/v2/DataTable.jsx
- src/js/components/DataTable/v2/DataTableBody.jsx
- src/js/components/DataTable/v2/DataTableHeader.jsx
- src/js/components/Filter/FilterForm.jsx
- src/js/components/cycleCountReporting/CycleCountReporting.jsx
- src/js/components/cycleCountReporting/CycleCountReportingFilterFields.jsx
- src/js/components/cycleCountReporting/CycleCountReportingFilters.jsx
- src/js/components/cycleCountReporting/InventoryTransactionsTab.jsx
- src/js/hooks/cycleCount/useInventoryTransactionsTab.jsx
- src/js/hooks/cycleCountReporting/useCycleCountReportingFilters.js
- src/js/hooks/useCycleCountPagination.js
- src/js/hooks/useTableDataV2.js
- src/js/hooks/useTablePagination.js
- src/js/utils/getCommonPinningStyles.jsx
> OBPIH-7246 Product and Transaction date filters for inventory transactions report

- grails-app/controllers/org/pih/warehouse/api/PutawayApiController.groovy
https://openboxes.atlassian.net/browse/OB-3223
- Putaway items were duplicated (during the process).
---
Before:
After:
> OB-3223 do not duplicate putaway items

- src/js/components/cycleCount/allProductsTab/CycleCountAllProducts.jsx
- src/js/components/cycleCount/toCountTab/CycleCountToCount.jsx
- src/js/components/cycleCount/toResolveTab/CycleCountToResolve.jsx
- src/js/hooks/cycleCount/useAllProductsTab.jsx
- src/js/hooks/cycleCount/useToCountTab.jsx
- src/js/hooks/cycleCount/useToResolveTab.jsx
- src/js/hooks/useCycleCountPagination.js
- src/js/hooks/useTableDataV2.js
- src/js/hooks/useTablePagination.js
> OBPIH-7093 Small search and pagination issue on cc lists

- src/js/components/cycleCountReporting/CycleCountReportingFilterFields.jsx
- src/js/hooks/useDataTable.js
> OBPIH-7246 Change filters order and fix table fixed position

- grails-app/services/org/pih/warehouse/product/ProductMergeService.groovy
**Link to GitHub issue or Jira ticket:** https://pihemr.atlassian.net/browse/OBPIH-7196
**Description:** Switch the product merge feature to use the new inventory baseline transaction type.
> OBPIH-7196 switch product merge to use baseline transaction type

- src/css/main.scss
- src/js/components/cycleCountReporting/CycleCountReportingFilterFields.jsx
- src/js/components/form-elements/DateFilter/DateFilter.jsx
- src/js/hooks/cycleCount/useInventoryTransactionsTab.jsx
- src/js/tests/menu/__snapshots__/Wizard.test.jsx.snap
- src/js/utils/form-utils.jsx
> OBPIH-7241 Create table component for inventory transactions report (fix)

- src/js/hooks/cycleCount/useInventoryTransactionsTab.jsx
> OBPIH-7241 Create table component for inventory transactions report (improvement)

- grails-app/controllers/org/pih/warehouse/api/MobileProductApiController.groovy
https://openboxes.atlassian.net/browse/OB-3223
- Include `productType` when fetching product by id (mobile).
> OB-3223 include productType when fetching (mobile)

- src/js/hooks/cycleCount/useCountStep.jsx
> OBPIH-7270 Fix updating non-custom rows from import

- src/css/main.scss
- src/js/components/cycleCount/toCountTab/CountStep.jsx
- src/js/components/cycleCount/toResolveTab/ResolveStep.jsx
- src/js/hooks/cycleCount/useCountStepTable.jsx
- src/js/hooks/cycleCount/useResolveStepTable.jsx
- src/js/hooks/useTablePagination.js
> OBPIH-7115 Prevent access to cycle count from another location (fix after QA)

- src/js/components/cycleCount/toCountTab/CountStep.jsx
- src/js/components/cycleCount/toCountTab/CountStepTable.jsx
- src/js/components/cycleCount/toResolveTab/ResolveStep.jsx
- src/js/components/cycleCount/toResolveTab/ResolveStepTable.jsx
- src/js/hooks/cycleCount/useCountStep.jsx
- src/js/hooks/cycleCount/useCountStepValidation.js
- src/js/hooks/cycleCount/useResolveStep.js
- src/js/hooks/cycleCount/useResolveStepValidation.js
> OBPIH-7294 Fallback to current user for counted by and recounted by

- grails-app/services/org/pih/warehouse/inventory/CycleCountService.groovy
**Link to GitHub issue or Jira ticket:** https://pihemr.atlassian.net/browse/OBPIH-7332
**Description:** Export CC was leaving quantity counted blank in the xls when quantityCounted was 0.
> OBPIH-7332 export CC when quantity counted is 0

- grails-app/controllers/org/pih/warehouse/api/CycleCountApiController.groovy
- grails-app/i18n/messages.properties
- grails-app/services/org/pih/warehouse/inventory/CycleCountService.groovy
- src/js/api/services/CycleCountApi.js
- src/js/components/cycleCount/toCountTab/CountStep.jsx
- src/js/components/cycleCount/toCountTab/CountStepHeader.jsx
- src/js/components/cycleCount/toResolveTab/ResolveStep.jsx
- src/js/components/cycleCount/toResolveTab/ResolveStepHeader.jsx
- src/js/hooks/cycleCount/useCountStep.jsx
- src/js/hooks/cycleCount/useResolveStep.js
> OBPIH-7309 Sort in alphabetical order in count and recount workflows

- src/js/components/cycleCount/toCountTab/CountStepHeader.jsx
- src/js/components/cycleCount/toResolveTab/ResolveStepHeader.jsx
> OBPIH-7309 Reverse color logic of alphabetical sort button (fix)

- src/css/main.scss
- src/js/components/cycleCount/toCountTab/CountStepHeader.jsx
- src/js/components/form-elements/v2/ButtonFileSelect.jsx
- src/js/hooks/cycleCount/useInventoryTransactionsTab.jsx
> OBPIH-7258 Fix display root causes and comments + improve disabling "Import Count" button

- grails-app/services/org/pih/warehouse/inventory/CycleCountService.groovy
- src/main/groovy/org/pih/warehouse/inventory/CycleCountDto.groovy
**Link to GitHub issue or Jira ticket:** https://pihemr.atlassian.net/browse/OBPIH-7337
**Description:** Modified CycleCountService.getRecountFormXls to also export the value of “Quantity Recounted“, "Root Cause", “Comment“, “User Recounted“, and “Date Recounted“.
---
> OBPIH-7337 export recount enhancements

- grails-app/controllers/org/pih/warehouse/api/CycleCountApiController.groovy
- grails-app/services/org/pih/warehouse/inventory/CycleCountImportService.groovy
- grails-app/services/org/pih/warehouse/inventory/CycleCountService.groovy
- src/js/components/cycleCount/toCountTab/CountStep.jsx
- src/js/components/cycleCount/toCountTab/CountStepHeader.jsx
- src/js/hooks/cycleCount/useCountStep.jsx
- src/main/groovy/org/pih/warehouse/importer/CycleCountItemsExcelImporter.groovy
> OBPIH-7271 Handle invalid count import

- src/js/hooks/cycleCount/useCountStep.jsx
- src/js/hooks/cycleCount/useResolveStep.js
> OBPIH-7294 Fallback to current user for counted by and recounted by (fix)

- src/js/consts/cycleCountCandidateStatus.js
- src/js/hooks/cycleCount/useCycleCountProductAvailability.jsx
- src/js/hooks/cycleCount/useToCountTab.jsx
> OBPIH-7046 Don't block count for 'In Progress' products (fix)

- src/js/consts/valueIndicatorVariant.js
- src/js/hooks/cycleCount/useInventoryTransactionsTab.jsx
- src/js/hooks/cycleCount/useProductsTab.jsx
- src/js/hooks/cycleCount/useResolveStepTable.jsx
https://pihemr.atlassian.net/browse/OBPIH-7260
---
> OBPIH-7260 Fix recount difference calculation when input is 0 in recount table

- src/js/hooks/cycleCount/useProductsTab.jsx
- src/js/utils/formatCurrency.jsx
> OBPIH-7260 Fix format currency values and months of stock change

- grails-app/migrations/views/cycle-count-details.sql
> OBPIH-7366 Fix performance issues of cycle_count_details view on MySQL

- src/js/hooks/cycleCount/useResolveStep.js
- src/js/reducers/cycleCountReducer.js
> OBPIH-7365 Unable to finish recount when perform any change on stock card

- grails-app/services/org/pih/warehouse/report/ReportService.groovy
- src/js/components/cycleCountReporting/CycleCountReporting.jsx
- src/js/components/cycleCountReporting/IndicatorsTab/IndicatorsTab.jsx
- src/js/hooks/cycleCount/useIndicatorsTab.jsx
> OBPIH-7322 Create indicator: products inventoried (fix after QA)

- grails-app/services/org/pih/warehouse/report/ReportService.groovy
> OBPIH-7322 Create indicator: products inventoried (fix)

- src/js/components/cycleCount/CycleCount.jsx
**Link to GitHub issue or Jira ticket:** https://pihemr.atlassian.net/browse/OBPIH-7341
**Description:** The approval cycle count feature was never implemented and so we needed to remove the tab since it was always empty.
> OBPIH-7341 hide 'to approve' tab in cycle count

- grails-app/init/org/pih/warehouse/BootStrap.groovy
**Link to GitHub issue or Jira ticket:** https://openboxes.atlassian.net/browse/OB-3260
- Provide the info about bin's location type.
---
> OB-3260: pass down the bin location type

- grails-app/jobs/org/pih/warehouse/jobs/AutomaticReceiptJob.groovy
**Link to GitHub issue or Jira ticket:** https://openboxes.atlassian.net/browse/OB-3254
- [Auto Receive] Check if the shipment has a SHIPPED event associated.
---
> OB-3254 Check if the shipment has shipped event associated

- grails-app/services/org/pih/warehouse/inventory/InventoryTransactionSummaryService.groovy
- src/js/components/cycleCountReporting/CycleCountReporting.jsx
- src/js/hooks/cycleCount/useInventoryTransactionsTab.jsx
https://pihemr.atlassian.net/browse/OBPIH-7353
---
> OBPIH-7353 UI changes: sort and number of rows on inventory transactions report

- grails-app/services/org/pih/warehouse/core/DashboardService.groovy
https://pihemr.atlassian.net/browse/OBPIH-7449
---
> OBPIH-7449 Correct Most Recent Stock Count date in Export Latest Inventory Date report

- grails-app/services/org/pih/warehouse/report/ReportService.groovy
> OBPIH-7434 Fix number of counts not being displayed properly

- src/js/hooks/cycleCount/useAssignCycleCountModal.jsx
…n modal
https://pihemr.atlassian.net/browse/OBPIH-7464
---
> OBPIH-7464 Prevent backspace from deselecting assignee field in Assign modal

- grails-app/services/org/pih/warehouse/importer/ProductSupplierImportDataService.groovy
https://pihemr.atlassian.net/browse/OBPIH-7457
---
> OBPIH-7457 Fix prevent adding supplier as manufacturer via import

- grails-app/services/org/pih/warehouse/core/ConfigService.groovy
- grails-app/services/org/pih/warehouse/dashboard/IndicatorDataService.groovy
https://pihemr.atlassian.net/browse/OBPIH-7452
---
> OBPIH-7452 Fix last stock count for items with backdated shipments to include transactions without baselines

- grails-app/conf/application.yml
- grails-app/services/org/pih/warehouse/data/MigrationService.groovy
- grails-app/services/org/pih/warehouse/inventory/InventoryService.groovy
- grails-app/views/migration/dataMigration.gsp
https://pihemr.atlassian.net/browse/OBPIH-7462
This change is purely for the locations that have a lot of transactions to be migrated, like the Distribution Center.
> OBPIH-7462 Limit number of old product inventory transactions migrated at once

- src/js/components/cycleCountReporting/InventoryTransactionsTab.jsx
- src/js/components/cycleCountReporting/ProductsTab.jsx
- src/js/hooks/cycleCount/useInventoryTransactionsTab.jsx
- src/js/hooks/cycleCount/useProductsTab.jsx
https://pihemr.atlassian.net/browse/OBPIH-7466
---
> OBPIH-7466 Hide Export button on Products and Transactions reports

- grails-app/conf/logback-spring.xml
- grails-app/controllers/org/pih/warehouse/RoleInterceptor.groovy
- grails-app/controllers/org/pih/warehouse/UrlMappings.groovy
- grails-app/controllers/org/pih/warehouse/api/ApiController.groovy
- grails-app/controllers/org/pih/warehouse/api/putaway/PutawayTaskApiController.groovy
- grails-app/controllers/org/pih/warehouse/api/putaway/PutawayUrlMappings.groovy
- grails-app/controllers/org/pih/warehouse/api/putaway/SearchPutawayTaskCommand.groovy
- grails-app/controllers/org/pih/warehouse/core/ErrorsController.groovy
- grails-app/controllers/org/pih/warehouse/data/DataExportController.groovy
- grails-app/controllers/org/pih/warehouse/putaway/PutAwayController.groovy
- grails-app/domain/org/pih/warehouse/order/OrderItem.groovy
- grails-app/domain/org/pih/warehouse/putaway/PutawayTask.groovy
- grails-app/init/org/pih/warehouse/BootStrap.groovy
- grails-app/migrations/0.9.x/changelog-2025-08-25-1347-create-table-putaway-task.xml
- grails-app/migrations/0.9.x/changelog-2025-08-31-1654-add-column-order-item-container-location.xml
- grails-app/migrations/0.9.x/changelog.xml
- grails-app/migrations/views/changelog.xml
- grails-app/migrations/views/putaway-task.sql
- grails-app/services/org/pih/warehouse/core/UserService.groovy
- grails-app/services/org/pih/warehouse/putaway/PutawayService.groovy
- grails-app/services/org/pih/warehouse/putaway/PutawayTaskCompletedEventService.groovy
- grails-app/services/org/pih/warehouse/putaway/PutawayTaskService.groovy
- grails-app/views/order/_summary.gsp
- src/main/groovy/org/pih/warehouse/api/Putaway.groovy
- src/main/groovy/org/pih/warehouse/api/PutawayTaskAdapter.groovy
- src/main/groovy/org/pih/warehouse/api/PutawayTaskStatus.groovy
- src/main/groovy/org/pih/warehouse/api/StatusCategory.groovy
- src/main/groovy/org/pih/warehouse/putaway/PutawayTaskCompletedEvent.groovy
Video describing current state of the putaway task API
https://app.screencastify.com/watch/sGBRQdjjlNDbnTslhkru
> OBLS-126 Create initial version of putaway task API

- grails-app/services/org/pih/warehouse/core/OrganizationIdentifierService.groovy
- src/test/groovy/unit/org/pih/warehouse/organization/OrganizationIdentifierServiceSpec.groovy
**Link to GitHub issue or Jira ticket:** https://pihemr.atlassian.net/browse/OBPIH-7441
**Description:** ~~This doesn't fix the issue on prod. I just wanted to create some tests so that we could better understand what the current behaviour is. We can add to this PR if we want to push a code fix to the identifier service, or we can leave the PR as is and just keep it as unit tests.~~
EDIT: This now properly fixes organization identifier generation. There are still some cases that I opted not to solve in this PR that I left as TODOs instead.
> OBPIH-7441 refactor org identifier generation

- grails-app/conf/runtime.groovy
Change `putAway` to `putaway`.
> Correct a create putaway url

- grails-app/views/putaway/_putawaySummary.gsp
- grails-app/views/putaway/show.gsp
**Link to GitHub issue or Jira ticket:** https://openboxes.atlassian.net/browse/OBLS-140
- Fix status display
> OBLS-140 fix status display

- src/test/groovy/unit/org/pih/warehouse/product/ProductServiceSpec.groovy
**Link to GitHub issue or Jira ticket:** https://pihemr.atlassian.net/browse/OBPIH-7479
**Description:** The backend tests (executed via `grails test-app`) are failing which is breaking our build. Time to figure out why.
> OBPIH-7479 Fix failing backend tests

- .github/workflows/backend-tests.yml
- .github/workflows/dbdocs.yml
- .github/workflows/do-github-release.yml
- build.gradle
**Link to GitHub issue or Jira ticket:** closes https://github.com/openboxes/openboxes/issues/4049
**Description:** GitHub Action for auto-generating our openboxes.dbml file and uploading it to the dbdocs site
> autogenerate and publish dbdocs when a schema change is submitted
